/* Copyright (c) 2026 Tamilselvan R  SPDX-License-Identifier: MIT */
/*
 * value_noise_showcase.c
 *   — Lance Williams / Ken Perlin's value noise: the 1980s ancestor
 *     of gradient noise. Thirty patterns across six complexity tiers
 *     show what you can build from "random scalars on a lattice +
 *     interpolation" alone.
 *
 * DEMO: A scalar field generated by sampling pseudo-random values at
 *       every integer lattice point and interpolating them across the
 *       cells in between. Older and simpler than Perlin's 1985
 *       gradient noise — and visually shows WHY Perlin invented the
 *       gradient variant: value noise leaks visible axis-aligned
 *       artefacts along the integer grid that gradient noise does not.
 *       Thirty patterns, grouped into six tiers ordered simple →
 *       complex:
 *         Tier 1 INTERPOLATION — value noise's defining knob
 *                                 (SMOOTH, LINEAR, BLOCKY, QUINTIC,
 *                                  COSINE)
 *         Tier 2 STACKS        — fBm and family (FBM_2, FBM, FBM_6,
 *                                 TURBULENCE, RIDGED)
 *         Tier 3 MAPPED        — post-transforms of one fBm
 *                                 (CONTOURS, THRESHOLD, WAVES, POW2,
 *                                  SQRT)
 *         Tier 4 WARPED        — domain-space transforms (WARP,
 *                                 WISPS, ROTATE, SHIFTED, ZOOMED)
 *         Tier 5 COMPOSITES    — multiple value-noise samples combined
 *                                 (MULT, ADD, DIFF, MARBLE, NEBULA)
 *         Tier 6 EFFECTS       — heavier transforms / visual idioms
 *                                 (PLASMA, STORM, LIGHTNING, STARS,
 *                                  AURORA)
 *       Field drifts so every pattern evolves. Cycle patterns with
 *       n/p, themes with t/T.
 *
 * Study alongside:
 *   ./perin_noise_flow_showcase.c — Perlin 1985 gradient noise. The
 *       SUCCESSOR to value noise. The grid bias visible in this file's
 *       SMOOTH pattern is exactly what gradient interpolation fixes.
 *   ./simplex_noise_clouds.c — Simplex (Perlin 2001). The next step
 *       again: triangular lattice instead of square.
 *
 * Section map:
 *   §1 config   — grid, patterns, scale, themes
 *   §2 clock    — monotonic timer + sleep
 *   §3 color    — HUD reserved + 10 themes (4 palette colours each)
 *   §5 noise    — hash, lattice value, 5 interp modes, fBm + helpers
 *   §6 patterns — 30 derived visualisations + dispatch table
 *   §7 scene    — Field, scene state, per-frame grid update
 *   §8 screen   — ASCII render: density-graded glyphs
 *   §9 app      — signals, resize, main loop
 *
 * Keys:
 *   q / ESC    quit
 *   space      pause / resume
 *   r          reset (new hash seed)
 *   n / N      next pattern
 *   p / P      previous pattern
 *   t / T      next / previous theme
 *   + / =      faster drift
 *   -          slower
 *   ] / [      raise / lower tick Hz
 *
 * Build:
 *   gcc -std=c11 -O2 -Wall -Wextra value_noise_showcase.c \
 *       -o value_noise -lncurses -lm
 */

/* ── CONCEPTS ──────────────────────────────────────────────────────────── *
 *
 * Algorithm      : Value noise. The original procedural-noise idea,
 *                  predating Perlin gradient noise. For any query
 *                  point (x, y):
 *                    1. Find the integer cell (xi, yi) containing it.
 *                    2. Look up four random SCALARS, one per cell
 *                       corner, via a hash of the corner coords.
 *                    3. Compute the query's fractional position
 *                       (fx, fy) ∈ [0, 1)² inside the cell.
 *                    4. Interpolate the four corner scalars:
 *                       - SMOOTH:  smoothstep then bilerp
 *                       - LINEAR:  raw bilerp (no smoothstep)
 *                       - BLOCKY:  nearest-neighbor (no interp)
 *                    5. Output is the interpolated scalar ∈ [0, 1].
 *
 *                  Gradient noise (Perlin) replaces step (2) with
 *                  random VECTORS and computes dot(grad, offset)
 *                  per corner. The dot-product cancels the value
 *                  at the corner itself, removing the lattice bias
 *                  visible in value noise.
 *
 * Data-structure : ValueNoise struct holds the ONLY mutable state —
 *                  a single uint32_t seed, re-rolled on reset. No
 *                  pre-allocated value grid: every corner scalar is
 *                  computed on demand via
 *                  hash(cell_x, cell_y, seed) → uint32 → float-[0,1].
 *
 *                  Per-cell glow + band buffers (GlowField in §7) as
 *                  in the sibling noise showcases. Buffers
 *                  overwritten in full on every sim tick.
 *
 * Rendering      : ASCII only. Density-graded glyphs ('.', '*', '#')
 *                  in 4 theme palette colours, picked via GlyphRamp
 *                  in §7. Glow comes directly from the noise value;
 *                  band index from the glow quartile via
 *                  band_from_glow().
 *
 * Performance    : Tier-1 INTERPOLATION / Tier-3 MAPPED patterns:
 *                  O(1) per cell — 4 hash lookups + 1-3 lerps.
 *                  Tier-2 STACKS: 4 (FBM) to 6 (FBM_6) noise samples
 *                  per cell. Tier-4 WARPED / Tier-5 COMPOSITES /
 *                  Tier-6 EFFECTS: 2-3 fbm calls per cell = up to
 *                  ~18 noise samples per cell at the heaviest.
 *                  Worst case on a 200×56 grid at 60 Hz is ~12 M
 *                  hashes/sec — still well under CPU budget. The
 *                  4-mul integer hash mixer is the dominant cost.
 *
 * References     : NOISE THEORY (foundational)
 *                  • Williams, L. (1983) — "Pyramidal parametrics",
 *                    SIGGRAPH'83. Among the first to discuss random-
 *                    scalar-lattice noise in the context of texture
 *                    synthesis. The historical "before" of Perlin.
 *                  • Perlin, K. (1985) — "An Image Synthesizer",
 *                    SIGGRAPH'85. The gradient-noise paper that
 *                    explicitly contrasts itself with the older
 *                    value-noise approach implemented here. Also
 *                    defines fBm and Σ|noise(2ⁱx)| turbulence in §5.
 *                  • Perlin, K. (2002) — "Improving Noise", SIGGRAPH'02
 *                    / TOG 21(3). Introduces the 6t⁵−15t⁴+10t³ quintic
 *                    interpolant used by our Tier-1 QUINTIC pattern
 *                    (zero first AND second derivatives at endpoints).
 *                  • Ebert, Musgrave, Peachey, Perlin, Worley —
 *                    "Texturing & Modeling: A Procedural Approach"
 *                    (Morgan Kaufmann, 3rd ed. 2002, ISBN
 *                    1-55860-848-6). Chapter 2 walks through value
 *                    noise, gradient noise, and value-gradient hybrids
 *                    in canonical detail.
 *
 *                  fBm AND DERIVED TECHNIQUES
 *                  • Mandelbrot, B. (1982) — "The Fractal Geometry of
 *                    Nature". The original fBm definition; the
 *                    mathematical basis for Tier-2 STACKS.
 *                  • Quilez, I. — "fbm". Augmented fBm techniques
 *                    (amplitude warping, derivative-domain variants).
 *                    Tier-2 reference:
 *                    https://iquilezles.org/articles/fbm/
 *                  • Quilez, I. — "Domain warping". Direct source
 *                    for Tier-4 WARP — IQ's fbm(p + fbm(p))
 *                    construction applied to value noise here:
 *                    https://iquilezles.org/articles/warp/
 *
 *                  ASCII RENDERING (noise → terminal)
 *                  • Bourke, P. — "Character representation of grey
 *                    scale images". Canonical luminance ramps; the
 *                    GlyphRamp '.', '*', '#' is a coarse subset of
 *                    his 10-char ramp:
 *                    http://paulbourke.net/dataformats/asciiart/
 *                  • Wikipedia — "ANSI escape code § 8-bit". The
 *                    xterm/ANSI 256-colour palette (16 system + 6³
 *                    cube + 24 greys) that themes[] in §1 indexes:
 *                    https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit
 *                  • Padala, P. — "NCURSES Programming HOWTO".
 *                    Pragmatic reference for the §3/§8 rendering
 *                    APIs (init_pair, mvaddch, doupdate, A_BOLD):
 *                    https://tldp.org/HOWTO/NCURSES-Programming-HOWTO/
 *
 *                  COMPARE IN PROJECT
 *                  • ./perin_noise_flow_showcase.c — Perlin 1985
 *                    gradient noise. THE successor to value noise;
 *                    fixes the axis-aligned lattice artefacts that
 *                    Tier-1 BLOCKY / LINEAR / SMOOTH demonstrate.
 *                  • ./simplex_noise_clouds.c — Perlin 2001 simplex.
 *                    Next step after gradient noise: triangular
 *                    lattice instead of square.
 *                  • ./worley_cellular_noise.c — cellular / Voronoi
 *                    noise. Different family entirely — distance to
 *                    feature points instead of interpolation.
 *
 * ─────────────────────────────────────────────────────────────────────── */

/* ── MENTAL MODEL ─────────────────────────────────────────────────────── *
 *
 * CORE IDEA
 * ─────────
 * Put a random scalar at every integer lattice point. To sample at
 * any point in between, interpolate the surrounding four values.
 * That's the entire algorithm.
 *
 * The QUALITY of the result depends ENTIRELY on the interpolation
 * scheme:
 *   - nearest-neighbor → blocky tiles (BLOCKY pattern)
 *   - linear           → pyramid tents at each corner (LINEAR)
 *   - smoothstep+lerp  → smooth-but-grid-biased (SMOOTH)
 *
 * HOW TO THINK ABOUT IT
 * ─────────────────────
 * Imagine a grid of height-marked posts at every integer (x, y).
 * Each post's height is random but the SAME random height every time
 * (because hash(x, y, seed) is deterministic). To find the height at
 * any non-integer point, look at the four posts surrounding you and
 * blend. The smoother your blend function, the less the grid shows
 * through.
 *
 * Even with smoothstep, value noise has a tell: AT each lattice
 * point, the noise value is EXACTLY the random scalar at that point
 * (the blend collapses to one corner). So scanning a horizontal line
 * past lattice points gives a curve that touches the random values
 * EXACTLY at integer x. Gradient noise (Perlin) doesn't have this
 * property — at lattice points the value is always 0, and only the
 * SLOPE is random.
 *
 * ALGORITHM IN STEPS  (per cell, per frame)
 * ──────────────────
 *  1. Convert cell coordinate to noise space: (fx, fy) = (x, y) ·
 *     NOISE_SCALE + (0, t) for the time drift.
 *  2. Find integer corner: (xi, yi) = (⌊fx⌋, ⌊fy⌋).
 *  3. Fractional position in cell: (ux, uy) = (fx − xi, fy − yi).
 *  4. Look up four corner scalars:
 *       v00 = hash_to_unit(xi,     yi)
 *       v10 = hash_to_unit(xi + 1, yi)
 *       v01 = hash_to_unit(xi,     yi + 1)
 *       v11 = hash_to_unit(xi + 1, yi + 1)
 *  5. Interpolate per the active pattern's rule:
 *       BLOCKY  : v_nearest(ux, uy)
 *       LINEAR  : bilerp(v00, v10, v01, v11; ux, uy)
 *       SMOOTH  : bilerp with smoothstep(ux), smoothstep(uy)
 *       FBM     : sum SMOOTH at 4 octaves with halving amplitude
 *       TURBUL. : sum |SMOOTH| at 4 octaves
 *  6. Map noise → glow ∈ [0, 1] and band ∈ {0, 1, 2, 3}.
 *  7. Write to GlowField.glow[cell] / GlowField.band[cell].
 *
 * KEY FORMULAS
 * ────────────
 *  Smoothstep                  : s(t) = t² · (3 − 2t),  t ∈ [0, 1]
 *  Bilinear interp             : lerp(lerp(v00, v10, ux),
 *                                     lerp(v01, v11, ux), uy)
 *  Hash → unit-float           : (hash32(...) & 0xFFFFFF) / 2²⁴
 *  fBm                         : Σᵢ aᵢ · value(2ⁱ x), aᵢ = 1/2ⁱ
 *  Turbulence                  : Σᵢ aᵢ · |value(2ⁱ x)|
 *
 * ─────────────────────────────────────────────────────────────────────── */

#define _POSIX_C_SOURCE 200809L

#include <math.h>
#include <ncurses.h>
#include <signal.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ===================================================================== */
/* §1  config                                                             */
/* ===================================================================== */

enum {
    MAP_W_MAX         = 200,
    MAP_H_MAX         =  56,
    CELLS_MAX         = MAP_W_MAX * MAP_H_MAX,

    SIM_FPS_MIN       =  10,
    SIM_FPS_DEFAULT   =  60,
    SIM_FPS_MAX       = 240,
    SIM_FPS_STEP      =  10,

    HUD_COLS          =  72,
    FPS_UPDATE_MS     = 500,

    /* Color pair indices — PAIR_HUD/PAIR_HINT reserved per CLAUDE.md. */
    PAIR_HUD          =   1,
    PAIR_HINT         =   2,
    PAIR_BAND_BASE    =   3,    /* PAIR_BAND_BASE..+3 = 4 palette colours */
    PAIR_FLASH        =   7,    /* vestigial — cross-file palette parity  */
};

#define GLOW_THRESHOLD      0.05f

/* HUD layout — top carries data, bottom carries actions. */
#define HUD_TOP_ROWS             2
#define HUD_BOTTOM_ROWS          1
#define HUD_BAND_RESERVED_ROWS   (HUD_TOP_ROWS + HUD_BOTTOM_ROWS)
#define HUD_LEFT_MARGIN          1

/* Noise scale: ~0.10 noise-units per cell → ~10 cells between lattice
 * points → ~20 × 6 lattice cells across the 200×56 grid. Big enough
 * that the grid bias of value noise is visible at all. */
#define NOISE_SCALE         0.10f

/* Field drift in noise-coord units per second. */
#define FIELD_DRIFT         0.10f

/* Drift multiplier — cranked by +/-. */
#define DRIFT_MULT_MIN      1
#define DRIFT_MULT_DEF      1
#define DRIFT_MULT_MAX      32

/* fBm stack — 4 octaves, halving amplitude, doubling frequency. */
#define FBM_OCTAVES         4

/* Density thresholds for the ASCII glyph ramp. */
#define GLYPH_HIGH_THRESH   0.65f
#define GLYPH_MID_THRESH    0.30f

/*
 * Palette quantisation — continuous glow ∈ [0, 1] → discrete band
 * index ∈ {0..3}. Same scheme as the simplex / worley files.
 *
 *   N_PALETTE_BANDS    — # of tiers (matches Theme.band[] length).
 *   PALETTE_BAND_MASK  — cheap `& MASK` modulo (works because
 *                         N_PALETTE_BANDS is a power of two).
 *   GLOW_TO_BAND_GAIN  — glow * GAIN → int 0..3 via truncation.
 *                         Set to N_PALETTE_BANDS − ε so glow == 1.0
 *                         still floors to band 3 (not band 4).
 */
#define N_PALETTE_BANDS     4
#define PALETTE_BAND_MASK   3       /* N_PALETTE_BANDS - 1 */
#define GLOW_TO_BAND_GAIN   3.999f  /* almost-4 to keep glow=1.0 → band 3 */

/*
 * Lattice hash constants.
 *
 *   LATTICE_HASH_MUL_X / Y — large odd primes mixed with (xi, yi)
 *                            before hash32. Different multipliers per
 *                            axis ensure (0, 1) and (1, 0) hash to
 *                            uncorrelated values. Same constants used
 *                            by the simplex / worley files.
 *   HASH_TOP24_TO_UNIT     — converts the top 24 bits of a 32-bit
 *                            hash to a unit float ∈ [0, 1]. Top bits
 *                            are higher quality than bottom in most
 *                            mixers — divisor is 2²⁴ − 1 = 16777215.
 */
#define LATTICE_HASH_MUL_X  374761393u
#define LATTICE_HASH_MUL_Y  668265263u
#define HASH_TOP24_TO_UNIT  (1.0f / 16777215.0f)

/*
 * Rotation matrix constants. ROTATE_COS_45 ≈ 0.7071068 = √2/2 is
 * both sin(45°) and cos(45°) — used by the Tier-4 ROTATE pattern to
 * sample at coords rotated 45° from screen space.
 */
#define ROTATE_COS_45       0.7071068f

/*
 * Pattern — thirty value-noise variants, grouped into six complexity
 * tiers. Cycle with n/p. The enum order MUST match the
 * `noise_patterns[]` dispatch table in §6 (compiler enforces this
 * via the fixed-size [N_PATTERNS] array initialiser).
 *
 *   Tier 1 INTERPOLATION : SMOOTH, LINEAR, BLOCKY, QUINTIC, COSINE
 *   Tier 2 STACKS        : FBM_2, FBM, FBM_6, TURBULENCE, RIDGED
 *   Tier 3 MAPPED        : CONTOURS, THRESHOLD, WAVES, POW2, SQRT
 *   Tier 4 WARPED        : WARP, WISPS, ROTATE, SHIFTED, ZOOMED
 *   Tier 5 COMPOSITES    : MULT, ADD, DIFF, MARBLE, NEBULA
 *   Tier 6 EFFECTS       : PLASMA, STORM, LIGHTNING, STARS, AURORA
 */
typedef enum {
    /* Tier 1 — INTERPOLATION: how to blend the 4 corner scalars */
    PATTERN_SMOOTH = 0,
    PATTERN_LINEAR,
    PATTERN_BLOCKY,
    PATTERN_QUINTIC,
    PATTERN_COSINE,
    /* Tier 2 — STACKS: fBm and family */
    PATTERN_FBM_2,
    PATTERN_FBM,
    PATTERN_FBM_6,
    PATTERN_TURBULENCE,
    PATTERN_RIDGED,
    /* Tier 3 — MAPPED: post-transforms of a single fBm sample */
    PATTERN_CONTOURS,
    PATTERN_THRESHOLD,
    PATTERN_WAVES,
    PATTERN_POW2,
    PATTERN_SQRT,
    /* Tier 4 — WARPED: domain-space transforms */
    PATTERN_WARP,
    PATTERN_WISPS,
    PATTERN_ROTATE,
    PATTERN_SHIFTED,
    PATTERN_ZOOMED,
    /* Tier 5 — COMPOSITES: combine multiple value-noise samples */
    PATTERN_MULT,
    PATTERN_ADD,
    PATTERN_DIFF,
    PATTERN_MARBLE,
    PATTERN_NEBULA,
    /* Tier 6 — EFFECTS: heavier transforms / visual idioms */
    PATTERN_PLASMA,
    PATTERN_STORM,
    PATTERN_LIGHTNING,
    PATTERN_STARS,
    PATTERN_AURORA,
    N_PATTERNS,
} Pattern;

/* pattern_name() / pattern_tier() defined in §6 alongside dispatch table. */
static const char *pattern_name(Pattern p);
static const char *pattern_tier(Pattern p);

#define NS_PER_SEC  1000000000LL
#define NS_PER_MS      1000000LL
#define TICK_NS(f)  (NS_PER_SEC / (f))

/*
 * Frame-loop timing limits.
 *
 *   MAX_FRAME_DT_NS   — cap per-frame dt at 100 ms before feeding
 *                        the fixed-timestep accumulator. Without
 *                        this cap, a long stall (debugger, SIGSTOP,
 *                        swap-storm) would queue thousands of sim
 *                        ticks to fire when the process resumes —
 *                        the "spiral of death" failure mode (see
 *                        Glenn Fiedler, "Fix Your Timestep!").
 *   RENDER_FPS_TARGET — render-throttle target. The sleep before
 *                        I/O paces the render loop at this rate
 *                        even when sim_fps is set higher.
 */
#define MAX_FRAME_DT_NS    (100 * NS_PER_MS)
#define RENDER_FPS_TARGET  60

/*
 * Theme — a named 4-tier colour palette + accent for the value-noise
 * renderer.
 *
 * INTENT
 *   Decouple the "what colours" choice from the "how to render"
 *   pipeline. The same GlowField + GlyphRamp drives 10 different
 *   visual moods just by swapping which 4 colour pairs ncurses is
 *   bound to (see theme_apply() in §3).
 *
 * CONTEXT
 *   Indexed by PaletteState.current (§7); cycled via t / T. The
 *   four band entries map 1:1 onto GlowField.band quartile
 *   {0,1,2,3} — band 0 is the dimmest tier, band 3 the brightest.
 *   The renderer reads `themes[palette.current].band[idx]` once per
 *   theme change and rebuilds the ncurses colour pairs.
 *
 * MEMBER LOGIC
 *   name   : short uppercase label shown in HUD row 1. ≤7 chars so
 *            the "theme:%-8s" format string never overflows.
 *   band[] : xterm-256 colour-cube indices (see ANSI escape code
 *            § 8-bit). Per CLAUDE.md "Theme Palette Brightness",
 *            every entry MUST sit in the bright half of the cube
 *            (≥ 24 for the 6³ cube, ≥ 244 for the greyscale ramp).
 *            Bottom-of-palette colours go invisible against the
 *            default-black bg when rendered with A_DIM.
 *   flash  : 256-colour accent reserved for rare-event highlights.
 *            Vestigial in this file (no event flash) — kept so the
 *            theme table stays compatible with sibling demos that
 *            DO use the accent.
 *
 * Ref: ANSI escape code § 8-bit (link in References block).
 */
typedef struct {
    const char *name;        /* HUD label, ≤7 chars                         */
    short       band[4];     /* xterm-256 idx, one per GlowField.band tier  */
    short       flash;       /* xterm-256 accent (reserved, unused here)    */
} Theme;

#define N_THEMES 10

static const Theme themes[N_THEMES] = {
    /*           name      band0 band1 band2 band3 flash */
    { "DEFAULT", {  17,   33,  220,  231 }, 226 },
    { "MATRIX",  {  22,   34,   46,  118 }, 226 },
    { "NOVA",    {  53,  129,  201,  219 }, 226 },
    { "MONO",    { 234,  244,  250,  254 }, 226 },
    { "OCEAN",   {  17,   33,   39,   51 }, 226 },
    { "FIRE",    {  52,  124,  208,  226 }, 196 },
    { "EARTH",   {  58,  100,  173,  230 }, 226 },
    { "FOREST",  {  22,   28,   64,  144 }, 226 },
    { "DESERT",  {  94,  130,  173,  222 }, 226 },
    { "ARCTIC",  {  18,   39,  159,  231 }, 226 },
};

/* ===================================================================== */
/* §2  clock                                                              */
/* ===================================================================== */

static int64_t clock_ns(void)
{
    struct timespec t;
    clock_gettime(CLOCK_MONOTONIC, &t);
    return (int64_t)t.tv_sec * NS_PER_SEC + t.tv_nsec;
}

static void clock_sleep_ns(int64_t ns)
{
    if (ns <= 0) return;
    struct timespec req = {
        .tv_sec  = (time_t)(ns / NS_PER_SEC),
        .tv_nsec = (long)  (ns % NS_PER_SEC),
    };
    nanosleep(&req, NULL);
}

/* ===================================================================== */
/* §3  color                                                              */
/* ===================================================================== */

static void theme_apply(int idx)
{
    if (idx < 0 || idx >= N_THEMES) idx = 0;
    if (COLORS >= 256) {
        const Theme *t = &themes[idx];
        for (int i = 0; i < 4; i++)
            init_pair(PAIR_BAND_BASE + i, t->band[i], -1);
        init_pair(PAIR_FLASH, t->flash, -1);
    } else {
        static const short fallback[4] = {
            COLOR_BLUE, COLOR_CYAN, COLOR_MAGENTA, COLOR_YELLOW,
        };
        for (int i = 0; i < 4; i++)
            init_pair(PAIR_BAND_BASE + i, fallback[i], -1);
        init_pair(PAIR_FLASH, COLOR_YELLOW, -1);
    }
}

static void color_init(void)
{
    start_color();
    use_default_colors();
    if (COLORS >= 256) {
        init_pair(PAIR_HUD,   226, -1);
        init_pair(PAIR_HINT,   51, -1);
    } else {
        init_pair(PAIR_HUD,  COLOR_YELLOW, -1);
        init_pair(PAIR_HINT, COLOR_CYAN,   -1);
    }
    theme_apply(0);
}

/* ===================================================================== */
/* §5  noise — ValueNoise primitive + lattice scalars + fBm helpers       */
/* ===================================================================== */

/*
 * ValueNoise — the noise primitive's runtime state.
 *
 * INTENT
 *   Encapsulate the ONE piece of mutable state value noise needs —
 *   the per-run hash seed — so the algorithm can be passed as
 *   `const ValueNoise *` and its purity is type-checked. Everything
 *   else value noise needs (the integer hash mixer, the lattice
 *   index multipliers, the interpolation curves) is a compile-time
 *   mathematical fact.
 *
 * CONTEXT
 *   Lives on Scene (§7). Pattern functions in §6 receive a
 *   const-pointer so the dataflow at every call site reads "sample
 *   noise, don't mutate it". Reseeding only happens via
 *   value_noise_reseed() on user reset (r key).
 *
 *   Unlike simplex (which needs a 512-byte permutation table) or
 *   worley (which is also seed-only), value noise has the SIMPLEST
 *   possible state — a single 32-bit integer. That matches its role
 *   as the predecessor / pedagogical base case of gradient noise.
 *
 * MEMBER LOGIC
 *   seed : 32-bit per-run randomness. XOR'd into the per-corner hash
 *          mixer so different runs of the program produce different
 *          random-scalar fields at every lattice point. Rerolled
 *          from `rand() ^ (rand() << 16)` on every scene_reset.
 *
 * Ref: Williams 1983, Perlin 1985 — both describe per-lattice-point
 *      hashed scalars as the input to interpolation.
 */
typedef struct {
    uint32_t seed;
} ValueNoise;

/* Small 32-bit integer mixer. 4 mul + 4 shift. Decent visual quality
 * (passes basic chi-square; not crypto-grade). Same mixer used by
 * the simplex / worley files for consistency. */
static inline uint32_t hash32(uint32_t x)
{
    x = (x ^ (x >> 16)) * 0x7feb352du;
    x = (x ^ (x >> 15)) * 0x846ca68bu;
    x = (x ^ (x >> 16));
    return x;
}

/*
 * lattice_scalar — pseudo-random value ∈ [0, 1] at integer corner
 * (xi, yi). Deterministic per (xi, yi, vn->seed): the same coords
 * always return the same scalar within one run, but two adjacent
 * lattice points hash to uncorrelated scalars. This is the entire
 * "data" of value noise — every lookup is an on-demand hash; no
 * pre-built grid.
 */
static inline float lattice_scalar(const ValueNoise *vn, int xi, int yi)
{
    uint32_t h = (uint32_t)xi * LATTICE_HASH_MUL_X
               + (uint32_t)yi * LATTICE_HASH_MUL_Y
               + vn->seed;
    h = hash32(h);
    /* Use top 24 bits → unit float for ~7-decimal-digit precision. */
    return (float)(h >> 8) * HASH_TOP24_TO_UNIT;
}

/* value_noise_reseed — reroll vn->seed. Called at every reset (r) so
 * different runs / r-presses produce visibly different lattice fields. */
static void value_noise_reseed(ValueNoise *vn)
{
    vn->seed = (uint32_t)rand() ^ ((uint32_t)rand() << 16);
}

/* smoothstep — Hermite blend curve. s(0)=0, s(1)=1, derivative 0 at
 * both ends → no slope discontinuity at lattice points. */
static inline float smoothstep01(float t)
{
    return t * t * (3.0f - 2.0f * t);
}

/* quintic01 — Perlin's improved-noise interpolant:
 *   q(t) = 6t⁵ − 15t⁴ + 10t³
 * Has zero first AND second derivatives at the endpoints (vs
 * smoothstep, which only has zero first derivative). Eliminates
 * the second-derivative "ridge" visible along lattice edges with
 * smoothstep. Used by the QUINTIC pattern. */
static inline float quintic01(float t)
{
    return t * t * t * (t * (t * 6.0f - 15.0f) + 10.0f);
}

/* cosine01 — classic alternative interpolation:
 *   c(t) = (1 − cos(πt)) / 2
 * Equivalent to smoothstep visually but uses a transcendental, so
 * it's slower in tight loops. Historically common in early
 * procedural-noise code. */
static inline float cosine01(float t)
{
    return (1.0f - cosf(t * (float)M_PI)) * 0.5f;
}

/* Linear interpolation. */
static inline float lerpf(float a, float b, float t)
{
    return a + (b - a) * t;
}

/* ───── value_noise — types and helpers ─────────────────────────────── *
 *
 * The value-noise algorithm decomposes naturally into 5 named stages.
 * Each stage gets a dedicated helper below; value_noise itself is then
 * a pseudocode driver.
 *
 *   STAGE 1  LOCATE — floor(x, y) → integer lattice cell + the query's
 *                      fractional position within it.
 *                                                       → value_locate_cell
 *
 *   STAGE 2  BLOCKY SHORTCUT — if interp_mode is "no interp", pick the
 *                      nearest of the 4 corners and return. (Skips
 *                      stages 3-5.)
 *
 *   STAGE 3  SAMPLE  — look up the 4 corner scalars from the hash.
 *
 *   STAGE 4  CURVE   — pre-curve the fractional position through the
 *                      selected interpolator (smoothstep / quintic /
 *                      cosine / identity).
 *                                                       → apply_interp_curve
 *
 *   STAGE 5  BILERP  — bilinear blend of the 4 corners using the
 *                      curved fractions.                → bilerp_corners
 */

/*
 * CellQuery — what value_locate_cell returns: enough information for
 * stages 3-5 to find the four corner scalars and the blend factors.
 *
 *   cell_x, cell_y : integer lattice cell index (the cell's
 *                    bottom-left corner) — used as the base for the
 *                    four lattice_scalar lookups.
 *   frac_x, frac_y : the query's position within the cell, ∈ [0, 1).
 *                    Drives the bilerp weights after the interp
 *                    curve is applied.
 */
typedef struct {
    int   cell_x, cell_y;
    float frac_x, frac_y;
} CellQuery;

/* STAGE 1 — floor (x, y) to get the cell index; subtract to get the
 * query's local position within the cell. The two cells (cell_x,
 * cell_x+1) × (cell_y, cell_y+1) define the 2×2 block of lattice
 * corners that bilerp will blend. */
static inline CellQuery value_locate_cell(float x, float y)
{
    CellQuery q;
    q.cell_x = (int)floorf(x);
    q.cell_y = (int)floorf(y);
    q.frac_x = x - (float)q.cell_x;
    q.frac_y = y - (float)q.cell_y;
    return q;
}

/*
 * STAGE 4 — apply the selected interpolator's curve to one fractional
 * axis. The curve is what differentiates the LINEAR (no curve) and
 * SMOOTH / QUINTIC / COSINE variants. Bilerp uses the curved value
 * as the blend weight in stage 5.
 *
 *   mode 1 LINEAR   — identity (no curve; raw fractional position)
 *   mode 2 SMOOTH   — smoothstep(t) = t² (3 − 2t)
 *   mode 3 QUINTIC  — 6t⁵ − 15t⁴ + 10t³  (Perlin 2002)
 *   mode 4 COSINE   — (1 − cos(πt)) / 2
 *
 * Mode 0 BLOCKY doesn't reach this helper — it shortcuts at stage 2.
 */
static inline float apply_interp_curve(float t, int interp_mode)
{
    switch (interp_mode) {
    case 2:  return smoothstep01(t);
    case 3:  return quintic01(t);
    case 4:  return cosine01(t);
    default: return t;                  /* LINEAR — no curve */
    }
}

/*
 * STAGE 5 — bilinear interpolation of the 4 corner scalars. The
 * blend factors (bx, by) come from stage 4 (already curved).
 *
 *   top = lerp(BL, BR, bx)   — interpolate along bottom edge
 *   bot = lerp(TL, TR, bx)   — interpolate along top edge
 *   out = lerp(top, bot, by) — interpolate between the two edges
 *
 * Subscripts use lattice coords: corner_xy is the value at the
 * (xi + x, yi + y) corner of the cell where x, y ∈ {0, 1}.
 */
static inline float bilerp_corners(float corner_00, float corner_10,
                                   float corner_01, float corner_11,
                                   float bx, float by)
{
    float bottom_edge = lerpf(corner_00, corner_10, bx);
    float top_edge    = lerpf(corner_01, corner_11, bx);
    return lerpf(bottom_edge, top_edge, by);
}

/*
 * value_noise — the algorithm proper. `interp_mode` selects which
 * interpolation rule:
 *   0 = BLOCKY   (nearest-neighbor — no interp)
 *   1 = LINEAR   (bilerp, no smoothstep)
 *   2 = SMOOTH   (smoothstep + bilerp)
 *   3 = QUINTIC  (Perlin's 5th-order curve + bilerp)
 *   4 = COSINE   (cosine curve + bilerp)
 *
 * Pseudocode shape:
 *
 *   q       = LOCATE(x, y)                      // STAGE 1
 *   if BLOCKY: return nearest corner            // STAGE 2
 *   corners = SAMPLE 4 lattice scalars          // STAGE 3
 *   bx, by  = CURVE(q.frac_x, q.frac_y, mode)   // STAGE 4
 *   return    BILERP(corners, bx, by)           // STAGE 5
 *
 * Returns value ∈ [0, 1]. Pure function of (vn, x, y, mode).
 */
static float value_noise(const ValueNoise *vn,
                         float x, float y, int interp_mode)
{
    /* STAGE 1 — LOCATE cell + query's fractional position within it. */
    CellQuery q = value_locate_cell(x, y);

    /* STAGE 2 — BLOCKY shortcut: no interpolation, return the scalar
     * at whichever corner the query is closest to. Skips stages 3-5. */
    if (interp_mode == 0) {
        int corner_x = (q.frac_x < 0.5f) ? q.cell_x : q.cell_x + 1;
        int corner_y = (q.frac_y < 0.5f) ? q.cell_y : q.cell_y + 1;
        return lattice_scalar(vn, corner_x, corner_y);
    }

    /* STAGE 3 — SAMPLE the four corner scalars of the cell. */
    float corner_00 = lattice_scalar(vn, q.cell_x,     q.cell_y);
    float corner_10 = lattice_scalar(vn, q.cell_x + 1, q.cell_y);
    float corner_01 = lattice_scalar(vn, q.cell_x,     q.cell_y + 1);
    float corner_11 = lattice_scalar(vn, q.cell_x + 1, q.cell_y + 1);

    /* STAGE 4 — CURVE the fractional position through the interpolator
     * to get the bilerp blend weights. */
    float blend_x = apply_interp_curve(q.frac_x, interp_mode);
    float blend_y = apply_interp_curve(q.frac_y, interp_mode);

    /* STAGE 5 — BILERP the 4 corners with the curved blend weights. */
    return bilerp_corners(corner_00, corner_10,
                          corner_01, corner_11,
                          blend_x, blend_y);
}

/*
 * value_fbm_n — fBm of value noise with caller-chosen octave count.
 * Halving amplitude, doubling frequency per octave. Output normalised
 * by amplitude sum so it stays in [0, 1]. Always uses SMOOTH interp
 * under the hood (mode 2) — fBm always wants the cleanest base noise.
 */
static float value_fbm_n(const ValueNoise *vn,
                         float x, float y, int n_octaves)
{
    float total   = 0.0f;
    float amp     = 1.0f;
    float freq    = 1.0f;
    float max_amp = 0.0f;
    for (int o = 0; o < n_octaves; o++) {
        /* value_noise returns [0, 1]; remap to [-1, 1] before summing
         * so the fBm sum is also signed (centred on 0). */
        float v = value_noise(vn, x * freq, y * freq, 2) * 2.0f - 1.0f;
        total   += amp * v;
        max_amp += amp;
        amp     *= 0.5f;
        freq    *= 2.0f;
    }
    /* Re-map signed sum back into [0, 1] for the renderer. */
    return total / max_amp * 0.5f + 0.5f;
}

/* fBm with the default FBM_OCTAVES count. Convenience wrapper. */
static float value_fbm(const ValueNoise *vn, float x, float y)
{
    return value_fbm_n(vn, x, y, FBM_OCTAVES);
}

/* fBm of |value| — turbulence. Always ≥ 0; gives sharp-edged textures. */
static float value_fbm_abs(const ValueNoise *vn, float x, float y)
{
    float total   = 0.0f;
    float amp     = 1.0f;
    float freq    = 1.0f;
    float max_amp = 0.0f;
    for (int o = 0; o < FBM_OCTAVES; o++) {
        float v = value_noise(vn, x * freq, y * freq, 2) * 2.0f - 1.0f;
        total   += amp * fabsf(v);
        max_amp += amp;
        amp     *= 0.5f;
        freq    *= 2.0f;
    }
    return total / max_amp;
}

/* ===================================================================== */
/* §6  patterns — 30 derived visualisations + dispatch table              */
/* ===================================================================== */

/*
 * Signature: all pattern functions take (vn, x, y, t) and return a
 * single glow ∈ [0, 1]. Band is derived from the glow quartile by
 * the caller — no &band out-param like in worley, since value noise
 * has no analog of cell_id.
 *   vn  = const ValueNoise* — the seed-holding primitive. Threaded
 *         through so the dataflow at every call site reads "sample
 *         noise, don't mutate it".
 *   x,y = noise-space coords (cell × NOISE_SCALE).
 *   t   = pattern.field_time, the drift accumulator.
 */

static inline float clampf(float v, float lo, float hi)
{
    return v < lo ? lo : v > hi ? hi : v;
}

/* glow ∈ [0, 1] → palette band ∈ {0, 1, 2, 3}.
 * The GLOW_TO_BAND_GAIN is "almost 4" so glow=1.0 still floors to
 * band 3 instead of overflowing past it. See §1. */
static inline int band_from_glow(float g)
{
    return (int)(g * GLOW_TO_BAND_GAIN) & PALETTE_BAND_MASK;
}

/* ---------- Tier 1 — INTERPOLATION: how to blend the 4 corners -------- */

/* SMOOTH — smoothstep + bilerp. The canonical value-noise look. */
static float pattern_smooth(const ValueNoise *vn, float x, float y, float t)
{
    return clampf(value_noise(vn, x, y + t, 2), 0.0f, 1.0f);
}

/* LINEAR — raw bilerp; pyramid tents around each lattice point. */
static float pattern_linear(const ValueNoise *vn, float x, float y, float t)
{
    return clampf(value_noise(vn, x, y + t, 1), 0.0f, 1.0f);
}

/* BLOCKY — nearest-neighbor; visible lattice tiles. */
static float pattern_blocky(const ValueNoise *vn, float x, float y, float t)
{
    return clampf(value_noise(vn, x, y + t, 0), 0.0f, 1.0f);
}

/* QUINTIC — Perlin's 5th-order interpolator. Smoother than smoothstep
 * (zero first AND second derivative at endpoints). */
static float pattern_quintic(const ValueNoise *vn, float x, float y, float t)
{
    return clampf(value_noise(vn, x, y + t, 3), 0.0f, 1.0f);
}

/* COSINE — classic cosine interpolation. Visually close to smoothstep. */
static float pattern_cosine(const ValueNoise *vn, float x, float y, float t)
{
    return clampf(value_noise(vn, x, y + t, 4), 0.0f, 1.0f);
}

/* ---------- Tier 2 — STACKS: fBm and family --------------------------- */

/* FBM_2 — 2-octave fBm. Big rolling blobs with a single fine detail layer. */
static float pattern_fbm_2(const ValueNoise *vn, float x, float y, float t)
{
    return clampf(value_fbm_n(vn, x, y + t, 2), 0.0f, 1.0f);
}

/* FBM — default 4-octave fBm. The "natural cloud" look. */
static float pattern_fbm(const ValueNoise *vn, float x, float y, float t)
{
    return clampf(value_fbm(vn, x, y + t), 0.0f, 1.0f);
}

/* FBM_6 — 6-octave fBm. More detail; some octaves alias at high freq. */
static float pattern_fbm_6(const ValueNoise *vn, float x, float y, float t)
{
    return clampf(value_fbm_n(vn, x, y + t, 6), 0.0f, 1.0f);
}

/* TURBULENCE — Σ|value|. Always ≥ 0; sharp-edged storm clouds. */
static float pattern_turbulence(const ValueNoise *vn, float x, float y, float t)
{
    return clampf(value_fbm_abs(vn, x, y + t), 0.0f, 1.0f);
}

/* RIDGED — 1 − |fbm centred at 0|. Bright ridges where fbm crosses
 * zero; sharp wispy cirrus look. */
static float pattern_ridged(const ValueNoise *vn, float x, float y, float t)
{
    /* value_fbm returns [0, 1]; re-centre to [-1, 1] for the |·|. */
    float v = (value_fbm(vn, x, y + t) - 0.5f) * 2.0f;
    return clampf(1.0f - fabsf(v), 0.0f, 1.0f);
}

/* ---------- Tier 3 — MAPPED: pure post-transforms of one fbm ---------- */

/* CONTOURS — fractional part of fbm · 8. Sawtooth bands following the
 * underlying smooth field — topographic look. */
static float pattern_contours(const ValueNoise *vn, float x, float y, float t)
{
    float v = value_fbm(vn, x, y + t) * 8.0f;
    return v - floorf(v);
}

/* THRESHOLD — smoothstep around 0.5 of fbm. Binary cloud cover with
 * anti-aliased edges. */
static float pattern_threshold(const ValueNoise *vn, float x, float y, float t)
{
    float v = value_fbm(vn, x, y + t);
    if (v < 0.45f) return 0.0f;
    if (v > 0.55f) return 1.0f;
    float s = (v - 0.45f) * 10.0f;
    return s * s * (3.0f - 2.0f * s);
}

/* WAVES — sin(fbm · 12). Many concentric sin bands; reads like
 * raindrops on a still pond. */
static float pattern_waves(const ValueNoise *vn, float x, float y, float t)
{
    return sinf(value_fbm(vn, x, y + t) * 12.0f) * 0.5f + 0.5f;
}

/* POW2 — fbm². Accentuates high values, suppresses low ones. */
static float pattern_pow2(const ValueNoise *vn, float x, float y, float t)
{
    float v = value_fbm(vn, x, y + t);
    return v * v;
}

/* SQRT — √fbm. Compresses high values, lifts low ones — low-contrast haze. */
static float pattern_sqrt(const ValueNoise *vn, float x, float y, float t)
{
    return sqrtf(clampf(value_fbm(vn, x, y + t), 0.0f, 1.0f));
}

/* ---------- Tier 4 — WARPED: domain-space transforms ------------------ */

/* WARP — IQ-style domain warp: sample fbm at coords themselves
 * perturbed by another fbm. "Currents-pushing-clouds" look. */
static float pattern_warp(const ValueNoise *vn, float x, float y, float t)
{
    float wx = (value_fbm(vn, x,        y + t)        - 0.5f) * 2.0f;
    float wy = (value_fbm(vn, x + 5.2f, y + 1.3f + t) - 0.5f) * 2.0f;
    return clampf(value_fbm(vn, x + wx, y + wy + t), 0.0f, 1.0f);
}

/* WISPS — anisotropic stretch. Sample at smaller x-scale → horizontal
 * streaks instead of round puffs. */
static float pattern_wisps(const ValueNoise *vn, float x, float y, float t)
{
    return clampf(value_fbm(vn, x * 0.4f, y + t * 1.5f), 0.0f, 1.0f);
}

/* ROTATE — sample at coords rotated 45°. Lattice artefacts (a value-
 * noise weakness) now run diagonally instead of axis-aligned. */
static float pattern_rotate(const ValueNoise *vn, float x, float y, float t)
{
    const float ca = ROTATE_COS_45;
    const float sa = ROTATE_COS_45;         /* sin(45°) == cos(45°) */
    float rx = x * ca - y * sa;
    float ry = x * sa + y * ca;
    return clampf(value_fbm(vn, rx, ry + t), 0.0f, 1.0f);
}

/* SHIFTED — average of 4 fbm samples at half-cell offsets. Smoother
 * than plain fbm; acts as a 2×2 box filter on top of fBm. */
static float pattern_shifted(const ValueNoise *vn, float x, float y, float t)
{
    float a = value_fbm(vn, x,        y + t);
    float b = value_fbm(vn, x + 0.5f, y + t);
    float c = value_fbm(vn, x,        y + 0.5f + t);
    float d = value_fbm(vn, x + 0.5f, y + 0.5f + t);
    return clampf(0.25f * (a + b + c + d), 0.0f, 1.0f);
}

/* ZOOMED — blend fbm at 1× scale with fbm at 3× scale. Coarse blobs
 * with finer detail painted on top. */
static float pattern_zoomed(const ValueNoise *vn, float x, float y, float t)
{
    float lo = value_fbm(vn, x,        y + t);
    float hi = value_fbm(vn, x * 3.0f, y * 3.0f + t);
    return clampf(0.6f * lo + 0.4f * hi, 0.0f, 1.0f);
}

/* ---------- Tier 5 — COMPOSITES: multiple value-noise samples --------- */

/* MULT — fbm × fbm-at-2×. Bright cores where both fields are high. */
static float pattern_mult(const ValueNoise *vn, float x, float y, float t)
{
    float a = value_fbm(vn, x, y + t);
    float b = value_fbm(vn, x * 2.0f + 5.0f, y * 2.0f + 3.0f + t);
    return clampf(a * b * 2.0f, 0.0f, 1.0f);
}

/* ADD — fbm + fbm-at-3×. Additive composition (high-low blend). */
static float pattern_add(const ValueNoise *vn, float x, float y, float t)
{
    float a = value_fbm(vn, x,        y + t);
    float b = value_fbm(vn, x * 3.0f, y * 3.0f + t);
    return clampf((a + b) * 0.5f, 0.0f, 1.0f);
}

/* DIFF — |fbm − fbm-shifted|. Highlights gradient — edges of the field. */
static float pattern_diff(const ValueNoise *vn, float x, float y, float t)
{
    float a = value_fbm(vn, x,        y + t);
    float b = value_fbm(vn, x + 0.5f, y + 0.5f + t);
    return clampf(fabsf(a - b) * 4.0f, 0.0f, 1.0f);
}

/* MARBLE — sin(x·k + fbm·K). Pure sin gives perfect stripes; the fbm
 * term wobbles the stripe phase so they bend like marble veining. */
static float pattern_marble(const ValueNoise *vn, float x, float y, float t)
{
    float v = value_fbm(vn, x, y + t);
    return sinf(x * 3.0f + v * 6.0f) * 0.5f + 0.5f;
}

/* NEBULA — fbm × turbulence. Sparse bright cores against a darker
 * gaseous background. */
static float pattern_nebula(const ValueNoise *vn, float x, float y, float t)
{
    float a = value_fbm(vn, x, y + t);
    float b = value_fbm_abs(vn, x * 1.5f + 7.0f, y * 1.5f + 3.0f + t);
    return clampf(a * b * 1.8f, 0.0f, 1.0f);
}

/* ---------- Tier 6 — EFFECTS: heavier transforms / visual idioms ------ */

/* PLASMA — classic demoscene plasma: sum of three sinusoids whose
 * arguments are perturbed by shared fbm. */
static float pattern_plasma(const ValueNoise *vn, float x, float y, float t)
{
    float v = value_fbm(vn, x, y + t);
    float s = sinf(x * 2.0f + v * 3.0f)
            + cosf(y * 2.5f + v * 3.0f)
            + sinf((x + y) * 1.5f + v * 2.0f);
    return (s + 3.0f) / 6.0f;
}

/* STORM — turbulence², gain 1.5. */
static float pattern_storm(const ValueNoise *vn, float x, float y, float t)
{
    float v = value_fbm_abs(vn, x, y + t);
    return clampf(v * v * 1.5f, 0.0f, 1.0f);
}

/* LIGHTNING — (1 − |fbm|)¹². Razor-sharp ridges read as bolts. */
static float pattern_lightning(const ValueNoise *vn, float x, float y, float t)
{
    float v = (value_fbm(vn, x, y + t) - 0.5f) * 2.0f;   /* [-1, 1] */
    float r = 1.0f - fabsf(v);                            /* ridge   */
    float p = r * r;                                      /* ^2      */
    p     *= p;                                           /* ^4      */
    p     *= p;                                           /* ^8      */
    p     *= r * r * r * r;                               /* ^12     */
    return clampf(p * 1.8f, 0.0f, 1.0f);
}

/* STARS — sparse bright pinpoints from a high-frequency lattice
 * overlaid on a dim smooth background. */
static float pattern_stars(const ValueNoise *vn, float x, float y, float t)
{
    float bg    = value_noise(vn, x, y + t * 0.3f, 2) * 0.3f;
    float stars = value_noise(vn, x * 6.0f + 13.0f, y * 6.0f + 7.0f + t * 0.5f, 2);
    if (stars > 0.7f) bg += (stars - 0.7f) * 3.0f;
    return clampf(bg, 0.0f, 1.0f);
}

/* AURORA — horizontal bands modulated by fbm phase, fading vertically. */
static float pattern_aurora(const ValueNoise *vn, float x, float y, float t)
{
    float band = sinf(x * 1.5f + value_fbm(vn, x, y + t) * 4.0f) * 0.5f + 0.5f;
    float vert = sinf(y * 0.4f + 1.0f);
    if (vert < 0.0f) vert = 0.0f;
    return clampf(band * vert * 1.2f, 0.0f, 1.0f);
}

/* ---------- Dispatch table -------------------------------------------- */

/*
 * ValuePatternFn — function-pointer signature shared by all 30 pattern
 * samplers. Spelt out here so the dispatch table is type-safe and so
 * a reader can grep ONE place to see what every pattern function MUST
 * accept.
 *
 *   vn   — read-only noise context (seed). Threaded through so
 *          patterns can't silently mutate the primitive.
 *   x, y — noise-space coords (cell × NOISE_SCALE).
 *   t    — PatternState.field_time, the drift accumulator.
 *
 *   return — glow ∈ [0, 1]. Clamped by the caller too, but each
 *            pattern keeps it well-behaved.
 */
typedef float (*ValuePatternFn)(const ValueNoise *vn,
                                float x, float y, float t);

/*
 * NoisePattern — one row of the dispatch table: (display-name,
 * tier-label, sampler function pointer).
 *
 * INTENT
 *   Replace what would otherwise be a 30-case switch with a table
 *   lookup keyed by the Pattern enum. Adding a new pattern is then
 *   THREE coordinated edits (enum value, table row, function body)
 *   and the compiler enforces alignment via the fixed-size
 *   [N_PATTERNS] initialiser — a missing or mis-ordered row is a
 *   compile error.
 *
 * CONTEXT
 *   The whole `noise_patterns[]` array (below this typedef) is the
 *   source of truth for pattern → (name, tier, fn) lookup. The
 *   Pattern enum in §1 provides readable indices; pattern_name() and
 *   pattern_tier() in this section are the only outside accessors.
 *   scene_evaluate_field in §7 fetches `noise_patterns[active].sample`
 *   once per tick.
 *
 * MEMBER LOGIC
 *   name   : Display name, FIXED 10-char left-padded. The constant
 *            width is deliberate — HUD column alignment must stay
 *            stable as the user cycles patterns with n/p (otherwise
 *            the HUD jitters as each name changes length).
 *   tier   : 7-char "N-LABEL " form (e.g. "1-INTRP", "2-STACK",
 *            "6-FX   "). Encodes both the complexity tier (1-6) and
 *            the technique class (INTERPOLATION / STACKS / MAPPED /
 *            WARPED / COMPOSITES / EFFECTS). Same fixed-width
 *            rationale as `name`.
 *   sample : Function pointer to one of the 30 pattern_* functions.
 *            Indirection cost is one indirect call per cell, dwarfed
 *            by the cost of the noise samples inside the function
 *            itself (one value_fbm call = FBM_OCTAVES (4) value_noise
 *            calls; Tier-4 WARP is the worst case at 3 fbm calls).
 */
typedef struct {
    const char     *name;      /* HUD-padded display name, 10 chars */
    const char     *tier;      /* HUD-padded tier label, 7 chars    */
    ValuePatternFn  sample;    /* the pattern's per-cell sampler    */
} NoisePattern;

static const NoisePattern noise_patterns[N_PATTERNS] = {
    /* Tier 1 — INTERPOLATION */
    [PATTERN_SMOOTH]     = { "SMOOTH    ", "1-INTRP", pattern_smooth     },
    [PATTERN_LINEAR]     = { "LINEAR    ", "1-INTRP", pattern_linear     },
    [PATTERN_BLOCKY]     = { "BLOCKY    ", "1-INTRP", pattern_blocky     },
    [PATTERN_QUINTIC]    = { "QUINTIC   ", "1-INTRP", pattern_quintic    },
    [PATTERN_COSINE]     = { "COSINE    ", "1-INTRP", pattern_cosine     },
    /* Tier 2 — STACKS */
    [PATTERN_FBM_2]      = { "FBM_2     ", "2-STACK", pattern_fbm_2      },
    [PATTERN_FBM]        = { "FBM       ", "2-STACK", pattern_fbm        },
    [PATTERN_FBM_6]      = { "FBM_6     ", "2-STACK", pattern_fbm_6      },
    [PATTERN_TURBULENCE] = { "TURBULENCE", "2-STACK", pattern_turbulence },
    [PATTERN_RIDGED]     = { "RIDGED    ", "2-STACK", pattern_ridged     },
    /* Tier 3 — MAPPED */
    [PATTERN_CONTOURS]   = { "CONTOURS  ", "3-MAP  ", pattern_contours   },
    [PATTERN_THRESHOLD]  = { "THRESHOLD ", "3-MAP  ", pattern_threshold  },
    [PATTERN_WAVES]      = { "WAVES     ", "3-MAP  ", pattern_waves      },
    [PATTERN_POW2]       = { "POW2      ", "3-MAP  ", pattern_pow2       },
    [PATTERN_SQRT]       = { "SQRT      ", "3-MAP  ", pattern_sqrt       },
    /* Tier 4 — WARPED */
    [PATTERN_WARP]       = { "WARP      ", "4-WARP ", pattern_warp       },
    [PATTERN_WISPS]      = { "WISPS     ", "4-WARP ", pattern_wisps      },
    [PATTERN_ROTATE]     = { "ROTATE    ", "4-WARP ", pattern_rotate     },
    [PATTERN_SHIFTED]    = { "SHIFTED   ", "4-WARP ", pattern_shifted    },
    [PATTERN_ZOOMED]     = { "ZOOMED    ", "4-WARP ", pattern_zoomed     },
    /* Tier 5 — COMPOSITES */
    [PATTERN_MULT]       = { "MULT      ", "5-COMP ", pattern_mult       },
    [PATTERN_ADD]        = { "ADD       ", "5-COMP ", pattern_add        },
    [PATTERN_DIFF]       = { "DIFF      ", "5-COMP ", pattern_diff       },
    [PATTERN_MARBLE]     = { "MARBLE    ", "5-COMP ", pattern_marble     },
    [PATTERN_NEBULA]     = { "NEBULA    ", "5-COMP ", pattern_nebula     },
    /* Tier 6 — EFFECTS */
    [PATTERN_PLASMA]     = { "PLASMA    ", "6-FX   ", pattern_plasma     },
    [PATTERN_STORM]      = { "STORM     ", "6-FX   ", pattern_storm      },
    [PATTERN_LIGHTNING]  = { "LIGHTNING ", "6-FX   ", pattern_lightning  },
    [PATTERN_STARS]      = { "STARS     ", "6-FX   ", pattern_stars      },
    [PATTERN_AURORA]     = { "AURORA    ", "6-FX   ", pattern_aurora     },
};

static const char *pattern_name(Pattern p)
{
    if ((unsigned)p >= (unsigned)N_PATTERNS) return "?         ";
    return noise_patterns[p].name;
}

static const char *pattern_tier(Pattern p)
{
    if ((unsigned)p >= (unsigned)N_PATTERNS) return "?      ";
    return noise_patterns[p].tier;
}

/* ===================================================================== */
/* §7  scene                                                              */
/* ===================================================================== */

/*
 * GlowField — the per-cell output grid that the pipeline writes into
 * and the renderer reads from.
 *
 * INTENT
 *   Decouple "compute the value-noise field" (scene_evaluate_field,
 *   runs once per sim tick) from "paint the value-noise field"
 *   (scene_draw, runs once per render frame). The GlowField is the
 *   snapshot the renderer reads in between ticks.
 *
 * CONTEXT
 *   Lives on Scene. Written by scene_evaluate_field — one pattern-
 *   sampler call per cell, results written here. Read by scene_draw
 *   — uses glow + band via the GlyphRamp to pick a glyph + colour
 *   pair. Index with glow_field_idx(gf, x, y) = y · w + x (row-major).
 *
 * MEMORY
 *   No allocation post-init. Both buffers are sized at CELLS_MAX in
 *   BSS storage so the hot path never touches malloc/free.
 *
 * MEMBER LOGIC
 *   w, h    : Grid dimensions in cells. Set by app_pick_map_size at
 *             init and on every resize. Bounded by
 *             [16..MAP_W_MAX] × [8..MAP_H_MAX].
 *   count   : w · h, cached for the buffer-clearing loop.
 *   glow[]  : Per-cell scalar ∈ [0, 1]. Pattern sampler writes here.
 *   band[]  : Per-cell palette band ∈ {0, 1, 2, 3} — derived from
 *             glow quartile by scene_evaluate_field.
 */
typedef struct {
    int      w, h;                   /* grid dims (cells), set at reset */
    int      count;                  /* w * h, cached for tight loops   */
    float    glow[CELLS_MAX];        /* per-cell scalar ∈ [0, 1]        */
    uint8_t  band[CELLS_MAX];        /* per-cell palette tier ∈ {0..3}  */
} GlowField;

static inline int glow_field_idx(const GlowField *gf, int x, int y)
{
    return y * gf->w + x;
}

static void glow_field_reset(GlowField *gf, int w, int h)
{
    gf->w     = w;
    gf->h     = h;
    gf->count = w * h;
    for (int i = 0; i < gf->count; i++) {
        gf->glow[i] = 0.0f;
        gf->band[i] = 0;
    }
}

/*
 * GlyphRamp — the density → (glyph, attr) mapping.
 *
 * INTENT
 *   Capture "how density becomes a character" as a NAMED RULE
 *   rather than an inline if/else in the renderer. Three benefits:
 *   (1) thresholds visible as data; (2) future themes could swap
 *   ramps; (3) `glyph_ramp_pick(...)` scans cleaner than `if (glow
 *   > X)`.
 *
 * THE RAMP
 *      glow > thresh_high  →  glyph_high  bold     (dense core)
 *      glow > thresh_mid   →  glyph_mid   bold     (mid density)
 *      glow > thresh_low   →  glyph_low   normal   (faint trace)
 *      else                →  not drawn            (transparent)
 *
 * Defaults: 0.65 / 0.30 / 0.05 with '#', '*', '.'.
 *
 * GLYPH CHOICE
 *   '#', '*', '.' is a coarse 3-tier subset of Paul Bourke's
 *   canonical 10-char luminance ramp "@%#*+=-:. ".
 *
 * Ref: Bourke, "Character representation of grey scale images".
 */
typedef struct {
    float thresh_high;   /* > this → glyph_high  (default 0.65) */
    float thresh_mid;    /* > this → glyph_mid   (default 0.30) */
    float thresh_low;    /* > this → glyph_low   (default 0.05) */
    char  glyph_high;    /* dense core   glyph                  */
    char  glyph_mid;     /* mid-density  glyph                  */
    char  glyph_low;     /* faint-trace  glyph                  */
} GlyphRamp;

/*
 * GlyphChoice — return value from glyph_ramp_pick(). Small POD so
 * the call site reads as a pure function:
 *
 *   GlyphChoice gc = glyph_ramp_pick(ramp, glow);
 *   if (gc.visible) draw_cell(gc.glyph, palette[band], gc.attr);
 */
typedef struct {
    char glyph;         /* the char to draw — only valid if visible   */
    int  attr;          /* ncurses attribute: A_BOLD or A_NORMAL      */
    bool visible;       /* false → leave the cell empty (transparent) */
} GlyphChoice;

static void glyph_ramp_init(GlyphRamp *gr)
{
    gr->thresh_high = GLYPH_HIGH_THRESH;
    gr->thresh_mid  = GLYPH_MID_THRESH;
    gr->thresh_low  = GLOW_THRESHOLD;
    gr->glyph_high  = '#';
    gr->glyph_mid   = '*';
    gr->glyph_low   = '.';
}

static GlyphChoice glyph_ramp_pick(const GlyphRamp *gr, float glow)
{
    GlyphChoice c = { .glyph = ' ', .attr = A_NORMAL, .visible = false };
    if      (glow > gr->thresh_high) { c.glyph = gr->glyph_high; c.attr = A_BOLD;   c.visible = true; }
    else if (glow > gr->thresh_mid)  { c.glyph = gr->glyph_mid;  c.attr = A_BOLD;   c.visible = true; }
    else if (glow > gr->thresh_low)  { c.glyph = gr->glyph_low;  c.attr = A_NORMAL; c.visible = true; }
    return c;
}

/*
 * PatternState — the active pattern + how it animates over time.
 *
 * INTENT
 *   Group the three values that together describe "the current
 *   animation": which pattern, where in its drift cycle, at what
 *   speed. They change together so giving them a struct gives the
 *   animation a name.
 *
 * MEMBER LOGIC
 *   current    : Active pattern enum, indexes noise_patterns[].
 *                Defaults to PATTERN_SMOOTH (the canonical baseline).
 *                Cycled by n/p with wraparound through N_PATTERNS.
 *   field_time : Drift accumulator in noise-space units. Added to
 *                the y-coordinate of every noise sample so the field
 *                appears to scroll vertically. Monotonically
 *                increasing; reset only by r (scene_reset).
 *   drift_mult : User-controlled drift-rate multiplier. Power of 2
 *                in [DRIFT_MULT_MIN, DRIFT_MULT_MAX] = [1, 32].
 */
typedef struct {
    Pattern current;          /* active pattern enum                   */
    float   field_time;       /* drift accumulator (noise-space units) */
    int     drift_mult;       /* powers of 2 ∈ [MIN, MAX]              */
} PatternState;

static void pattern_state_init(PatternState *ps)
{
    ps->current    = PATTERN_SMOOTH;
    ps->field_time = 0.0f;
    ps->drift_mult = DRIFT_MULT_DEF;
}

/*
 * PaletteState — the active theme index.
 *
 * INTENT
 *   Currently a one-int wrapper, but kept as a named struct so the
 *   responsibility "which colour scheme is showing" has a stable
 *   home. Future themed-glyph or theme-crossfade support would
 *   extend this struct without disturbing Scene.
 *
 * MEMBER LOGIC
 *   current : Index into themes[] in §1. Always in [0, N_THEMES);
 *             wraparound handled in the key handler via mod.
 */
typedef struct {
    int current;              /* index into themes[] ∈ [0, N_THEMES) */
} PaletteState;

static void palette_state_init(PaletteState *p)
{
    p->current = 0;
}

/*
 * Scene — composite owner of ALL mutable simulation state.
 *
 * THE PIPELINE (top to bottom = dataflow order)
 *
 *   noise    — the ValueNoise seed                  (the ALGORITHM)
 *               ↓ (sampled by pattern functions)
 *   pattern  — active pattern + drift state         (the ANIMATION)
 *               ↓ (drives scene_evaluate_field)
 *   field    — per-cell glow + band buffers         (the DATA)
 *               ↓ (read by scene_draw)
 *   ramp     — density → glyph mapping              (the RENDER RULE)
 *               + palette colour pairs (via ncurses)
 *               ↓
 *   palette  — active theme index                   (the COLOUR CHOICE)
 *               + paused flag                       (the CONTROL)
 *
 *   Reads in dataflow order: noise → field (via pattern) →
 *   ramp + palette (via renderer).
 */
typedef struct {
    ValueNoise    noise;     /* §5 — seed-holding primitive (mutable)       */
    GlowField     field;     /* per-cell output grid (largest member)       */
    GlyphRamp     ramp;      /* density → glyph rule (read-mostly)          */
    PatternState  pattern;   /* active pattern + drift accumulator + speed  */
    PaletteState  palette;   /* active theme index                          */
    bool          paused;    /* if true, scene_tick early-returns           */
} Scene;

/* ---------- Per-cell mapping helper used by scene_evaluate_field ----- */

/* cell index → noise-space coordinate (cells × NOISE_SCALE). Used as
 * the (x, y) argument to every pattern sampler. */
static inline float cell_to_noise_coord(int cell)
{
    return (float)cell * NOISE_SCALE;
}

/*
 * scene_evaluate_field — drive the whole pipeline for one sim tick.
 *
 *   FOR every cell (x, y):
 *     fx, fy = noise-space coords          // cell_to_noise_coord
 *     glow   = active_pattern(noise, fx, fy, drift)
 *     write (glow, glow→band) → GlowField[x, y]
 */
static void scene_evaluate_field(Scene *s)
{
    /* STEP 1 — RESOLVE the active pattern's sampler. */
    Pattern active = s->pattern.current;
    if ((unsigned)active >= (unsigned)N_PATTERNS) return;
    ValuePatternFn      sample_pattern = noise_patterns[active].sample;
    const ValueNoise   *noise          = &s->noise;
    GlowField          *field          = &s->field;
    float               drift          = s->pattern.field_time;

    /* STEP 2 — SAMPLE PER CELL: pattern → glow → band, write field. */
    for (int y = 0; y < field->h; y++) {
        float fy = cell_to_noise_coord(y);
        for (int x = 0; x < field->w; x++) {
            float fx   = cell_to_noise_coord(x);
            float glow = clampf(sample_pattern(noise, fx, fy, drift),
                                0.0f, 1.0f);

            int idx          = glow_field_idx(field, x, y);
            field->glow[idx] = glow;
            field->band[idx] = (uint8_t)band_from_glow(glow);
        }
    }
}

static void scene_reset(Scene *s, int mw, int mh)
{
    glow_field_reset(&s->field, mw, mh);
    s->pattern.field_time = 0.0f;
    value_noise_reseed(&s->noise);
}

static void scene_init(Scene *s, int mw, int mh)
{
    memset(s, 0, sizeof *s);
    glyph_ramp_init   (&s->ramp);
    pattern_state_init(&s->pattern);
    palette_state_init(&s->palette);
    s->paused = false;
    scene_reset(s, mw, mh);
}

static void scene_tick(Scene *s, float dt)
{
    if (s->paused) return;
    s->pattern.field_time += FIELD_DRIFT * (float)s->pattern.drift_mult * dt;
    scene_evaluate_field(s);
}

/* ===================================================================== */
/* §8  screen                                                             */
/* ===================================================================== */

/*
 * Screen — the terminal viewport's dimensions, cached from ncurses.
 *
 * INTENT
 *   Decouple "what the terminal is" from "what the simulation is".
 *   ncurses owns the actual screen buffer, the input loop, and the
 *   colour-pair table; Screen just remembers cols × rows so we
 *   don't call getmaxyx() once per cell.
 *
 * LIFETIME
 *   screen_init   — calls initscr(), configures ncurses, captures
 *                   cols/rows.
 *   screen_resize — re-captures cols/rows after a SIGWINCH. Owner
 *                   (App) follows up with scene_reset to re-size
 *                   the GlowField.
 *   screen_free   — calls endwin() to restore the terminal.
 *
 * MEMBER LOGIC
 *   cols : terminal width  in cells. ≥ 16 enforced by
 *          app_pick_map_size (smaller and the HUD won't fit).
 *   rows : terminal height in cells. ≥ 8 enforced by
 *          app_pick_map_size; HUD reserves 3 rows top/bottom.
 *   Ordering matches the ncurses getmaxyx(stdscr, rows, cols)
 *   convention — rows first because curses originally targeted
 *   line-printers.
 */
typedef struct {
    int cols;     /* terminal width  in cells (≥ 16)  */
    int rows;     /* terminal height in cells (≥ 8)   */
} Screen;

static void screen_init(Screen *s)
{
    initscr();
    noecho();
    cbreak();
    curs_set(0);
    nodelay(stdscr, TRUE);
    keypad(stdscr, TRUE);
    typeahead(-1);
    color_init();
    getmaxyx(stdscr, s->rows, s->cols);
}
static void screen_free(Screen *s) { (void)s; endwin(); }
static void screen_resize(Screen *s)
{
    endwin();
    refresh();
    getmaxyx(stdscr, s->rows, s->cols);
}

/* ---------- scene_draw: grid → glyphs ---------------------------------- */

/*
 * GridPlacement — the top-left screen cell where the field's (0, 0)
 * cell will be drawn. The result of centering the GlowField inside
 * the terminal viewport, holding the HUD rows clear.
 *
 * INTENT
 *   Lift the centering math out of the per-cell inner loop. Without
 *   GridPlacement the loop would have to redo `(cols - field_w) / 2`
 *   plus the HUD-row offset on every cell — w·h times per frame.
 *   With it, the loop body becomes `screen_y = origin_y + y` which
 *   the compiler can fold into the loop induction variable.
 *
 *   Also names the "where on screen" decision so a reader sees
 *   `compute_grid_placement(...)` and immediately knows what's
 *   happening, instead of staring at four lines of `/ 2` arithmetic
 *   inline.
 *
 * CONTEXT
 *   Computed once at the top of scene_draw() (§8) by
 *   compute_grid_placement(field_w, field_h, cols, rows) and then
 *   passed implicitly via the local `place` to every cell.
 *
 *   Coordinate convention matches ncurses: (origin_y, origin_x) is
 *   the (row, col) of the top-left screen cell to start drawing at.
 *   Y grows DOWN (toward bottom of terminal), X grows RIGHT.
 *
 * INVARIANTS
 *   origin_x ≥ 0
 *   origin_y ≥ HUD_TOP_ROWS         (kept clear for the title bar)
 *   The bottom HUD_BOTTOM_ROWS rows are kept clear by sizing the
 *   field, not by clamping here — so origin_y + field_h may run up
 *   to (rows − HUD_BOTTOM_ROWS).
 *
 *   Negative results from the centering arithmetic (over-large
 *   field on a small viewport) are clamped to the viewport edge —
 *   the field is cropped, not wrapped. The "cell off-screen?"
 *   check in the drawer's inner loop handles the rest.
 *
 * MEMBER LOGIC
 *   origin_x : screen column (cells) of the field's leftmost cell.
 *              0 if the field is wider than the viewport.
 *   origin_y : screen row (cells) of the field's topmost cell.
 *              HUD_TOP_ROWS at minimum (never overlaps title bar).
 */
typedef struct {
    int origin_x;   /* screen column where field's left edge starts */
    int origin_y;   /* screen row    where field's top edge starts  */
} GridPlacement;

/* Centre the GlowField inside the terminal viewport, respecting the
 * HUD's reserved top + bottom rows. Negative offsets are clamped so
 * an over-large field is cropped, not wrapped. */
static GridPlacement compute_grid_placement(int field_w, int field_h,
                                            int cols, int rows)
{
    GridPlacement p;
    p.origin_x = (cols - field_w) / 2;
    p.origin_y = ((rows - HUD_BAND_RESERVED_ROWS) - field_h) / 2
                 + HUD_TOP_ROWS;
    if (p.origin_x < 0)            p.origin_x = 0;
    if (p.origin_y < HUD_TOP_ROWS) p.origin_y = HUD_TOP_ROWS;
    return p;
}

/* The one-cell paint primitive: bind colour, emit glyph, unbind. */
static inline void draw_glyph_at(int screen_y, int screen_x,
                                 char glyph, int color_pair, int attr)
{
    attron(COLOR_PAIR(color_pair) | attr);
    mvaddch(screen_y, screen_x, (chtype)(unsigned char)glyph);
    attroff(COLOR_PAIR(color_pair) | attr);
}

/*
 * scene_draw — paint the GlowField using the Scene's GlyphRamp and
 * the currently-bound colour palette.
 *
 *   place = centre field inside viewport
 *   FOR every cell:
 *     glyph_pick = ramp(glow)
 *     IF glyph_pick.visible:
 *       draw at place + (x, y) with band's colour
 *
 * Pure read of Scene state — no simulation here.
 */
static void scene_draw(const Scene *s, int cols, int rows)
{
    const GlowField *field = &s->field;
    const GlyphRamp *ramp  = &s->ramp;
    GridPlacement    place = compute_grid_placement(field->w, field->h,
                                                    cols, rows);

    for (int y = 0; y < field->h; y++) {
        int screen_y = place.origin_y + y;
        if (screen_y < 0 || screen_y >= rows) continue;
        for (int x = 0; x < field->w; x++) {
            int screen_x = place.origin_x + x;
            if (screen_x < 0 || screen_x >= cols) continue;

            int   cell_idx = glow_field_idx(field, x, y);
            float glow     = field->glow[cell_idx];

            GlyphChoice pick = glyph_ramp_pick(ramp, glow);
            if (!pick.visible) continue;

            int color_pair = PAIR_BAND_BASE + (field->band[cell_idx] & PALETTE_BAND_MASK);
            draw_glyph_at(screen_y, screen_x,
                          pick.glyph, color_pair, pick.attr);
        }
    }
}

/* ---------- HUD layout widths ----------------------------------------- *
 *
 * Per-segment widths for the status row 1 chain. Each hud_draw_*
 * helper consumes (and returns) the cursor x; these widths are how
 * far each segment moves it.
 */
#define HUD_W_PATTERN_FIELD   21   /* " pattern:%-10s "          */
#define HUD_W_TIER_FIELD      15   /* " tier:%-7s "              */
#define HUD_W_THEME_FIELD     17   /* " theme:%-8s "             */
#define HUD_W_PALETTE_LABEL    9   /* " palette:"                */

#define HUD_TITLE_ROW          0
#define HUD_STATUS_ROW         1
#define HUD_TITLE_TEXT         " VALUE NOISE "
#define HUD_BOTTOM_HINT_TEXT \
    " n/p:pattern  t/T:theme  r:reset  spc:pause  +/-:drift  ]/[:Hz  q:quit "

/* ---------- HUD: per-segment drawers ---------------------------------- *
 *
 * Each segment takes (row, x, ...) and returns the next x cursor
 * position so the caller can chain them.
 */

/* Row 0 LEFT — the program title chip. */
static int hud_draw_title_chip(int row, int x)
{
    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(row, x, "%s", HUD_TITLE_TEXT);
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    return x + (int)strlen(HUD_TITLE_TEXT);
}

/* Row 0 RIGHT — fps + Hz + state + pattern index + drift multiplier. */
static void hud_draw_state_bar(int row, int cols,
                               double fps, int sim_fps,
                               const PatternState *ps, bool paused)
{
    const char *state_text = paused ? "PAUSED    " : pattern_name(ps->current);
    char        buf[HUD_COLS + 1];
    snprintf(buf, sizeof buf,
             " %5.1f fps  %3d Hz  %s [%d/%d]  drift:x%-2d ",
             fps, sim_fps, state_text,
             (int)ps->current + 1, N_PATTERNS,
             ps->drift_mult);
    int right_aligned_x = cols - (int)strlen(buf);
    if (right_aligned_x < 0) right_aligned_x = 0;
    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(row, right_aligned_x, "%s", buf);
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);
}

/* Row 1 segment — "pattern:<NAME>" */
static int hud_draw_pattern_field(int row, int x, Pattern p)
{
    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(row, x, " pattern:%-10s ", pattern_name(p));
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    return x + HUD_W_PATTERN_FIELD;
}

/* Row 1 segment — "tier:<N-LABEL>" */
static int hud_draw_tier_field(int row, int x, Pattern p)
{
    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(row, x, " tier:%-7s ", pattern_tier(p));
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    return x + HUD_W_TIER_FIELD;
}

/* Row 1 segment — "theme:<NAME>" */
static int hud_draw_theme_field(int row, int x, int theme_idx)
{
    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(row, x, " theme:%-8s ", themes[theme_idx].name);
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    return x + HUD_W_THEME_FIELD;
}

/* Row 1 segment — "palette:" label + 4 coloured swatches so the user
 * can see each density-tier's colour at a glance in the active theme. */
static int hud_draw_palette_swatches(int row, int x)
{
    attron(COLOR_PAIR(PAIR_HUD));
    mvprintw(row, x, " palette:");
    attroff(COLOR_PAIR(PAIR_HUD));
    x += HUD_W_PALETTE_LABEL;
    for (int band = 0; band < N_PALETTE_BANDS; band++) {
        int color_pair = PAIR_BAND_BASE + band;
        attron(COLOR_PAIR(color_pair) | A_BOLD);
        mvaddch(row, x, '#');
        attroff(COLOR_PAIR(color_pair) | A_BOLD);
        x += 1;
    }
    return x;
}

/* Row 1 tail — algorithm parameter readout: noise scale, fBm octaves,
 * grid dimensions. */
static void hud_draw_stats_field(int row, int x, const GlowField *gf)
{
    attron(COLOR_PAIR(PAIR_HUD));
    mvprintw(row, x, "  scale:%.2f  oct:%d  map:%dx%d ",
             NOISE_SCALE, FBM_OCTAVES, gf->w, gf->h);
    attroff(COLOR_PAIR(PAIR_HUD));
}

/* Bottom row — keymap reminder. Fixed text; cyan + bold for contrast. */
static void hud_draw_action_hint(int row)
{
    attron(COLOR_PAIR(PAIR_HINT) | A_BOLD);
    mvprintw(row, 0, "%s", HUD_BOTTOM_HINT_TEXT);
    attroff(COLOR_PAIR(PAIR_HINT) | A_BOLD);
}

/* ---------- screen_draw: scene + full HUD ----------------------------- */

/*
 * screen_draw — the per-frame composite renderer. Pure read of state.
 *
 *   STEP 1  erase  — ncurses double-buffer
 *   STEP 2  scene  — paint the GlowField
 *   STEP 3  HUD row 0 — title (left) + state bar (right)
 *   STEP 4  HUD row 1 — pattern | tier | theme | swatches | stats
 *   STEP 5  HUD last row — action hint
 */
static void screen_draw(Screen *sc, const Scene *s, double fps, int sim_fps)
{
    erase();
    scene_draw(s, sc->cols, sc->rows);

    /* Row 0 — title + state bar */
    hud_draw_title_chip(HUD_TITLE_ROW, HUD_LEFT_MARGIN);
    hud_draw_state_bar (HUD_TITLE_ROW, sc->cols, fps, sim_fps,
                        &s->pattern, s->paused);

    /* Row 1 — chained left-to-right segments */
    int x = HUD_LEFT_MARGIN;
    x = hud_draw_pattern_field   (HUD_STATUS_ROW, x, s->pattern.current);
    x = hud_draw_tier_field      (HUD_STATUS_ROW, x, s->pattern.current);
    x = hud_draw_theme_field     (HUD_STATUS_ROW, x, s->palette.current);
    x = hud_draw_palette_swatches(HUD_STATUS_ROW, x);
    hud_draw_stats_field         (HUD_STATUS_ROW, x, &s->field);

    /* Bottom row — keymap hint */
    hud_draw_action_hint(sc->rows - 1);
}

static void screen_present(void) { wnoutrefresh(stdscr); doupdate(); }

/* ===================================================================== */
/* §9  app                                                                */
/* ===================================================================== */

/*
 * App — the top-level harness. Owns every other piece of state.
 *
 * INTENT
 *   ONE struct at the top of the dependency tree, holding the
 *   simulation (Scene), the terminal binding (Screen), the tick
 *   rate, the chosen map dimensions, and the two signal flags
 *   driving the main loop. main() touches App and only App; every
 *   other function takes App* (for write paths) or const App*
 *   (for read paths) — or a sub-struct pointer if it only needs
 *   part of the state.
 *
 * SINGLETON
 *   One file-scope instance (g_app, see below). Signal handlers
 *   need to reach the `running` / `need_resize` flags from outside
 *   any caller's scope, and POSIX signal handlers can't take a
 *   user pointer — a file-scope `App` is the simplest correct
 *   path. The handlers ONLY touch the volatile sig_atomic_t flags;
 *   the main loop owns everything else.
 *
 * LIFETIME
 *   main() does: zero-init g_app → screen_init → app_pick_map_size
 *   → scene_init → loop → screen_free. No teardown beyond endwin()
 *   via atexit() — App is in BSS so the OS reclaims it at exit.
 *
 * MEMBER LOGIC
 *   scene       : The simulation. See Scene above.
 *
 *   screen      : Terminal cols/rows. Refreshed on every SIGWINCH
 *                 by app_do_resize().
 *
 *   sim_fps     : Tick rate in Hz. Determines TICK_NS used by the
 *                 fixed-timestep accumulator in main(). Adjustable
 *                 by ] (faster) / [ (slower) keys; clamped to
 *                 [SIM_FPS_MIN, SIM_FPS_MAX] = [10, 240].
 *
 *   map_w,      : Grid dimensions selected by app_pick_map_size()
 *   map_h         from the terminal cols/rows minus HUD reservations.
 *                 Bounded by [16..MAP_W_MAX] × [8..MAP_H_MAX].
 *                 Passed to scene_reset on init and resize.
 *
 *   running     : Cleared to 0 by SIGINT / SIGTERM handlers (and
 *                 by app_handle_key on q/ESC). Main loop exits when
 *                 this goes false. `volatile sig_atomic_t` because:
 *                 (1) POSIX guarantees only sig_atomic_t writes are
 *                 async-safe inside a signal handler; (2) `volatile`
 *                 prevents the compiler from caching the read in
 *                 the main loop (the handler can flip it between
 *                 any two iterations).
 *
 *   need_resize : Set to 1 by SIGWINCH handler; consumed by main
 *                 loop, which then calls app_do_resize() and clears
 *                 it. Same volatile-sig_atomic_t rationale as
 *                 `running`. The signal → flag → main-loop-consumes
 *                 pattern keeps the handler tiny and signal-safe
 *                 (no libc calls beyond what's listed in
 *                 signal-safety(7)).
 */
typedef struct {
    Scene                 scene;        /* the simulation                       */
    Screen                screen;       /* terminal dims, refreshed on resize   */
    int                   sim_fps;      /* tick rate Hz, user-adjustable by ]/[ */
    int                   map_w;        /* chosen grid width  (cells)           */
    int                   map_h;        /* chosen grid height (cells)           */
    volatile sig_atomic_t running;      /* main-loop flag, 0 → exit             */
    volatile sig_atomic_t need_resize;  /* SIGWINCH→1, main loop consumes       */
} App;

static App g_app;

static void on_exit_signal  (int sig) { (void)sig; g_app.running     = 0; }
static void on_resize_signal(int sig) { (void)sig; g_app.need_resize = 1; }
static void cleanup(void)             { endwin(); }

static void app_pick_map_size(App *app)
{
    int mw = app->screen.cols;
    int mh = app->screen.rows - HUD_BAND_RESERVED_ROWS;
    if (mw < 16) mw = 16;
    if (mh < 8)  mh = 8;
    if (mw > MAP_W_MAX) mw = MAP_W_MAX;
    if (mh > MAP_H_MAX) mh = MAP_H_MAX;
    app->map_w = mw;
    app->map_h = mh;
}

static void app_do_resize(App *app)
{
    screen_resize(&app->screen);
    app_pick_map_size(app);
    scene_reset(&app->scene, app->map_w, app->map_h);
    app->need_resize = 0;
}

/* ---------- Scene action helpers (input → state mutation) ------------- *
 *
 * Each helper names ONE keystroke-triggered state change so
 * app_handle_key reads as a keymap rather than a switch full of
 * arithmetic. Direction parameters use ±1 throughout for next/prev
 * symmetry.
 */

/* Cycle the active pattern by ±1 with wraparound through N_PATTERNS. */
static void scene_cycle_pattern(Scene *s, int direction)
{
    int next = ((int)s->pattern.current + direction + N_PATTERNS) % N_PATTERNS;
    s->pattern.current = (Pattern)next;
}

/* Cycle the active theme by ±1 with wraparound, then rebind ncurses
 * colour pairs to the new palette via theme_apply (side effect). */
static void scene_cycle_theme(Scene *s, int direction)
{
    s->palette.current = (s->palette.current + direction + N_THEMES)
                         % N_THEMES;
    theme_apply(s->palette.current);
}

/* Drift speed control — multiplier doubles or halves in clean ×2 / ÷2
 * steps so the user perceives discrete speed changes, not a slider. */
static void scene_drift_double(PatternState *ps)
{
    if (ps->drift_mult < DRIFT_MULT_MAX) ps->drift_mult *= 2;
    if (ps->drift_mult > DRIFT_MULT_MAX) ps->drift_mult = DRIFT_MULT_MAX;
}
static void scene_drift_halve(PatternState *ps)
{
    ps->drift_mult /= 2;
    if (ps->drift_mult < DRIFT_MULT_MIN) ps->drift_mult = DRIFT_MULT_MIN;
}

/* Adjust sim tick rate by delta Hz, clamped to [SIM_FPS_MIN, MAX]. */
static void app_adjust_sim_fps(App *app, int delta)
{
    app->sim_fps += delta;
    if (app->sim_fps > SIM_FPS_MAX) app->sim_fps = SIM_FPS_MAX;
    if (app->sim_fps < SIM_FPS_MIN) app->sim_fps = SIM_FPS_MIN;
}

/*
 * app_handle_key — the keymap. Returns false on quit, true otherwise.
 * Every arm is a single named action so the switch reads as
 * "key → behaviour" without arithmetic inline.
 */
static bool app_handle_key(App *app, int ch)
{
    Scene *s = &app->scene;
    switch (ch) {
    case 'q': case 'Q': case 27 /* ESC */: return false;
    case ' ':            s->paused = !s->paused;                 break;
    case 'r': case 'R':  scene_reset(s, app->map_w, app->map_h); break;

    case '=': case '+':  scene_drift_double(&s->pattern);        break;
    case '-':            scene_drift_halve (&s->pattern);        break;

    case ']':            app_adjust_sim_fps(app, +SIM_FPS_STEP); break;
    case '[':            app_adjust_sim_fps(app, -SIM_FPS_STEP); break;

    case 't':            scene_cycle_theme  (s, +1);             break;
    case 'T':            scene_cycle_theme  (s, -1);             break;

    case 'n': case 'N':  scene_cycle_pattern(s, +1);             break;
    case 'p': case 'P':  scene_cycle_pattern(s, -1);             break;

    default:                                                     break;
    }
    return true;
}

/* ---------- FrameClock: timing accumulators for the main loop --------- */

/*
 * FrameClock — every running scalar the main loop's timing needs,
 * grouped under one name.
 *
 * INTENT
 *   The original main loop carried FIVE loose locals (frame_time,
 *   sim_accum, fps_accum, frame_count, fps_display) that all had
 *   to be initialised together, reset together on resize, and
 *   advanced together each frame. Grouping them makes the loop
 *   body a sequence of NAMED operations on one object
 *   (frame_clock_advance, fps_meter_observe, ...) instead of a
 *   collection of bare arithmetic against scattered locals.
 *
 * THE TWO SUB-ACCUMULATORS
 *   FrameClock combines two independent integrator patterns that
 *   happen to share `frame_dt_ns` as their input:
 *
 *     1) FIXED-TIMESTEP SIM DRIVER  (sim_accum_ns)
 *        Each frame's wall-clock dt is poured into the accumulator;
 *        drained one TICK_NS chunk at a time into scene_tick calls.
 *        The "Glenn Fiedler / 'Fix Your Timestep!'" pattern.
 *
 *     2) FPS METER                  (fps_accum_ns + fps_frame_count)
 *        Sum frame dts and count frames; every FPS_UPDATE_MS of wall
 *        clock, divide frames/seconds to refresh `fps_display`. The
 *        HUD reads `fps_display` only.
 *
 * Refs:
 *   • Glenn Fiedler, "Fix Your Timestep!" (gafferongames.com)
 *   • POSIX clock_gettime(CLOCK_MONOTONIC) — the wall-clock source
 *     in §2 clock_ns(); strictly increasing, immune to NTP jumps.
 */
typedef struct {
    int64_t frame_time_ns;     /* wall clock at start of current frame    */
    int64_t sim_accum_ns;      /* unconsumed time → sim ticks (Fiedler)   */
    int64_t fps_accum_ns;      /* ns since last FPS recomputation         */
    int     fps_frame_count;   /* frames since last FPS recomputation     */
    double  fps_display;       /* last computed FPS — the value HUD reads */
} FrameClock;

static void frame_clock_init(FrameClock *fc)
{
    fc->frame_time_ns   = clock_ns();
    fc->sim_accum_ns    = 0;
    fc->fps_accum_ns    = 0;
    fc->fps_frame_count = 0;
    fc->fps_display     = 0.0;
}

/* Re-anchor after a stall (e.g. SIGWINCH resize) so we don't burst-
 * tick to "catch up" on time the user wasn't seeing the sim. */
static void frame_clock_resync(FrameClock *fc)
{
    fc->frame_time_ns = clock_ns();
    fc->sim_accum_ns  = 0;
}

/* Advance the frame clock; return dt since previous frame, capped at
 * 100 ms to prevent the spiral-of-death failure mode. */
static int64_t frame_clock_advance(FrameClock *fc)
{
    int64_t now = clock_ns();
    int64_t dt  = now - fc->frame_time_ns;
    fc->frame_time_ns = now;
    if (dt > MAX_FRAME_DT_NS) dt = MAX_FRAME_DT_NS;
    return dt;
}

/* FPS meter — accumulate frame dt; every FPS_UPDATE_MS, divide
 * frames by elapsed seconds and refresh the display value. */
static void fps_meter_observe(FrameClock *fc, int64_t frame_dt_ns)
{
    fc->fps_frame_count++;
    fc->fps_accum_ns += frame_dt_ns;
    if (fc->fps_accum_ns >= FPS_UPDATE_MS * NS_PER_MS) {
        double elapsed_sec = (double)fc->fps_accum_ns / (double)NS_PER_SEC;
        fc->fps_display     = (double)fc->fps_frame_count / elapsed_sec;
        fc->fps_frame_count = 0;
        fc->fps_accum_ns    = 0;
    }
}

/* ---------- Main-loop step helpers ----------------------------------- */

/* Fiedler's fixed-timestep tick drain. Pour this frame's dt into the
 * accumulator, then consume it one TICK_NS chunk at a time, calling
 * scene_tick with a STABLE per-tick dt — so the simulation behaves
 * identically regardless of render-frame jitter. */
static void app_run_fixed_step_ticks(App *app, FrameClock *fc,
                                     int64_t frame_dt_ns)
{
    int64_t tick_ns     = TICK_NS(app->sim_fps);
    float   tick_dt_sec = (float)tick_ns / (float)NS_PER_SEC;

    fc->sim_accum_ns += frame_dt_ns;
    while (fc->sim_accum_ns >= tick_ns) {
        scene_tick(&app->scene, tick_dt_sec);
        fc->sim_accum_ns -= tick_ns;
    }
}

/* Sleep so the render loop spins at ~60 Hz. Compute how much wall-
 * clock has been consumed this iteration (tick work + frame-to-frame
 * gap) and sleep the remainder of the frame budget. */
static void app_throttle_to_render_rate(int64_t frame_start_ns,
                                        int64_t frame_dt_ns)
{
    int64_t target_frame_period_ns = NS_PER_SEC / RENDER_FPS_TARGET;
    int64_t time_consumed_ns       = clock_ns() - frame_start_ns
                                   + frame_dt_ns;
    clock_sleep_ns(target_frame_period_ns - time_consumed_ns);
}

/* Drain one key event (non-blocking) and route it to app_handle_key.
 * Quit returns false from the handler → we clear app->running. */
static void app_pump_input(App *app)
{
    int ch = getch();
    if (ch != ERR && !app_handle_key(app, ch))
        app->running = 0;
}

/* Wire SIGINT / SIGTERM → exit flag, SIGWINCH → resize flag.
 * Handler bodies are tiny (one volatile flip each) so they stay
 * inside the POSIX signal-safety envelope. */
static void app_install_signal_handlers(void)
{
    signal(SIGINT,   on_exit_signal);
    signal(SIGTERM,  on_exit_signal);
    signal(SIGWINCH, on_resize_signal);
}

/*
 * main — top-level driver. Reads as pseudocode:
 *
 *   bootstrap (PRNG seed, signal handlers, atexit cleanup)
 *   init terminal → pick grid size → init simulation
 *   init frame clock
 *   LOOP until app.running goes false:
 *     handle pending resize
 *     advance frame clock → frame_dt
 *     run fixed-step sim ticks (Fiedler)
 *     fps meter
 *     throttle to render rate
 *     draw scene + HUD; present
 *     pump input (may clear running)
 *   shutdown terminal
 */
int main(void)
{
    /* STEP 1 — bootstrap */
    srand((unsigned int)(clock_ns() & 0xFFFFFFFF));
    atexit(cleanup);
    app_install_signal_handlers();

    App *app     = &g_app;
    app->running = 1;
    app->sim_fps = SIM_FPS_DEFAULT;

    /* STEP 2 — terminal + simulation init */
    screen_init(&app->screen);
    app_pick_map_size(app);
    scene_init(&app->scene, app->map_w, app->map_h);

    /* STEP 3 — main loop */
    FrameClock clock;
    frame_clock_init(&clock);

    while (app->running) {
        if (app->need_resize) {
            app_do_resize(app);
            frame_clock_resync(&clock);
        }

        int64_t frame_dt_ns = frame_clock_advance(&clock);
        app_run_fixed_step_ticks   (app, &clock, frame_dt_ns);
        fps_meter_observe          (&clock, frame_dt_ns);
        app_throttle_to_render_rate(clock.frame_time_ns, frame_dt_ns);

        screen_draw(&app->screen, &app->scene,
                    clock.fps_display, app->sim_fps);
        screen_present();

        app_pump_input(app);
    }

    /* STEP 4 — shutdown */
    screen_free(&app->screen);
    return 0;
}
