/* Copyright (c) 2026 Tamilselvan R  SPDX-License-Identifier: MIT */
/*
 * maze_of_maze.c
 *   — A maze whose every cell contains its own smaller maze. Two
 *     levels of recursive maze nesting, each generated by an
 *     independent depth-first random-walk (the "recursive backtracker"
 *     algorithm). The outer-maze cells are rendered with bold walls;
 *     the inner mazes inside each cell are rendered with thinner
 *     walls and a different colour tint so the two scales remain
 *     visually distinct.
 *
 * DEMO: A grid of "rooms" fills the screen — that's the OUTER maze,
 *       carved by removing walls between adjacent cells until every
 *       room is reachable from every other. Inside each room, look
 *       closely: a complete SMALLER maze fills the room's interior,
 *       with its own walls and own corridors. Each inner maze is
 *       independently generated, so no two rooms have the same
 *       inner layout.
 *
 *       PATTERN (n / N) — controls the cell counts at each level:
 *
 *         CLASSIC   6×3 outer rooms, each holding a 6×4 inner maze
 *         WIDE      4×2 outer (big rooms), each with 10×6 inner
 *                   maze (most detail per room)
 *         DENSE     8×4 outer (small rooms), each with 4×3 inner
 *                   (most rooms total, sparser inner)
 *         EVEN      5×3 outer × 8×5 inner — balanced
 *
 *       GLYPH (g / G) — wall rendering style:
 *
 *         LINES     classic ASCII '+' '-' '|' walls (thin)
 *         BLOCKS    '#' walls everywhere (thick / solid)
 *         MIXED     outer walls '#', inner walls '+' '-' '|'
 *                   — exaggerates the visual hierarchy between scales
 *
 *       'r' reseeds — fresh outer maze + fresh inner mazes for every
 *       outer cell. Brightness drift continues smoothly.
 *
 * Study alongside:
 *   ../generational/wfc_showcase.c
 *      — wave-function-collapse: a constraint-based "maze-like"
 *        layout solver. The DFS carving here is simpler but
 *        guaranteed to make a perfect maze (single path between
 *        any two cells).
 *   ../patterns/wang_tiles.c
 *      — also tiling on a grid, but with edge-colour adjacency
 *        instead of carved passages.
 *
 * Section map:
 *   §1 config     — maze sizes per pattern, themes, glyph styles
 *   §2 clock      — monotonic timer + sleep
 *   §3 color      — HUD reserved + 10 themes (8-step ramp + accents)
 *   §5 maze       — hash, perlin/fBm, Maze struct, DFS carve,
 *                   maze-of-maze generation + rendering helpers
 *   §6 scene      — state, regenerate on pattern change / reseed
 *   §7 screen     — render outer + inner mazes with brightness drift
 *   §8 app        — signals, resize, fixed-step main loop
 *
 * Keys:
 *   q / ESC    quit
 *   space      pause / resume light-field drift
 *   r          reseed (all mazes regenerated)
 *   n / N      next pattern
 *   p / P      previous pattern
 *   g / G      next / previous glyph set
 *   t / T      next / previous theme
 *   + / =      faster light drift
 *   -          slower
 *   ] / [      raise / lower tick Hz
 *
 * Build:
 *   gcc -std=c11 -O2 -Wall -Wextra \
 *     procedural/patterns/maze_of_maze.c \
 *     -o maze_of_maze -lncurses -lm
 */

/* ── CONCEPTS ──────────────────────────────────────────────────────────── *
 *
 * Algorithm      : Two pieces composed together.
 *
 *                  (1) RECURSIVE BACKTRACKER (DFS) maze carving.
 *                      Start with a grid where every cell has all
 *                      four walls. Mark cell (0, 0) visited; from
 *                      each visited cell, pick a random unvisited
 *                      neighbour, knock down the shared wall, recurse
 *                      into the neighbour. When stuck, backtrack.
 *                      Result: a "perfect" maze — exactly one path
 *                      between any two cells, no loops, every cell
 *                      reachable. The simplest of the classical
 *                      maze algorithms; produces long winding
 *                      corridors and few short dead-ends.
 *
 *                  (2) NESTING. After carving the OUTER maze (size
 *                      W_outer × H_outer), generate W_outer ·
 *                      H_outer INDEPENDENT inner mazes (size
 *                      W_inner × H_inner each), each with its own
 *                      seed. When rendering, each outer cell
 *                      occupies a rectangular block on screen; the
 *                      block's interior holds that cell's inner
 *                      maze, drawn at smaller scale and dimmer
 *                      colour. The result is a maze of mazes —
 *                      two layers of structure visible
 *                      simultaneously.
 *
 *                  Plus a slow-drifting fBm BRIGHTNESS field
 *                  (same trick as truchet_tiles.c / wang_tiles.c)
 *                  modulates per-cell A_DIM/A_NORMAL/A_BOLD over the
 *                  static maze layout, giving subtle motion.
 *
 * Data-structure : Maze { w, h, walls[]:uint8 } — one byte per cell
 *                  encoding 4 wall bits (N=1, E=2, S=4, W=8). Outer
 *                  maze + up to MAX_OUTER_CELLS inner mazes
 *                  (MAX_OUTER_CELLS = 64). Total memory: a few
 *                  kilobytes.
 *
 * Rendering      : ASCII only. For each cell, draw the present walls
 *                  as horizontal/vertical line segments between
 *                  cells, with intersections at corners drawn as
 *                  '+'. Adjacent cells share walls; double-drawing
 *                  is harmless (idempotent same-colour write).
 *                  Outer walls drawn LAST so they overlay the inner
 *                  mazes at outer-cell boundaries.
 *
 * Performance    : Generation is O(cells) per maze. With pattern
 *                  CLASSIC: 18 outer cells + 18 inner mazes × 24
 *                  inner cells = ~450 cells total carved. Runs in
 *                  microseconds on regen.
 *                  Per-frame render: ~10 K wall-cell mvaddch calls
 *                  + one fBm sample per cell for brightness. About
 *                  10 % of a CPU core at 240×80 × 60 fps.
 *
 * References     :
 *   • Wikipedia — Maze generation algorithm
 *     https://en.wikipedia.org/wiki/Maze_generation_algorithm
 *   • Buck, Jamis — Mazes for Programmers (Pragmatic Bookshelf, 2015).
 *     The definitive guide to maze algorithms; recursive backtracker
 *     is chapter 1.
 *   • Think Labyrinth — comprehensive maze-algorithm reference
 *     http://www.astrolog.org/labyrnth/algrithm.htm
 *   • Wikipedia — Depth-first search
 *     https://en.wikipedia.org/wiki/Depth-first_search
 *
 * ─────────────────────────────────────────────────────────────────────── */

/* ── MENTAL MODEL ─────────────────────────────────────────────────────── *
 *
 * CORE IDEA
 * ─────────
 * A perfect maze is a SPANNING TREE on the grid graph: every cell is
 * connected, exactly one path between any two cells, no loops. The
 * recursive backtracker builds one by depth-first random walk — at
 * each step you knock down a wall to a fresh neighbour and step in;
 * when no fresh neighbour exists, you back up. The result is a maze
 * with long meandering corridors. To get a MAZE OF MAZES, take that
 * algorithm and run it not once but TWICE per scale — once for the
 * outer big maze, then once independently for every cell of that
 * maze. Each cell becomes its own little maze, and you can look at
 * the big picture or zoom into any room and find more structure.
 *
 * HOW TO THINK ABOUT IT
 * ─────────────────────
 * Imagine a hotel where every room is itself a hotel. You walk down
 * the long corridor of the OUTER hotel, picking doors at random.
 * Open one — inside is not a bedroom but another corridor with more
 * doors. Open one of THOSE — and inside is yet another (smaller)
 * room. The structure repeats. From the lobby you can in principle
 * reach any inner room of any outer room, but you have to navigate
 * the outer maze first and then the inner maze second. Each outer
 * room has its OWN floor plan; no two are the same.
 *
 * The fact that BOTH levels are MAZES (perfect, every cell reachable)
 * is just the Recursive Backtracker applied twice. The interesting
 * thing is that the two levels are generated independently — outer
 * and inner have no relationship — yet the visual whole reads as a
 * single coherent fractal-ish structure because the eye groups
 * adjacent cells naturally.
 *
 * ALGORITHM IN STEPS
 * ──────────────────
 *  1. CHOOSE SIZES. Outer maze is W_outer × H_outer; each inner
 *     maze is W_inner × H_inner. Pattern selects these.
 *  2. CARVE OUTER. dfs_carve(outer, 0, 0):
 *     a. Mark current cell visited.
 *     b. Shuffle the 4 directions {N, E, S, W} with a deterministic
 *        seeded RNG.
 *     c. For each direction in shuffled order:
 *          neighbour = step in that direction
 *          if neighbour is in-bounds and unvisited:
 *            remove the wall between current and neighbour
 *            recurse into neighbour
 *  3. CARVE EACH INNER. For (ox, oy) in [0..W_outer)×[0..H_outer):
 *       seed_inner = base_seed ^ hash(ox, oy)
 *       dfs_carve(inner[ox, oy], 0, 0)  with this seed
 *  4. EACH FRAME:
 *       a. Advance brightness wind.
 *       b. Compute outer cell screen size = total_screen / (W_outer, H_outer)
 *       c. Compute inner cell screen size = (outer cell − 1) / (W_inner, H_inner)
 *       d. For each outer cell, render its inner maze inside the
 *          outer cell's interior region.
 *       e. Render the outer maze on top (its walls overdraw the
 *          inner-maze walls at outer-cell boundaries).
 *       f. For each wall cell drawn, sample the fBm brightness field
 *          and choose A_DIM / A_NORMAL / A_BOLD.
 *  5. HUD on top.
 *
 * KEY FORMULAS
 * ────────────
 *  Wall bit encoding (per cell):
 *    bit 0 (1) = North wall
 *    bit 1 (2) = East wall
 *    bit 2 (4) = South wall
 *    bit 3 (8) = West wall
 *    initial state: all walls present (0xF)
 *
 *  DFS carve, removing wall between cell (x, y) and neighbour at
 *  direction d:
 *    walls[y][x]    &= ~(1 << d)            // remove our wall
 *    walls[ny][nx]  &= ~(1 << OPPOSITE[d])  // remove their wall
 *
 *  Direction tables (clockwise from N):
 *    DX = {  0,  1,  0, -1 }
 *    DY = { -1,  0,  1,  0 }
 *    OPPOSITE = { 2, 3, 0, 1 }
 *
 *  Outer cell screen size:
 *    cw_outer = total_screen_w / W_outer
 *    ch_outer = total_screen_h / H_outer
 *
 *  Inner cell screen size (within an outer cell, leaving 1 cell for
 *  the outer wall on each side):
 *    cw_inner = (cw_outer - 1) / W_inner
 *    ch_inner = (ch_outer - 1) / H_inner
 *
 *  Brightness modulation (per wall cell):
 *    b = fbm2(sx · BSC_X + wind_x, sy · BSC_Y · ASPECT_Y)
 *    attr = (b > 0.65) ? A_BOLD : (b < 0.35) ? A_DIM : A_NORMAL
 *
 * EDGE CASES TO WATCH
 * ───────────────────
 *  • DFS RECURSION DEPTH. Worst case is the longest possible
 *    Hamiltonian path through the maze grid — bounded by
 *    W_outer · H_outer (outer) or W_inner · H_inner (inner). With
 *    caps at 16 × 16 = 256 cells, recursion depth ≤ 256. Each stack
 *    frame is ~50 bytes; total ≤ 13 KB stack, comfortably within
 *    default thread stacks.
 *
 *  • SHARED WALL BETWEEN ADJACENT CELLS. Each interior wall belongs
 *    to TWO cells. The renderer draws BOTH cells' walls, so the
 *    interior wall gets drawn twice (idempotent, same colour).
 *    Cleaner alternatives (skip duplicates) would track a hash set
 *    of edges — not worth the complexity.
 *
 *  • OUTER CELL VS SCREEN BOUNDARY. The outermost edge of the outer
 *    maze (row 0 north, column 0 west, etc.) has all-cells-have-
 *    that-wall-set, so the outer maze always has a complete
 *    rectangular border. Good for visual cohesion.
 *
 *  • INNER MAZE FITTING. If the inner cell size rounds down to <2
 *    in either axis, the inner maze becomes invisible (walls on top
 *    of walls). Cap MIN_CELL_W=2, MIN_CELL_H=1 in the pattern
 *    config; if a pattern's inner maze can't fit at the current
 *    screen size, the renderer silently skips inner-maze drawing
 *    inside that outer cell.
 *
 *  • DETERMINISTIC SEED PER INNER MAZE. We compute each inner
 *    maze's seed as `base_seed ^ hash3(ox, oy, salt)`, so the same
 *    base_seed always produces the same maze of mazes. Reseeding
 *    with 'r' picks a new base_seed — every inner maze regenerates.
 *
 *  • OUTER WALLS OVER INNER MAZES. We render inner mazes FIRST,
 *    then outer mazes ON TOP. Otherwise outer-cell-boundary walls
 *    might be eaten by inner mazes that happen to draw a passage
 *    near the boundary.
 *
 *  • ASPECT NOT CORRECTED FOR INNER. We don't try to make inner
 *    cells visually square — they tend to be tall and thin in
 *    horizontal-maze visualisation. ASCII cell aspect (2:1) makes
 *    the issue worse but it's mostly OK.
 *
 * HOW TO VERIFY
 * ─────────────
 *  • Pause (space). Brightness freezes. Resume: drift continues.
 *
 *  • Press 'r'. The flash fires and ALL mazes change (outer + every
 *    inner). The pattern stays the same — rooms remain in the same
 *    grid arrangement — but the carved corridors all randomise.
 *
 *  • CLASSIC pattern. Count outer rooms: 6 × 3 = 18. Trace the outer
 *    maze: every room should be reachable from every other through
 *    door openings (cells where the outer wall is absent). Inside
 *    each room, the inner maze should also be a perfect maze
 *    (every inner cell reachable from every other inner cell of
 *    THE SAME ROOM).
 *
 *  • Switch to WIDE. Now there are only 4 × 2 = 8 outer rooms but
 *    each is large and contains a 10 × 6 = 60-cell inner maze. The
 *    fine detail per room is visibly higher than CLASSIC.
 *
 *  • Switch to DENSE. 32 outer rooms, but each inner maze is only
 *    4 × 3 = 12 cells — rooms read as small "chunks" of layout.
 *
 *  • Glyph cycle (g). The maze layouts don't change; only the wall
 *    rendering does. LINES gives clean ASCII art; BLOCKS makes a
 *    chunkier look; MIXED visually separates the outer (#) from
 *    the inner (+ - |) layer.
 *
 *  • Inner mazes ARE INDEPENDENT. Two adjacent rooms have unrelated
 *    inner layouts — the inner walls do NOT line up across the
 *    outer-room boundary. (An interesting variant would be to align
 *    them; we don't, on purpose, for visual variety.)
 *
 * ─────────────────────────────────────────────────────────────────────── */

#define _POSIX_C_SOURCE 200809L

#include <math.h>
#include <ncurses.h>
#include <signal.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ===================================================================== */
/* §1  config                                                             */
/* ===================================================================== */

enum {
    SIM_FPS_MIN         =  10,
    SIM_FPS_DEFAULT     =  60,
    SIM_FPS_MAX         = 240,
    SIM_FPS_STEP        =  10,

    SPEED_MIN           =   1,
    SPEED_DEF           =   8,
    SPEED_MAX           =  64,

    HUD_COLS            =  80,
    FPS_UPDATE_MS       = 500,

    /* Per-maze cell limits.  Outer max 16×8 = 128 cells; inner max
     * 16×8 = 128. Generous bounds; patterns use far less. */
    MAX_MAZE_W          =  16,
    MAX_MAZE_H          =   8,
    MAX_MAZE_CELLS      = MAX_MAZE_W * MAX_MAZE_H,

    /* Outer cell limit for the inner-maze pool. With a 16×8 outer
     * maze, that's 128 inner mazes. */
    MAX_OUTER_CELLS     = MAX_MAZE_W * MAX_MAZE_H,

    /* Color pair indices.  PAIR_HUD/PAIR_HINT reserved per CLAUDE.md. */
    PAIR_HUD            =   1,
    PAIR_HINT           =   2,
    PAIR_RAMP_BASE      =   3,    /* +0..+7 = 8 brightness/colour tints */
    PAIR_HOT            =  11,
    PAIR_COLD           =  12,
    PAIR_FLASH          =  13,
};

#define NS_PER_SEC      1000000000LL
#define NS_PER_MS          1000000LL
#define TICK_NS(f)      (NS_PER_SEC / (f))

#define ASPECT_Y_F           2.0f

/* Brightness fBm parameters — slow drift over the static mazes. */
#define BRIGHT_SCALE_X       0.040f
#define BRIGHT_SCALE_Y       0.080f
#define WIND_X_BASE          3.0f
#define FBM_OCTAVES          3

/* Wall bit positions. */
#define WALL_N               0x1u
#define WALL_E               0x2u
#define WALL_S               0x4u
#define WALL_W               0x8u

/* Ramp slot for outer vs inner walls — both chosen from the BRIGHT
 * half of the ramp so the inner stays visible even when the brightness
 * fBm field is at its dim end. INNER_RAMP=5 (was 3) ensures the
 * inner walls don't disappear; OUTER_RAMP=7 keeps the outer
 * dominant. Inner walls additionally never go to A_DIM (see the
 * `no_dim` flag in draw_wall_cell) — they're always at least
 * A_NORMAL so the inner-maze structure is always readable. */
#define OUTER_RAMP           7
#define INNER_RAMP           5

/*
 * Pattern enum — different (outer, inner) maze size combos.
 */
typedef enum {
    PATTERN_CLASSIC = 0,
    PATTERN_WIDE    = 1,
    PATTERN_DENSE   = 2,
    PATTERN_EVEN    = 3,
    N_PATTERNS      = 4,
} Pattern;

typedef struct {
    int outer_w, outer_h;
    int inner_w, inner_h;
} PatternCfg;

static const PatternCfg PATTERN_CFG[N_PATTERNS] = {
    /*               outer  inner */
    [PATTERN_CLASSIC] = { 6, 3,   6, 4 },
    [PATTERN_WIDE   ] = { 4, 2,  10, 6 },
    [PATTERN_DENSE  ] = { 8, 4,   4, 3 },
    [PATTERN_EVEN   ] = { 5, 3,   8, 5 },
};

static const char *pattern_name(Pattern p)
{
    switch (p) {
    case PATTERN_CLASSIC: return "CLASSIC";
    case PATTERN_WIDE:    return "WIDE   ";
    case PATTERN_DENSE:   return "DENSE  ";
    case PATTERN_EVEN:    return "EVEN   ";
    default:              return "?      ";
    }
}

/* GlyphSet — wall rendering style. */
typedef enum {
    GLYPH_LINES  = 0,
    GLYPH_BLOCKS = 1,
    GLYPH_MIXED  = 2,
    N_GLYPH_SETS = 3,
} GlyphSet;

static const char *glyph_set_name(GlyphSet g)
{
    switch (g) {
    case GLYPH_LINES:  return "lines";
    case GLYPH_BLOCKS: return "block";
    case GLYPH_MIXED:  return "mixed";
    default:           return "?    ";
    }
}

/* WallStyle — three glyphs that describe how to draw a maze level. */
typedef struct {
    char h_wall;     /* horizontal-segment glyph */
    char v_wall;     /* vertical-segment glyph   */
    char corner;     /* intersection glyph       */
} WallStyle;

static const WallStyle STYLE_LINES  = { '-', '|', '+' };
static const WallStyle STYLE_BLOCKS = { '#', '#', '#' };

static WallStyle outer_style_for(GlyphSet g)
{
    switch (g) {
    case GLYPH_LINES:  return STYLE_LINES;
    case GLYPH_BLOCKS: return STYLE_BLOCKS;
    case GLYPH_MIXED:  return STYLE_BLOCKS;
    default:           return STYLE_LINES;
    }
}

static WallStyle inner_style_for(GlyphSet g)
{
    switch (g) {
    case GLYPH_LINES:  return STYLE_LINES;
    case GLYPH_BLOCKS: return STYLE_BLOCKS;
    case GLYPH_MIXED:  return STYLE_LINES;
    default:           return STYLE_LINES;
    }
}

/*
 * Themes — every entry sits in the bright half of the 256-colour
 * cube so even A_DIM cells stay legible against a default-black
 * terminal.  See "Theme Palette Brightness" in /CLAUDE.md.
 */
typedef struct {
    const char *name;
    short       ramp[8];
    short       hot;
    short       cold;
} Theme;

#define N_THEMES 10

static const Theme themes[N_THEMES] = {
    /* name       0    1    2    3    4    5    6    7   hot cold */
    { "DEFAULT",{ 24,  31,  39,  70,  76, 137, 215, 230 }, 196,  39 },
    { "MATRIX", { 28,  34,  40,  46,  76, 118, 154, 192 }, 226,  39 },
    { "NOVA",   { 60,  91, 134, 165, 207, 213, 219, 231 }, 196,  39 },
    { "MONO",   {240, 243, 245, 247, 249, 251, 253, 255 }, 226,  39 },
    { "OCEAN",  { 24,  25,  31,  38,  45,  51, 117, 195 }, 196,  21 },
    { "FIRE",   { 88, 124, 130, 166, 202, 208, 214, 226 }, 226,  21 },
    { "EARTH",  { 94, 130, 137, 173, 179, 215, 222, 230 }, 196,  39 },
    { "FOREST", { 28,  34,  40,  70,  76, 112, 156, 192 }, 196,  39 },
    { "DESERT", {130, 137, 143, 173, 179, 215, 222, 229 }, 196,  21 },
    { "ARCTIC", { 24,  31,  67, 110, 117, 153, 195, 231 }, 196,  39 },
};

/* ===================================================================== */
/* §2  clock                                                              */
/* ===================================================================== */

static int64_t clock_ns(void)
{
    struct timespec t;
    clock_gettime(CLOCK_MONOTONIC, &t);
    return (int64_t)t.tv_sec * NS_PER_SEC + t.tv_nsec;
}

static void clock_sleep_ns(int64_t ns)
{
    if (ns <= 0) return;
    struct timespec req = {
        .tv_sec  = (time_t)(ns / NS_PER_SEC),
        .tv_nsec = (long)  (ns % NS_PER_SEC),
    };
    nanosleep(&req, NULL);
}

/* ===================================================================== */
/* §3  color                                                              */
/* ===================================================================== */

static void theme_apply(int idx)
{
    if (idx < 0 || idx >= N_THEMES) idx = 0;
    if (COLORS >= 256) {
        const Theme *t = &themes[idx];
        for (int i = 0; i < 8; i++)
            init_pair((short)(PAIR_RAMP_BASE + i), t->ramp[i], -1);
        init_pair(PAIR_HOT,  t->hot,  -1);
        init_pair(PAIR_COLD, t->cold, -1);
    } else {
        static const short fb[8] = {
            COLOR_BLUE,  COLOR_BLUE,  COLOR_CYAN,   COLOR_CYAN,
            COLOR_GREEN, COLOR_YELLOW,COLOR_YELLOW, COLOR_WHITE,
        };
        for (int i = 0; i < 8; i++)
            init_pair((short)(PAIR_RAMP_BASE + i), fb[i], -1);
        init_pair(PAIR_HOT,  COLOR_RED,  -1);
        init_pair(PAIR_COLD, COLOR_CYAN, -1);
    }
}

static void color_init(void)
{
    start_color();
    use_default_colors();
    if (COLORS >= 256) {
        init_pair(PAIR_HUD,   226, -1);
        init_pair(PAIR_HINT,   51, -1);
        init_pair(PAIR_FLASH, 226, -1);
    } else {
        init_pair(PAIR_HUD,   COLOR_YELLOW, -1);
        init_pair(PAIR_HINT,  COLOR_CYAN,   -1);
        init_pair(PAIR_FLASH, COLOR_YELLOW, -1);
    }
    theme_apply(0);
}

/* ===================================================================== */
/* §5  maze — hash, perlin, DFS carve, render helpers                     */
/* ===================================================================== */

/* hash3 — same routine as other showcases. */
static inline uint32_t hash3(int wx, int wy, int wz)
{
    uint32_t h = (uint32_t)wx * 73856093u
               ^ (uint32_t)wy * 19349663u
               ^ (uint32_t)wz * 83492791u;
    h ^= h >> 16;
    h *= 0x85ebca6bu;
    h ^= h >> 13;
    h *= 0xc2b2ae35u;
    h ^= h >> 16;
    return h;
}

/* Perlin scaffold — copied inline per the self-contained-file rule. */
static uint8_t perm[512];

static void perm_shuffle(int seed)
{
    uint8_t base[256];
    for (int i = 0; i < 256; i++) base[i] = (uint8_t)i;
    uint32_t st = (uint32_t)seed * 2654435761u;
    for (int i = 255; i > 0; i--) {
        st = st * 1664525u + 1013904223u;
        int j = (int)(st >> 16) % (i + 1);
        uint8_t t = base[i]; base[i] = base[j]; base[j] = t;
    }
    for (int i = 0; i < 256; i++) {
        perm[i      ] = base[i];
        perm[i + 256] = base[i];
    }
}

static inline float fade_q(float t)
{
    return t * t * t * (t * (t * 6.0f - 15.0f) + 10.0f);
}
static inline float lerp_f(float a, float b, float t) { return a + t * (b - a); }
static inline float grad2(int hash, float x, float y)
{
    int h = hash & 7;
    float u = (h < 4) ? x : y;
    float v = (h < 4) ? y : x;
    return ((h & 1) ? -u : u) + ((h & 2) ? -2.0f * v : 2.0f * v);
}

static float perlin2d(float x, float y)
{
    int X = (int)floorf(x) & 255;
    int Y = (int)floorf(y) & 255;
    x -= floorf(x); y -= floorf(y);
    float u = fade_q(x), v = fade_q(y);
    int A = perm[X    ] + Y;
    int B = perm[X + 1] + Y;
    float n00 = grad2(perm[A    ], x,        y       );
    float n10 = grad2(perm[B    ], x - 1.0f, y       );
    float n01 = grad2(perm[A + 1], x,        y - 1.0f);
    float n11 = grad2(perm[B + 1], x - 1.0f, y - 1.0f);
    return lerp_f(lerp_f(n00, n10, u), lerp_f(n01, n11, u), v);
}

static float fbm2(float x, float y)
{
    float total = 0.0f, amp = 1.0f, freq = 1.0f, max_amp = 0.0f;
    for (int o = 0; o < FBM_OCTAVES; o++) {
        total   += amp * perlin2d(x * freq, y * freq);
        max_amp += amp;
        amp     *= 0.5f;
        freq    *= 2.0f;
    }
    return (total / max_amp) * 0.5f + 0.5f;     /* → [0, 1] */
}

/* ----------------------------------------------------------------------- *
 * Maze + DFS carve.                                                        *
 * ----------------------------------------------------------------------- */

typedef struct {
    int     w, h;
    uint8_t walls[MAX_MAZE_CELLS];
} Maze;

/* Direction tables, clockwise from N. */
static const int DX[4] = {  0,  1,  0, -1 };
static const int DY[4] = { -1,  0,  1,  0 };
static const int OPP[4] = { 2,  3,  0,  1 };
static const uint8_t WALL_BIT[4] = { WALL_N, WALL_E, WALL_S, WALL_W };

/*
 * tiny LCG — deterministic per-call randomness for the DFS shuffle.
 * Seeded from the maze's seed; produces reproducible mazes.
 */
static inline uint32_t lcg_next(uint32_t *st)
{
    *st = (*st) * 1664525u + 1013904223u;
    return *st;
}

static void shuffle4(int *a, uint32_t *st)
{
    for (int i = 3; i > 0; i--) {
        int j = (int)(lcg_next(st) >> 16) % (i + 1);
        int t = a[i]; a[i] = a[j]; a[j] = t;
    }
}

/*
 * dfs_carve — recursive backtracker. From cell (x, y), shuffle the
 * four directions, and for each unvisited in-bounds neighbour,
 * remove the shared wall and recurse. When all 4 are visited or
 * out-of-bounds, return (effectively backtracking).
 *
 * `visited` is a flat bool array of size m->w * m->h, owned by the
 * caller (allocated on stack in maze_generate). `st` is the LCG state
 * threaded through recursive calls.
 */
static void dfs_carve(Maze *m, int x, int y, bool *visited, uint32_t *st)
{
    visited[y * m->w + x] = true;
    int order[4] = { 0, 1, 2, 3 };
    shuffle4(order, st);
    for (int i = 0; i < 4; i++) {
        int d  = order[i];
        int nx = x + DX[d];
        int ny = y + DY[d];
        if (nx < 0 || nx >= m->w || ny < 0 || ny >= m->h) continue;
        if (visited[ny * m->w + nx]) continue;
        m->walls[y  * m->w + x ] &= (uint8_t)~WALL_BIT[d];
        m->walls[ny * m->w + nx] &= (uint8_t)~WALL_BIT[OPP[d]];
        dfs_carve(m, nx, ny, visited, st);
    }
}

static void maze_generate(Maze *m, int seed)
{
    int total = m->w * m->h;
    if (total > MAX_MAZE_CELLS) return;     /* should never happen */
    bool visited[MAX_MAZE_CELLS];
    for (int i = 0; i < total; i++) {
        m->walls[i] = (uint8_t)0xF;
        visited[i]  = false;
    }
    uint32_t st = (uint32_t)seed * 2654435761u + 1u;
    if (st == 0) st = 1;
    dfs_carve(m, 0, 0, visited, &st);
}

/* ----------------------------------------------------------------------- *
 * Maze of maze.                                                            *
 * ----------------------------------------------------------------------- */

typedef struct {
    Maze outer;
    Maze inner[MAX_OUTER_CELLS];
    int  outer_count;          /* outer.w * outer.h, cached            */
} MazeOfMaze;

static void mom_generate(MazeOfMaze *mom, const PatternCfg *cfg, int seed)
{
    int ow = cfg->outer_w, oh = cfg->outer_h;
    int iw = cfg->inner_w, ih = cfg->inner_h;
    if (ow > MAX_MAZE_W) ow = MAX_MAZE_W;
    if (oh > MAX_MAZE_H) oh = MAX_MAZE_H;
    if (iw > MAX_MAZE_W) iw = MAX_MAZE_W;
    if (ih > MAX_MAZE_H) ih = MAX_MAZE_H;

    mom->outer.w = ow;
    mom->outer.h = oh;
    maze_generate(&mom->outer, seed);

    mom->outer_count = ow * oh;
    for (int oy = 0; oy < oh; oy++) {
        for (int ox = 0; ox < ow; ox++) {
            int idx = oy * ow + ox;
            mom->inner[idx].w = iw;
            mom->inner[idx].h = ih;
            int inner_seed = seed ^ (int)hash3(ox, oy, 0xBEEF);
            maze_generate(&mom->inner[idx], inner_seed);
        }
    }
}

/* ===================================================================== */
/* §6  scene                                                              */
/* ===================================================================== */

typedef struct {
    MazeOfMaze mom;
    bool       paused;
    int        speed;
    int        current_theme;
    Pattern    current_pattern;
    GlyphSet   current_glyph;
    int        seed;
    float      time_secs;
    float      wind_x;
    float      flash_t;
} Scene;

/*
 * apply_perm — reshuffle the Perlin perm[] for the current
 * (seed, pattern) pair so the brightness field changes per pattern.
 * Same trick as truchet_tiles.c / wang_tiles.c / penrose_tiling.c.
 */
static void apply_perm(const Scene *s)
{
    perm_shuffle(s->seed ^ ((int)s->current_pattern * 0xA5A5A5));
}

static void scene_regenerate(Scene *s)
{
    apply_perm(s);
    mom_generate(&s->mom, &PATTERN_CFG[s->current_pattern], s->seed);
    s->flash_t = 1.0f;
}

static void scene_reseed(Scene *s)
{
    s->seed = (int)hash3((int)(s->time_secs * 1000.0f),
                         (int)(s->wind_x * 100.0f), 0xC0FFEE);
    scene_regenerate(s);
}

static void scene_init(Scene *s)
{
    memset(s, 0, sizeof *s);
    s->paused          = false;
    s->speed           = SPEED_DEF;
    s->current_theme   = 0;
    s->current_pattern = PATTERN_CLASSIC;
    s->current_glyph   = GLYPH_LINES;
    s->seed            = 0xCAFE;
    scene_regenerate(s);
}

/*
 * scene_tick — advance brightness wind. Maze layout is static until
 * the user reseeds or changes pattern.
 */
static void scene_tick(Scene *s, float dt)
{
    s->time_secs += dt;
    s->flash_t   *= expf(-4.0f * dt);
    if (s->paused) return;

    float speed_mul = (float)s->speed / (float)SPEED_DEF;
    s->wind_x += WIND_X_BASE * speed_mul * dt;
}

/* ===================================================================== */
/* §7  screen                                                             */
/* ===================================================================== */

typedef struct {
    int cols, rows;
} Screen;

static void screen_init(Screen *s)
{
    initscr();
    noecho();
    cbreak();
    curs_set(0);
    nodelay(stdscr, TRUE);
    keypad(stdscr, TRUE);
    typeahead(-1);
    color_init();
    getmaxyx(stdscr, s->rows, s->cols);
}
static void screen_free(Screen *s) { (void)s; endwin(); }
static void screen_resize(Screen *s)
{
    endwin();
    refresh();
    getmaxyx(stdscr, s->rows, s->cols);
}

/*
 * bright_at — slow drifting fBm spotlight value at a screen cell.
 * Returns [0, 1]. Used to modulate per-cell A_DIM/A_NORMAL/A_BOLD.
 */
static inline float bright_at(int sx, int sy, float wind_x)
{
    float nx = (float)sx * BRIGHT_SCALE_X + wind_x;
    float ny = (float)sy * BRIGHT_SCALE_Y * ASPECT_Y_F;
    float b  = fbm2(nx, ny);
    if (b < 0.0f) b = 0.0f;
    if (b > 1.0f) b = 1.0f;
    return b;
}

/*
 * draw_wall_cell — write one wall-segment glyph at (sy, sx) with
 * brightness modulation. Bounds-checks against the screen (rows-1
 * reserved for HUD).
 *
 * `no_dim` clamps the brightness floor to A_NORMAL — used for inner
 * walls so they remain readable everywhere, even where the fBm
 * brightness field is at its dim end. Outer walls leave it false so
 * the dim/normal/bold contrast still animates the outer scale.
 */
static inline void draw_wall_cell(const Screen *sc, const Scene *s,
                                  int sx, int sy, char glyph,
                                  int pair, int extra_attr, bool no_dim)
{
    if (sy < 2 || sy >= sc->rows - 1) return;
    if (sx < 0 || sx >= sc->cols)     return;
    float b = bright_at(sx, sy, s->wind_x);
    int b_attr;
    if      (b > 0.65f)             b_attr = A_BOLD;
    else if (b < 0.35f && !no_dim)  b_attr = A_DIM;
    else                            b_attr = A_NORMAL;
    int attr = b_attr | extra_attr;
    attron(COLOR_PAIR(pair) | attr);
    mvaddch(sy, sx, (chtype)(unsigned char)glyph);
    attroff(COLOR_PAIR(pair) | attr);
}

/*
 * render_maze — draw all walls of one maze at (gx, gy) with the
 * given cell dimensions and wall style. Adjacent cells share walls;
 * we draw both copies (idempotent same-colour write).
 *
 * Corners (intersections at all (mx · cw, my · ch)) are drawn LAST
 * so they overlay any wall-segment glyph at that cell — keeps the
 * '+' visible at every intersection.
 */
static void render_maze(const Screen *sc, const Scene *s,
                        const Maze *m, int gx, int gy,
                        int cw, int ch,
                        WallStyle style, int pair, int extra_attr,
                        bool no_dim)
{
    /* Wall segments. */
    for (int my = 0; my < m->h; my++) {
        for (int mx = 0; mx < m->w; mx++) {
            uint8_t w  = m->walls[my * m->w + mx];
            int     sx = gx + mx * cw;
            int     sy = gy + my * ch;

            if (w & WALL_N) {
                for (int dx = 1; dx < cw; dx++)
                    draw_wall_cell(sc, s, sx + dx, sy,
                                   style.h_wall, pair, extra_attr, no_dim);
            }
            if (w & WALL_E) {
                for (int dy = 1; dy < ch; dy++)
                    draw_wall_cell(sc, s, sx + cw, sy + dy,
                                   style.v_wall, pair, extra_attr, no_dim);
            }
            if (w & WALL_S) {
                for (int dx = 1; dx < cw; dx++)
                    draw_wall_cell(sc, s, sx + dx, sy + ch,
                                   style.h_wall, pair, extra_attr, no_dim);
            }
            if (w & WALL_W) {
                for (int dy = 1; dy < ch; dy++)
                    draw_wall_cell(sc, s, sx, sy + dy,
                                   style.v_wall, pair, extra_attr, no_dim);
            }
        }
    }

    /* Corners — at every grid intersection, regardless of walls. */
    for (int my = 0; my <= m->h; my++) {
        for (int mx = 0; mx <= m->w; mx++) {
            int sx = gx + mx * cw;
            int sy = gy + my * ch;
            draw_wall_cell(sc, s, sx, sy, style.corner, pair, extra_attr, no_dim);
        }
    }
}

/*
 * scene_draw — render the maze of mazes. Inner mazes drawn first;
 * the outer maze drawn LAST so its boundary walls overlay any
 * inner-maze drawing that happened to land on the outer-cell edge.
 */
static void scene_draw(const Screen *sc, const Scene *s)
{
    const PatternCfg *cfg = &PATTERN_CFG[s->current_pattern];
    int outer_w = cfg->outer_w;
    int outer_h = cfg->outer_h;
    int inner_w = cfg->inner_w;
    int inner_h = cfg->inner_h;

    int top    = 2;
    int bottom = sc->rows - 1;
    int avail_w = sc->cols;
    int avail_h = bottom - top;

    /* Compute outer cell screen size. We need the outer maze grid
     * (outer_w · cw + 1 cells) to fit inside avail_w × avail_h. */
    int cw_outer = (avail_w - 1) / outer_w;
    int ch_outer = (avail_h - 1) / outer_h;
    if (cw_outer < 6) cw_outer = 6;
    if (ch_outer < 4) ch_outer = 4;

    /* Centre the maze of mazes on screen. */
    int total_w = cw_outer * outer_w + 1;
    int total_h = ch_outer * outer_h + 1;
    int gx = (avail_w - total_w) / 2;
    int gy = top + (avail_h - total_h) / 2;
    if (gx < 0)   gx = 0;
    if (gy < top) gy = top;

    /* Inner cell sizing — inside the outer cell, leaving 1 cell on
     * each side for the outer wall. The inner maze's RENDERED size
     * is (cw_inner · inner_w + 1) cells wide (the trailing +1 is the
     * maze's own far-edge border), so we divide (interior - 1) by
     * the cell count rather than `interior / inner_*`.  Without
     * this off-by-one the inner border doesn't fit and `inner_fits`
     * silently bails out, leaving only the outer maze on screen.
     *
     * We further centre the inner maze inside the outer cell's
     * interior so it doesn't sit flush against an arbitrary corner. */
    int interior_w = cw_outer - 1;
    int interior_h = ch_outer - 1;
    int cw_inner = (interior_w - 1) / inner_w;
    int ch_inner = (interior_h - 1) / inner_h;
    if (cw_inner < 2) cw_inner = 2;
    if (ch_inner < 2) ch_inner = 2;

    int inner_total_w = cw_inner * inner_w + 1;
    int inner_total_h = ch_inner * inner_h + 1;
    int inner_margin_x = (interior_w - inner_total_w) / 2;
    int inner_margin_y = (interior_h - inner_total_h) / 2;
    if (inner_margin_x < 0) inner_margin_x = 0;
    if (inner_margin_y < 0) inner_margin_y = 0;

    WallStyle outer_st = outer_style_for(s->current_glyph);
    WallStyle inner_st = inner_style_for(s->current_glyph);
    int outer_pair = PAIR_RAMP_BASE + OUTER_RAMP;
    int inner_pair = PAIR_RAMP_BASE + INNER_RAMP;

    /* Inner mazes first. We always attempt to draw — if the inner
     * maze slightly overflows its outer cell (because inner cell size
     * had to be clamped to the minimum), the outer maze drawn next
     * overdraws the overflow at the boundary. The renderer's bounds
     * check inside draw_wall_cell handles screen-edge overflow.
     *
     * `no_dim=true` keeps inner walls at A_NORMAL minimum so they
     * remain visible even where the brightness fBm field is at its
     * dim end. */
    for (int oy = 0; oy < outer_h; oy++) {
        for (int ox = 0; ox < outer_w; ox++) {
            int idx = oy * outer_w + ox;
            if (idx >= s->mom.outer_count) break;
            const Maze *inner = &s->mom.inner[idx];
            int igx = gx + ox * cw_outer + 1 + inner_margin_x;
            int igy = gy + oy * ch_outer + 1 + inner_margin_y;
            render_maze(sc, s, inner, igx, igy,
                        cw_inner, ch_inner,
                        inner_st, inner_pair, A_NORMAL, true);
        }
    }

    /* Outer maze on top — full brightness modulation (no_dim=false)
     * so the outer-scale animation reads. */
    render_maze(sc, s, &s->mom.outer, gx, gy, cw_outer, ch_outer,
                outer_st, outer_pair, A_BOLD, false);

    /* Reseed flash overlay. */
    if (s->flash_t > 0.05f) {
        int seed = (int)(s->time_secs * 1000.0f);
        attron(COLOR_PAIR(PAIR_FLASH) | A_BOLD);
        for (int sy = 2; sy < sc->rows - 1; sy += 2) {
            for (int sx = 0; sx < sc->cols; sx += 2) {
                if (((sx ^ sy ^ seed) & 7) == 0)
                    mvaddch(sy, sx, '*');
            }
        }
        attroff(COLOR_PAIR(PAIR_FLASH) | A_BOLD);
    }
}

static void screen_draw(Screen *sc, const Scene *s,
                        double fps, int sim_fps)
{
    erase();
    scene_draw(sc, s);

    const PatternCfg *cfg = &PATTERN_CFG[s->current_pattern];
    const char *state_str = s->paused ? "PAUSED" : "DRIFT ";

    /* Row 0 right — primary status. */
    char buf[HUD_COLS + 1];
    snprintf(buf, sizeof buf,
             " %5.1f fps  %3d Hz  %s  speed:%-3d ",
             fps, sim_fps, state_str, s->speed);
    int hx = sc->cols - (int)strlen(buf);
    if (hx < 0) hx = 0;
    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(0, hx, "%s", buf);
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);

    /* Row 0 left — title. */
    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(0, 1, " MAZE OF MAZE ");
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);

    /* Row 1 — pattern + glyph + theme + sizes + ramp swatch. */
    int x = 1;
    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(1, x, " pattern:%-7s ", pattern_name(s->current_pattern));
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    x += 18;

    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(1, x, " glyph:%-5s ", glyph_set_name(s->current_glyph));
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    x += 14;

    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(1, x, " theme:%-8s ", themes[s->current_theme].name);
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    x += 17;

    attron(COLOR_PAIR(PAIR_HUD));
    mvprintw(1, x, " ramp:");
    attroff(COLOR_PAIR(PAIR_HUD));
    x += 6;
    static const char ramp_glyphs[8] = { '`', '.', ',', ':', '-', 'o', '#', '@' };
    for (int i = 0; i < 8; i++) {
        int p = PAIR_RAMP_BASE + i;
        attron(COLOR_PAIR(p) | A_BOLD);
        mvaddch(1, x, (chtype)(unsigned char)ramp_glyphs[i]);
        attroff(COLOR_PAIR(p) | A_BOLD);
        x++;
    }
    attron(COLOR_PAIR(PAIR_HUD));
    mvprintw(1, x,
             "  outer:%dx%d  inner:%dx%d ",
             cfg->outer_w, cfg->outer_h,
             cfg->inner_w, cfg->inner_h);
    attroff(COLOR_PAIR(PAIR_HUD));

    /* Bottom hint. */
    attron(COLOR_PAIR(PAIR_HINT) | A_BOLD);
    mvprintw(sc->rows - 1, 0,
             " n/p:pattern  g/G:glyph  t/T:theme  +/-:drift  spc:pause  r:reseed  q:quit ");
    attroff(COLOR_PAIR(PAIR_HINT) | A_BOLD);
}

static void screen_present(void) { wnoutrefresh(stdscr); doupdate(); }

/* ===================================================================== */
/* §8  app                                                                */
/* ===================================================================== */

typedef struct {
    Scene                 scene;
    Screen                screen;
    int                   sim_fps;
    volatile sig_atomic_t running;
    volatile sig_atomic_t need_resize;
} App;

static App g_app;

static void on_exit_signal  (int sig) { (void)sig; g_app.running     = 0; }
static void on_resize_signal(int sig) { (void)sig; g_app.need_resize = 1; }
static void cleanup(void)             { endwin(); }

static void app_do_resize(App *app)
{
    screen_resize(&app->screen);
    app->need_resize = 0;
}

static bool app_handle_key(App *app, int ch)
{
    Scene *s = &app->scene;
    switch (ch) {
    case 'q': case 'Q': case 27 /* ESC */: return false;
    case ' ':           s->paused = !s->paused;                       break;
    case 'r': case 'R': scene_reseed(s);                               break;

    case '=': case '+':
        if (s->speed < SPEED_MAX) s->speed *= 2;
        if (s->speed > SPEED_MAX) s->speed  = SPEED_MAX;
        break;
    case '-':
        s->speed /= 2;
        if (s->speed < SPEED_MIN) s->speed  = SPEED_MIN;
        break;

    case ']':
        app->sim_fps += SIM_FPS_STEP;
        if (app->sim_fps > SIM_FPS_MAX) app->sim_fps = SIM_FPS_MAX;
        break;
    case '[':
        app->sim_fps -= SIM_FPS_STEP;
        if (app->sim_fps < SIM_FPS_MIN) app->sim_fps = SIM_FPS_MIN;
        break;

    case 't':
        s->current_theme = (s->current_theme + 1) % N_THEMES;
        theme_apply(s->current_theme);
        break;
    case 'T':
        s->current_theme = (s->current_theme + N_THEMES - 1) % N_THEMES;
        theme_apply(s->current_theme);
        break;

    case 'n': case 'N':
        s->current_pattern = (Pattern)(((int)s->current_pattern + 1) % N_PATTERNS);
        scene_regenerate(s);
        break;
    case 'p': case 'P':
        s->current_pattern = (Pattern)(((int)s->current_pattern + N_PATTERNS - 1) % N_PATTERNS);
        scene_regenerate(s);
        break;

    case 'g':
        s->current_glyph = (GlyphSet)(((int)s->current_glyph + 1) % N_GLYPH_SETS);
        break;
    case 'G':
        s->current_glyph = (GlyphSet)(((int)s->current_glyph + N_GLYPH_SETS - 1) % N_GLYPH_SETS);
        break;

    default: break;
    }
    return true;
}

int main(void)
{
    srand((unsigned int)(clock_ns() & 0xFFFFFFFF));
    atexit(cleanup);
    signal(SIGINT,   on_exit_signal);
    signal(SIGTERM,  on_exit_signal);
    signal(SIGWINCH, on_resize_signal);

    App *app     = &g_app;
    app->running = 1;
    app->sim_fps = SIM_FPS_DEFAULT;

    screen_init(&app->screen);
    scene_init(&app->scene);

    int64_t frame_time  = clock_ns();
    int64_t sim_accum   = 0;
    int64_t fps_accum   = 0;
    int     frame_count = 0;
    double  fps_display = 0.0;

    while (app->running) {

        if (app->need_resize) {
            app_do_resize(app);
            frame_time = clock_ns();
            sim_accum  = 0;
        }

        int64_t now = clock_ns();
        int64_t dt  = now - frame_time;
        frame_time  = now;
        if (dt > 100 * NS_PER_MS) dt = 100 * NS_PER_MS;

        int64_t tick_ns = TICK_NS(app->sim_fps);
        float   dt_sec  = (float)tick_ns / (float)NS_PER_SEC;

        sim_accum += dt;
        while (sim_accum >= tick_ns) {
            scene_tick(&app->scene, dt_sec);
            sim_accum -= tick_ns;
        }

        frame_count++;
        fps_accum += dt;
        if (fps_accum >= FPS_UPDATE_MS * NS_PER_MS) {
            fps_display = (double)frame_count
                        / ((double)fps_accum / (double)NS_PER_SEC);
            frame_count = 0;
            fps_accum   = 0;
        }

        int64_t elapsed = clock_ns() - frame_time + dt;
        clock_sleep_ns(NS_PER_SEC / 60 - elapsed);

        screen_draw(&app->screen, &app->scene, fps_display, app->sim_fps);
        screen_present();

        int ch = getch();
        if (ch != ERR && !app_handle_key(app, ch))
            app->running = 0;
    }

    screen_free(&app->screen);
    return 0;
}
