/* Copyright (c) 2026 Tamilselvan R  SPDX-License-Identifier: MIT */
/*
 * maze_of_maze.c
 *   — A maze whose every cell contains its own smaller maze. Two
 *     levels of recursive maze nesting, each generated by an
 *     independent depth-first random-walk (the "recursive backtracker"
 *     algorithm). The outer-maze cells are rendered with bold walls;
 *     the inner mazes inside each cell are rendered with thinner
 *     walls and a different colour tint so the two scales remain
 *     visually distinct.
 *
 * DEMO: A grid of "rooms" fills the screen — that's the OUTER maze,
 *       carved by removing walls between adjacent cells until every
 *       room is reachable from every other. Inside each room, look
 *       closely: a complete SMALLER maze fills the room's interior,
 *       with its own walls and own corridors. Each inner maze is
 *       independently generated, so no two rooms have the same
 *       inner layout.
 *
 *       PATTERN (n / N) — controls the cell counts at each level:
 *
 *         CLASSIC   6×3 outer rooms, each holding a 6×4 inner maze
 *         WIDE      4×2 outer (big rooms), each with 10×6 inner
 *                   maze (most detail per room)
 *         DENSE     8×4 outer (small rooms), each with 4×3 inner
 *                   (most rooms total, sparser inner)
 *         EVEN      5×3 outer × 8×5 inner — balanced
 *
 *       GLYPH (g / G) — wall rendering style:
 *
 *         LINES     classic ASCII '+' '-' '|' walls (thin)
 *         BLOCKS    '#' walls everywhere (thick / solid)
 *         MIXED     outer walls '#', inner walls '+' '-' '|'
 *                   — exaggerates the visual hierarchy between scales
 *
 *       'r' reseeds — fresh outer maze + fresh inner mazes for every
 *       outer cell. Brightness drift continues smoothly.
 *
 * Study alongside:
 *   ../generational/wfc_showcase.c
 *      — wave-function-collapse: a constraint-based "maze-like"
 *        layout solver. The DFS carving here is simpler but
 *        guaranteed to make a perfect maze (single path between
 *        any two cells).
 *   ../patterns/wang_tiles.c
 *      — also tiling on a grid, but with edge-colour adjacency
 *        instead of carved passages.
 *
 * Section map (re-cut into single-responsibility layers — see ARCHITECTURE):
 *   §1 config      — immutable data tables & constants (no functions)
 *   §2 logic       — pure decisions: hash, perlin/fBm, brightness sample,
 *                    pattern/glyph/style selectors (no mutation, no I/O)
 *   §3 performance — monotonic timer + sleep
 *   §4 platform    — ncurses colour setup (HUD reserved + 10 themes)
 *   §5 generation  — Maze struct, DFS carve, maze-of-maze + noise basis;
 *                    runs on init / reseed / pattern change only
 *   §6 effects     — per-tick cosmetic advance (brightness drift, flash)
 *   §7 render      — outer + inner mazes → screen, brightness-modulated
 *   §8 app         — signals, resize, fixed-step main loop, event routing
 *
 * Keys:
 *   q / ESC    quit
 *   space      pause / resume light-field drift
 *   r          reseed (all mazes regenerated)
 *   n / N      next pattern
 *   p / P      previous pattern
 *   g / G      next / previous glyph set
 *   t / T      next / previous theme
 *   + / =      faster light drift
 *   -          slower
 *   ] / [      raise / lower tick Hz
 *
 * Build:
 *   gcc -std=c11 -O2 -Wall -Wextra \
 *     procedural/patterns/maze_of_maze.c \
 *     -o maze_of_maze -lncurses -lm
 */

/* ── CONCEPTS ──────────────────────────────────────────────────────────── *
 *
 * Algorithm      : Two pieces composed together.
 *
 *                  (1) RECURSIVE BACKTRACKER (DFS) maze carving.
 *                      Start with a grid where every cell has all
 *                      four walls. Mark cell (0, 0) visited; from
 *                      each visited cell, pick a random unvisited
 *                      neighbour, knock down the shared wall, recurse
 *                      into the neighbour. When stuck, backtrack.
 *                      Result: a "perfect" maze — exactly one path
 *                      between any two cells, no loops, every cell
 *                      reachable. The simplest of the classical
 *                      maze algorithms; produces long winding
 *                      corridors and few short dead-ends.
 *
 *                  (2) NESTING. After carving the OUTER maze (size
 *                      W_outer × H_outer), generate W_outer ·
 *                      H_outer INDEPENDENT inner mazes (size
 *                      W_inner × H_inner each), each with its own
 *                      seed. When rendering, each outer cell
 *                      occupies a rectangular block on screen; the
 *                      block's interior holds that cell's inner
 *                      maze, drawn at smaller scale and dimmer
 *                      colour. The result is a maze of mazes —
 *                      two layers of structure visible
 *                      simultaneously.
 *
 *                  Plus a slow-drifting fBm BRIGHTNESS field
 *                  (same trick as truchet_tiles.c / wang_tiles.c)
 *                  modulates per-cell A_DIM/A_NORMAL/A_BOLD over the
 *                  static maze layout, giving subtle motion.
 *
 * Data-structure : Maze { w, h, walls[]:uint8 } — one byte per cell
 *                  encoding 4 wall bits (N=1, E=2, S=4, W=8). Outer
 *                  maze + up to MAX_OUTER_CELLS inner mazes
 *                  (MAX_OUTER_CELLS = 64). Total memory: a few
 *                  kilobytes.
 *
 * Rendering      : ASCII only. For each cell, draw the present walls
 *                  as horizontal/vertical line segments between
 *                  cells, with intersections at corners drawn as
 *                  '+'. Adjacent cells share walls; double-drawing
 *                  is harmless (idempotent same-colour write).
 *                  Outer walls drawn LAST so they overlay the inner
 *                  mazes at outer-cell boundaries.
 *
 * Performance    : Generation is O(cells) per maze. With pattern
 *                  CLASSIC: 18 outer cells + 18 inner mazes × 24
 *                  inner cells = ~450 cells total carved. Runs in
 *                  microseconds on regen.
 *                  Per-frame render: ~10 K wall-cell mvaddch calls
 *                  + one fBm sample per cell for brightness. About
 *                  10 % of a CPU core at 240×80 × 60 fps.
 *
 * References     :
 *   CONCEPTS — maze carving, DFS, spanning trees
 *   • Buck, Jamis — "Mazes for Programmers" (Pragmatic Bookshelf,
 *     2015). The definitive practical guide; the recursive
 *     backtracker (this file's dfs_carve) is Chapter 5, and the
 *     spanning-tree framing of "perfect maze" runs throughout.
 *   • Cormen, Leiserson, Rivest, Stein — "Introduction to
 *     Algorithms" (4th ed., MIT Press, 2022). §20 Depth-First
 *     Search and §21 Minimum Spanning Trees — the graph-theory
 *     foundation: a perfect maze IS a spanning tree of the grid
 *     graph, and DFS carving is a randomized spanning-tree walk.
 *   • Pullen, Walter — "Think Labyrinth: Maze Algorithms" — the
 *     most complete catalogue of carving algorithms and their
 *     bias/texture trade-offs. http://www.astrolog.org/labyrnth/algrithm.htm
 *   • Wikipedia — "Maze generation algorithm" (quick survey) and
 *     "Depth-first search" (the traversal dfs_carve specializes).
 *     https://en.wikipedia.org/wiki/Maze_generation_algorithm
 *
 *   RENDERING — the drifting brightness field + grid drawing
 *   • Perlin, Ken — "Improving Noise", SIGGRAPH 2002. The exact
 *     gradient-noise variant implemented here in perlin2d()/grad2()
 *     (improved fade curve 6t^5-15t^4+10t^3, 256-entry perm table).
 *   • Ebert, Musgrave, Peachey, Perlin, Worley — "Texturing &
 *     Modeling: A Procedural Approach" (3rd ed., Morgan Kaufmann,
 *     2003). Ch. 2–3 derive fractional Brownian motion (fbm2's
 *     octave/amplitude/lacunarity summation that drives the
 *     A_DIM/A_NORMAL/A_BOLD brightness modulation).
 *   • Patel, Amit (Red Blob Games) — "Making maps with noise
 *     functions" and the grid/maze guides. Practical reference for
 *     using fBm as a spatial field over a cell grid and for the
 *     screen-coordinate maze rendering done in render_maze().
 *     https://www.redblobgames.com/maps/terrain-from-noise/
 *
 * ─────────────────────────────────────────────────────────────────────── */

/* ── MENTAL MODEL ─────────────────────────────────────────────────────── *
 *
 * CORE IDEA
 * ─────────
 * A perfect maze is a SPANNING TREE on the grid graph: every cell is
 * connected, exactly one path between any two cells, no loops. The
 * recursive backtracker builds one by depth-first random walk — at
 * each step you knock down a wall to a fresh neighbour and step in;
 * when no fresh neighbour exists, you back up. The result is a maze
 * with long meandering corridors. To get a MAZE OF MAZES, take that
 * algorithm and run it not once but TWICE per scale — once for the
 * outer big maze, then once independently for every cell of that
 * maze. Each cell becomes its own little maze, and you can look at
 * the big picture or zoom into any room and find more structure.
 *
 * HOW TO THINK ABOUT IT
 * ─────────────────────
 * Imagine a hotel where every room is itself a hotel. You walk down
 * the long corridor of the OUTER hotel, picking doors at random.
 * Open one — inside is not a bedroom but another corridor with more
 * doors. Open one of THOSE — and inside is yet another (smaller)
 * room. The structure repeats. From the lobby you can in principle
 * reach any inner room of any outer room, but you have to navigate
 * the outer maze first and then the inner maze second. Each outer
 * room has its OWN floor plan; no two are the same.
 *
 * The fact that BOTH levels are MAZES (perfect, every cell reachable)
 * is just the Recursive Backtracker applied twice. The interesting
 * thing is that the two levels are generated independently — outer
 * and inner have no relationship — yet the visual whole reads as a
 * single coherent fractal-ish structure because the eye groups
 * adjacent cells naturally.
 *
 * ALGORITHM IN STEPS
 * ──────────────────
 *  1. CHOOSE SIZES. Outer maze is W_outer × H_outer; each inner
 *     maze is W_inner × H_inner. Pattern selects these.
 *  2. CARVE OUTER. dfs_carve(outer, 0, 0):
 *     a. Mark current cell visited.
 *     b. Shuffle the 4 directions {N, E, S, W} with a deterministic
 *        seeded RNG.
 *     c. For each direction in shuffled order:
 *          neighbour = step in that direction
 *          if neighbour is in-bounds and unvisited:
 *            remove the wall between current and neighbour
 *            recurse into neighbour
 *  3. CARVE EACH INNER. For (ox, oy) in [0..W_outer)×[0..H_outer):
 *       seed_inner = base_seed ^ hash(ox, oy)
 *       dfs_carve(inner[ox, oy], 0, 0)  with this seed
 *  4. EACH FRAME:
 *       a. Advance brightness wind.
 *       b. Compute outer cell screen size = total_screen / (W_outer, H_outer)
 *       c. Compute inner cell screen size = (outer cell − 1) / (W_inner, H_inner)
 *       d. For each outer cell, render its inner maze inside the
 *          outer cell's interior region.
 *       e. Render the outer maze on top (its walls overdraw the
 *          inner-maze walls at outer-cell boundaries).
 *       f. For each wall cell drawn, sample the fBm brightness field
 *          and choose A_DIM / A_NORMAL / A_BOLD.
 *  5. HUD on top.
 *
 * KEY FORMULAS
 * ────────────
 *  Wall bit encoding (per cell):
 *    bit 0 (1) = North wall
 *    bit 1 (2) = East wall
 *    bit 2 (4) = South wall
 *    bit 3 (8) = West wall
 *    initial state: all walls present (0xF)
 *
 *  DFS carve, removing wall between cell (x, y) and neighbour at
 *  direction d:
 *    walls[y][x]    &= ~(1 << d)            // remove our wall
 *    walls[ny][nx]  &= ~(1 << OPPOSITE[d])  // remove their wall
 *
 *  Direction tables (clockwise from N):
 *    DX = {  0,  1,  0, -1 }
 *    DY = { -1,  0,  1,  0 }
 *    OPPOSITE = { 2, 3, 0, 1 }
 *
 *  Outer cell screen size:
 *    cw_outer = total_screen_w / W_outer
 *    ch_outer = total_screen_h / H_outer
 *
 *  Inner cell screen size (within an outer cell, leaving 1 cell for
 *  the outer wall on each side):
 *    cw_inner = (cw_outer - 1) / W_inner
 *    ch_inner = (ch_outer - 1) / H_inner
 *
 *  Brightness modulation (per wall cell):
 *    b = fbm2(sx · BSC_X + wind_x, sy · BSC_Y · ASPECT_Y)
 *    attr = (b > 0.65) ? A_BOLD : (b < 0.35) ? A_DIM : A_NORMAL
 *
 * EDGE CASES TO WATCH
 * ───────────────────
 *  • DFS RECURSION DEPTH. Worst case is the longest possible
 *    Hamiltonian path through the maze grid — bounded by
 *    W_outer · H_outer (outer) or W_inner · H_inner (inner). With
 *    caps at 16 × 16 = 256 cells, recursion depth ≤ 256. Each stack
 *    frame is ~50 bytes; total ≤ 13 KB stack, comfortably within
 *    default thread stacks.
 *
 *  • SHARED WALL BETWEEN ADJACENT CELLS. Each interior wall belongs
 *    to TWO cells. The renderer draws BOTH cells' walls, so the
 *    interior wall gets drawn twice (idempotent, same colour).
 *    Cleaner alternatives (skip duplicates) would track a hash set
 *    of edges — not worth the complexity.
 *
 *  • OUTER CELL VS SCREEN BOUNDARY. The outermost edge of the outer
 *    maze (row 0 north, column 0 west, etc.) has all-cells-have-
 *    that-wall-set, so the outer maze always has a complete
 *    rectangular border. Good for visual cohesion.
 *
 *  • INNER MAZE FITTING. If the inner cell size rounds down to <2
 *    in either axis, the inner maze becomes invisible (walls on top
 *    of walls). Cap MIN_CELL_W=2, MIN_CELL_H=1 in the pattern
 *    config; if a pattern's inner maze can't fit at the current
 *    screen size, the renderer silently skips inner-maze drawing
 *    inside that outer cell.
 *
 *  • DETERMINISTIC SEED PER INNER MAZE. We compute each inner
 *    maze's seed as `base_seed ^ hash3(ox, oy, salt)`, so the same
 *    base_seed always produces the same maze of mazes. Reseeding
 *    with 'r' picks a new base_seed — every inner maze regenerates.
 *
 *  • OUTER WALLS OVER INNER MAZES. We render inner mazes FIRST,
 *    then outer mazes ON TOP. Otherwise outer-cell-boundary walls
 *    might be eaten by inner mazes that happen to draw a passage
 *    near the boundary.
 *
 *  • ASPECT NOT CORRECTED FOR INNER. We don't try to make inner
 *    cells visually square — they tend to be tall and thin in
 *    horizontal-maze visualisation. ASCII cell aspect (2:1) makes
 *    the issue worse but it's mostly OK.
 *
 * HOW TO VERIFY
 * ─────────────
 *  • Pause (space). Brightness freezes. Resume: drift continues.
 *
 *  • Press 'r'. The flash fires and ALL mazes change (outer + every
 *    inner). The pattern stays the same — rooms remain in the same
 *    grid arrangement — but the carved corridors all randomise.
 *
 *  • CLASSIC pattern. Count outer rooms: 6 × 3 = 18. Trace the outer
 *    maze: every room should be reachable from every other through
 *    door openings (cells where the outer wall is absent). Inside
 *    each room, the inner maze should also be a perfect maze
 *    (every inner cell reachable from every other inner cell of
 *    THE SAME ROOM).
 *
 *  • Switch to WIDE. Now there are only 4 × 2 = 8 outer rooms but
 *    each is large and contains a 10 × 6 = 60-cell inner maze. The
 *    fine detail per room is visibly higher than CLASSIC.
 *
 *  • Switch to DENSE. 32 outer rooms, but each inner maze is only
 *    4 × 3 = 12 cells — rooms read as small "chunks" of layout.
 *
 *  • Glyph cycle (g). The maze layouts don't change; only the wall
 *    rendering does. LINES gives clean ASCII art; BLOCKS makes a
 *    chunkier look; MIXED visually separates the outer (#) from
 *    the inner (+ - |) layer.
 *
 *  • Inner mazes ARE INDEPENDENT. Two adjacent rooms have unrelated
 *    inner layouts — the inner walls do NOT line up across the
 *    outer-room boundary. (An interesting variant would be to align
 *    them; we don't, on purpose, for visual variety.)
 *
 * ─────────────────────────────────────────────────────────────────────── */

/* ── ARCHITECTURE (layer separation) ──────────────────────────────────── *
 *
 * This file was re-cut from a single combined flow into single-
 * responsibility layers. Each top-level §-section maps to exactly one
 * layer. "Mutates" is the ONLY state a layer is permitted to write;
 * everything else it reads. (Const-pointer signatures that would make
 * this read/mutate split self-evident are deferred to step 5, where the
 * types exist to express it — they are not faked on the current data.)
 *
 *   LAYER         SECTION          MUTATES
 *   ───────────   ──────────────   ─────────────────────────────────────
 *   CONFIG        §1 config        nothing — compile-time data only
 *   LOGIC         §2 logic         nothing — pure functions, no I/O
 *   PERFORMANCE   §3 performance   nothing — wall-clock read + sleep
 *   PLATFORM      §4 platform      ncurses colour pairs (init / theme key)
 *   GENERATION    §5 generation    perm[]; Maze/MazeOfMaze cells; Scene
 *                                  (seed, mom, bright.flash_t) EVENT/INIT
 *   EFFECTS       §6 effects       Scene.bright (time_secs, wind_x,
 *                                  flash_t) — the only per-tick advance
 *   RENDER        §7 render        screen cells only — never Scene
 *   APP           §8 app           App.running/need_resize/sim_fps + the
 *                                  frame timers; routes user/OS events
 *
 * LOGIC is provably uncorruptable by EFFECTS or RENDER: it mutates nothing
 * and does no I/O, so deleting or reordering any render/effects code
 * cannot change a LOGIC result. (perlin2d/fbm2 READ the global perm[]
 * table that §5 builds, but never write it — sampling stays pure.)
 *
 * SIMULATION — absent. The maze layout never evolves; once carved it is a
 *   static artifact. The only state that advances per tick is the cosmetic
 *   brightness field, which is EFFECTS, not simulation. No SIMULATION
 *   section exists rather than a hollow one.
 *
 * DELAYS — trivial. No holds or countdown timers exist; a single `paused`
 *   flag (toggled by the user) gates the EFFECTS advance, and the reseed
 *   flash is a continuous decay (EFFECTS), not a timed hold. Folded into
 *   §6 rather than given its own section.
 *
 * PER-TICK COMBINE ORDER — the ONE place state advances is the §8 main
 * loop; nothing else advances simulation state:
 *   1. PERFORMANCE  measure dt, clamp to 100 ms, accumulate
 *   2. EFFECTS      while (accum >= TICK) scene_tick()   ← only advance
 *   3. PERFORMANCE  fps accounting + sleep to the frame cap
 *   4. RENDER       screen_draw() → present   (reads state, writes screen)
 *
 * NOT PART OF THE TICK — user/OS events mutate state directly, OUTSIDE the
 * accumulator: key handling (app_handle_key → scene_reseed / regenerate /
 * theme_apply / pattern+glyph+speed changes) and resize (app_do_resize).
 * These reach GENERATION/PLATFORM only, never EFFECTS.
 * ─────────────────────────────────────────────────────────────────────── */

#define _POSIX_C_SOURCE 200809L

#include <math.h>
#include <ncurses.h>
#include <signal.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* ===================================================================== */
/* §1  config       — immutable data tables & constants (no functions) */
/* ===================================================================== */

enum {
    SIM_FPS_MIN         =  10,
    SIM_FPS_DEFAULT     =  60,
    SIM_FPS_MAX         = 240,
    SIM_FPS_STEP        =  10,

    SPEED_MIN           =   1,
    SPEED_DEF           =   8,
    SPEED_MAX           =  64,

    HUD_COLS            =  80,
    FPS_UPDATE_MS       = 500,

    /* Per-maze cell limits.  Outer max 16×8 = 128 cells; inner max
     * 16×8 = 128. Generous bounds; patterns use far less. */
    MAX_MAZE_W          =  16,
    MAX_MAZE_H          =   8,
    MAX_MAZE_CELLS      = MAX_MAZE_W * MAX_MAZE_H,

    /* Outer cell limit for the inner-maze pool. With a 16×8 outer
     * maze, that's 128 inner mazes. */
    MAX_OUTER_CELLS     = MAX_MAZE_W * MAX_MAZE_H,

    /* Color pair indices.  PAIR_HUD/PAIR_HINT reserved per CLAUDE.md. */
    PAIR_HUD            =   1,
    PAIR_HINT           =   2,
    PAIR_RAMP_BASE      =   3,    /* +0..+7 = 8 brightness/colour tints */
    PAIR_FLASH          =  11,
};

#define NS_PER_SEC      1000000000LL
#define NS_PER_MS          1000000LL
#define TICK_NS(f)      (NS_PER_SEC / (f))

#define ASPECT_Y_F           2.0f

/* Brightness fBm parameters — slow drift over the static mazes. */
#define BRIGHT_SCALE_X       0.040f
#define BRIGHT_SCALE_Y       0.080f
#define WIND_X_BASE          3.0f
#define FBM_OCTAVES          3

/* Wall bit positions. */
#define WALL_N               0x1u
#define WALL_E               0x2u
#define WALL_S               0x4u
#define WALL_W               0x8u

/* Ramp slot for outer vs inner walls — both chosen from the BRIGHT
 * half of the ramp so the inner stays visible even when the brightness
 * fBm field is at its dim end. INNER_RAMP=5 (was 3) ensures the
 * inner walls don't disappear; OUTER_RAMP=7 keeps the outer
 * dominant. Inner walls additionally never go to A_DIM (see the
 * `no_dim` flag in draw_wall_cell) — they're always at least
 * A_NORMAL so the inner-maze structure is always readable. */
#define OUTER_RAMP           7
#define INNER_RAMP           5

/* Layout geometry — all in terminal character cells. */
enum {
    HUD_TOP_ROWS   = 2,   /* rows 0-1 reserved for the HUD; maze starts row 2  */
    MIN_OUTER_CW   = 6,   /* floor on an outer cell's width  (keep it usable)  */
    MIN_OUTER_CH   = 4,   /* floor on an outer cell's height                   */
    MIN_INNER_CELL = 2,   /* floor on an inner cell, both axes; <2 = invisible */
};

/* Brightness -> ncurses intensity thresholds, on the [0,1] fBm sample. */
#define BRIGHT_HI            0.65f   /* above this -> A_BOLD                    */
#define BRIGHT_LO            0.35f   /* below this -> A_DIM (unless no_dim)     */

/* Reseed flash overlay. */
#define FLASH_VISIBLE_MIN    0.05f   /* drop the overlay once the envelope dips below */
#define FLASH_PHASE_RATE  1000.0f    /* time_secs -> integer sparkle phase, per second */
#define FLASH_GLYPH          '*'
enum { FLASH_SPARSITY_MASK = 7 };    /* (x^y^phase)&mask==0 -> ~1 cell in 8 sparkles  */

/* Maze carving. */
#define ALL_WALLS            0xFu        /* every wall up — a cell's pre-carve state */
#define KNUTH_HASH32  2654435761u        /* round(2^32 / phi); multiplicative seed mix */
#define INNER_SEED_SALT      0xBEEF      /* salts each room's inner-maze seed         */

/* Linear congruential generator step (Numerical Recipes constants) — the
 * per-maze shuffle RNG: next = state * LCG_MUL + LCG_ADD. */
#define LCG_MUL       1664525u
#define LCG_ADD    1013904223u

/* Main-loop timing. */
enum {
    MAX_FRAME_MS = 100,   /* dt clamp: caps catch-up after a stall (no spiral) */
    RENDER_FPS   =  60,   /* render frame cap, independent of the sim tick Hz  */
};

/*
 * Pattern — a named preset in the maze-of-maze size trade-space.
 *
 * Nesting has two free scales: how many OUTER rooms tile the screen, and
 * how many INNER cells fill each room. They trade against each other — on a
 * fixed screen, more rooms makes every room (and its inner maze) smaller.
 * These four presets sample useful corners of that space so the user flips
 * between "few big detailed rooms" and "many small coarse rooms" with one
 * key instead of tuning four numbers. The value indexes PATTERN_CFG[].
 */
typedef enum {
    PATTERN_CLASSIC = 0,   /* 6x3 rooms / 6x4 inner — balanced default         */
    PATTERN_WIDE    = 1,   /* 4x2 rooms / 10x6 inner — most detail per room    */
    PATTERN_DENSE   = 2,   /* 8x4 rooms / 4x3 inner — most rooms, sparse inner */
    PATTERN_EVEN    = 3,   /* 5x3 rooms / 8x5 inner — even split of both       */
    N_PATTERNS      = 4,   /* element count; also the modulus for n/p cycling  */
} Pattern;

/*
 * PatternCfg — the concrete cell counts behind one Pattern (one row of
 * PATTERN_CFG[]). All four numbers are in MAZE CELLS, never screen
 * characters: the on-screen pixel size of a cell is derived per-frame in
 * scene_draw() from the live terminal size, so one config reads correctly
 * at any window size. Each axis is clamped to MAX_MAZE_W/H (the Maze.walls[]
 * capacity) before use in mom_generate().
 */
typedef struct {
    int outer_w, outer_h;   /* outer grid — rooms across / down               */
    int inner_w, inner_h;   /* inner grid inside each room — cells across/down */
} PatternCfg;

static const PatternCfg PATTERN_CFG[N_PATTERNS] = {
    /*               outer  inner */
    [PATTERN_CLASSIC] = { 6, 3,   6, 4 },
    [PATTERN_WIDE   ] = { 4, 2,  10, 6 },
    [PATTERN_DENSE  ] = { 8, 4,   4, 3 },
    [PATTERN_EVEN   ] = { 5, 3,   8, 5 },
};


/*
 * GlyphSet — which ASCII wall glyphs to draw with. PURE presentation: the
 * carved maze is byte-for-byte identical across all three; only
 * outer_style_for()/inner_style_for() turn this into a WallStyle. MIXED
 * draws the outer level thick and the inner level thin on purpose, to
 * exaggerate the two-scale hierarchy the eye is meant to read. ASCII-only
 * per the project rule (no Unicode box-drawing — renders the same on every
 * locale).
 */
typedef enum {
    GLYPH_LINES  = 0,   /* '-' '|' '+' at both levels — clean line art       */
    GLYPH_BLOCKS = 1,   /* '#' everywhere — chunky / solid                   */
    GLYPH_MIXED  = 2,   /* outer '#', inner '-|+' — maximal scale contrast   */
    N_GLYPH_SETS = 3,   /* element count; modulus for g/G cycling            */
} GlyphSet;

/*
 * WallStyle — the resolved glyph triple one render pass stamps for one
 * level (outer or inner). outer_style_for()/inner_style_for() collapse the
 * user's GlyphSet down to this, so render_maze() never branches on the mode
 * — it just writes these three glyphs. Three is exactly what a grid drawing
 * needs: a run in each axis plus the lattice crossings.
 */
typedef struct {
    char h_wall;     /* horizontal wall run (a cell's north / south edge)    */
    char v_wall;     /* vertical wall run (a cell's east / west edge)        */
    char corner;     /* glyph at every grid intersection (drawn last, on top)*/
} WallStyle;

static const WallStyle STYLE_LINES  = { '-', '|', '+' };
static const WallStyle STYLE_BLOCKS = { '#', '#', '#' };

/*
 * Theme — one named 256-colour palette. The renderer never names a raw
 * colour; it indexes this palette through ncurses colour pairs, so
 * re-tinting the entire demo is a single theme swap (theme_apply() reloads
 * the pairs on a t/T keypress).
 *
 * Every value sits in the BRIGHT half of the xterm-256 cube on purpose: a
 * dim wall (A_DIM) on a bottom-of-cube colour is invisible on a black
 * terminal. The theme's character comes from the RELATIVE gradient, not
 * absolute darkness. See "Theme Palette Brightness" / COLOR.md.
 */
typedef struct {
    const char *name;     /* HUD label shown while cycling with t/T           */
    short       ramp[8];  /* brightness ramp, dark ramp[0] -> bright ramp[7]. */
                          /*   Walls read fixed slots (INNER_RAMP/OUTER_RAMP);*/
                          /*   the fBm field only shifts A_DIM/BOLD on top.   */
} Theme;

#define N_THEMES 10

static const Theme themes[N_THEMES] = {
    /* name       0    1    2    3    4    5    6    7 */
    { "DEFAULT",{ 24,  31,  39,  70,  76, 137, 215, 230 } },
    { "MATRIX", { 28,  34,  40,  46,  76, 118, 154, 192 } },
    { "NOVA",   { 60,  91, 134, 165, 207, 213, 219, 231 } },
    { "MONO",   {240, 243, 245, 247, 249, 251, 253, 255 } },
    { "OCEAN",  { 24,  25,  31,  38,  45,  51, 117, 195 } },
    { "FIRE",   { 88, 124, 130, 166, 202, 208, 214, 226 } },
    { "EARTH",  { 94, 130, 137, 173, 179, 215, 222, 230 } },
    { "FOREST", { 28,  34,  40,  70,  76, 112, 156, 192 } },
    { "DESERT", {130, 137, 143, 173, 179, 215, 222, 229 } },
    { "ARCTIC", { 24,  31,  67, 110, 117, 153, 195, 231 } },
};

/* ===================================================================== */
/* §2  logic        — pure decisions: no mutation, no I/O; readable alone */
/* ===================================================================== */

static const char *pattern_name(Pattern p)
{
    switch (p) {
    case PATTERN_CLASSIC: return "CLASSIC";
    case PATTERN_WIDE:    return "WIDE   ";
    case PATTERN_DENSE:   return "DENSE  ";
    case PATTERN_EVEN:    return "EVEN   ";
    default:              return "?      ";
    }
}

static const char *glyph_set_name(GlyphSet g)
{
    switch (g) {
    case GLYPH_LINES:  return "lines";
    case GLYPH_BLOCKS: return "block";
    case GLYPH_MIXED:  return "mixed";
    default:           return "?    ";
    }
}

static WallStyle outer_style_for(GlyphSet g)
{
    switch (g) {
    case GLYPH_LINES:  return STYLE_LINES;
    case GLYPH_BLOCKS: return STYLE_BLOCKS;
    case GLYPH_MIXED:  return STYLE_BLOCKS;
    default:           return STYLE_LINES;
    }
}

static WallStyle inner_style_for(GlyphSet g)
{
    switch (g) {
    case GLYPH_LINES:  return STYLE_LINES;
    case GLYPH_BLOCKS: return STYLE_BLOCKS;
    case GLYPH_MIXED:  return STYLE_LINES;
    default:           return STYLE_LINES;
    }
}

/* hash3 — same routine as other showcases. */
static inline uint32_t hash3(int wx, int wy, int wz)
{
    uint32_t h = (uint32_t)wx * 73856093u
               ^ (uint32_t)wy * 19349663u
               ^ (uint32_t)wz * 83492791u;
    h ^= h >> 16;
    h *= 0x85ebca6bu;
    h ^= h >> 13;
    h *= 0xc2b2ae35u;
    h ^= h >> 16;
    return h;
}

/* Perlin scaffold — copied inline per the self-contained-file rule. */
static uint8_t perm[512];

static inline float fade_q(float t)
{
    return t * t * t * (t * (t * 6.0f - 15.0f) + 10.0f);
}
static inline float lerp_f(float a, float b, float t) { return a + t * (b - a); }
static inline float grad2(int hash, float x, float y)
{
    int h = hash & 7;
    float u = (h < 4) ? x : y;
    float v = (h < 4) ? y : x;
    return ((h & 1) ? -u : u) + ((h & 2) ? -2.0f * v : 2.0f * v);
}

static float perlin2d(float x, float y)
{
    int X = (int)floorf(x) & 255;
    int Y = (int)floorf(y) & 255;
    x -= floorf(x); y -= floorf(y);
    float u = fade_q(x), v = fade_q(y);
    int A = perm[X    ] + Y;
    int B = perm[X + 1] + Y;
    float n00 = grad2(perm[A    ], x,        y       );
    float n10 = grad2(perm[B    ], x - 1.0f, y       );
    float n01 = grad2(perm[A + 1], x,        y - 1.0f);
    float n11 = grad2(perm[B + 1], x - 1.0f, y - 1.0f);
    return lerp_f(lerp_f(n00, n10, u), lerp_f(n01, n11, u), v);
}

static float fbm2(float x, float y)
{
    float total = 0.0f, amp = 1.0f, freq = 1.0f, max_amp = 0.0f;
    for (int o = 0; o < FBM_OCTAVES; o++) {
        total   += amp * perlin2d(x * freq, y * freq);
        max_amp += amp;
        amp     *= 0.5f;
        freq    *= 2.0f;
    }
    return (total / max_amp) * 0.5f + 0.5f;     /* → [0, 1] */
}

/*
 * bright_at — slow drifting fBm spotlight value at a screen cell.
 * Returns [0, 1]. Used to modulate per-cell A_DIM/A_NORMAL/A_BOLD.
 */
static inline float bright_at(int sx, int sy, float wind_x)
{
    float nx = (float)sx * BRIGHT_SCALE_X + wind_x;
    float ny = (float)sy * BRIGHT_SCALE_Y * ASPECT_Y_F;
    float b  = fbm2(nx, ny);
    if (b < 0.0f) b = 0.0f;
    if (b > 1.0f) b = 1.0f;
    return b;
}

/* brightness_attr — map a [0,1] brightness sample to an ncurses intensity.
 * no_dim raises the floor to A_NORMAL (inner walls, so they stay legible
 * even where the fBm field is darkest). */
static inline int brightness_attr(float b, bool no_dim)
{
    if (b > BRIGHT_HI)            return A_BOLD;
    if (b < BRIGHT_LO && !no_dim) return A_DIM;
    return A_NORMAL;
}

/* flash_active — is the reseed-flash envelope still bright enough to draw? */
static inline bool flash_active(float flash_t) { return flash_t > FLASH_VISIBLE_MIN; }

/* inner_seed — deterministic seed for the inner maze of outer cell (ox,oy):
 * the base seed mixed with the cell's hashed coordinates, so the whole nest
 * reproduces from one seed yet every room differs. */
static inline int inner_seed(int base_seed, int ox, int oy)
{
    return base_seed ^ (int)hash3(ox, oy, INNER_SEED_SALT);
}

/* imin — integer minimum; used to clamp a requested size down to capacity. */
static inline int imin(int a, int b) { return a < b ? a : b; }

/* cycle_next / cycle_prev — step an index forward / back around a ring of
 * n items (modular wrap), for t/n/g-style option cycling. */
static inline int cycle_next(int i, int n) { return (i + 1) % n; }
static inline int cycle_prev(int i, int n) { return (i + n - 1) % n; }

/* fit_cell_size — largest cell size (chars) such that n_cells cells plus
 * their shared far border fit within span, floored at min_cell so a cell
 * never collapses to nothing. */
static inline int fit_cell_size(int span, int n_cells, int min_cell)
{
    int size = (span - 1) / n_cells;     /* -1 leaves room for the far border */
    return size < min_cell ? min_cell : size;
}

/* grid_span — on-screen extent of an n_cells grid at cell_size: the cells
 * plus the one trailing border line (mirrors fit_cell_size's -1). */
static inline int grid_span(int cell_size, int n_cells) { return cell_size * n_cells + 1; }

/* center_offset — offset that centres `content` within `avail`, never below
 * `origin` (an oversized grid clips at the origin, not off-screen). */
static inline int center_offset(int avail, int content, int origin)
{
    int off = origin + (avail - content) / 2;
    return off < origin ? origin : off;
}

/* ===================================================================== */
/* §3  performance  — wall-clock read + sleep (frame pacing: §8 loop) */
/* ===================================================================== */

static int64_t clock_ns(void)
{
    struct timespec t;
    clock_gettime(CLOCK_MONOTONIC, &t);
    return (int64_t)t.tv_sec * NS_PER_SEC + t.tv_nsec;
}

static void clock_sleep_ns(int64_t ns)
{
    if (ns <= 0) return;
    struct timespec req = {
        .tv_sec  = (time_t)(ns / NS_PER_SEC),
        .tv_nsec = (long)  (ns % NS_PER_SEC),
    };
    nanosleep(&req, NULL);
}

/* ===================================================================== */
/* §4  platform     — ncurses colour setup (init + theme key)         */
/* ===================================================================== */

/* load_theme_pairs — bind the 8 ramp pairs to a theme's 256-colour palette. */
static void load_theme_pairs(const Theme *t)
{
    for (int i = 0; i < 8; i++)
        init_pair((short)(PAIR_RAMP_BASE + i), t->ramp[i], -1);
}

/* load_fallback_pairs — the 8/16-colour fallback ramp, for terminals without
 * the 256-colour cube. */
static void load_fallback_pairs(void)
{
    static const short fb[8] = {
        COLOR_BLUE,  COLOR_BLUE,  COLOR_CYAN,   COLOR_CYAN,
        COLOR_GREEN, COLOR_YELLOW,COLOR_YELLOW, COLOR_WHITE,
    };
    for (int i = 0; i < 8; i++)
        init_pair((short)(PAIR_RAMP_BASE + i), fb[i], -1);
}

static void theme_apply(int idx)
{
    if (idx < 0 || idx >= N_THEMES) idx = 0;
    if (COLORS >= 256) load_theme_pairs(&themes[idx]);
    else               load_fallback_pairs();
}

static void color_init(void)
{
    start_color();
    use_default_colors();
    if (COLORS >= 256) {
        init_pair(PAIR_HUD,   226, -1);
        init_pair(PAIR_HINT,   51, -1);
        init_pair(PAIR_FLASH, 226, -1);
    } else {
        init_pair(PAIR_HUD,   COLOR_YELLOW, -1);
        init_pair(PAIR_HINT,  COLOR_CYAN,   -1);
        init_pair(PAIR_FLASH, COLOR_YELLOW, -1);
    }
    theme_apply(0);
}

/* ===================================================================== */
/* §5  generation   — builds static maze + noise basis; EVENT/INIT only */
/* ===================================================================== */

static void perm_shuffle(int seed)
{
    uint8_t base[256];
    for (int i = 0; i < 256; i++) base[i] = (uint8_t)i;
    uint32_t st = (uint32_t)seed * KNUTH_HASH32;
    for (int i = 255; i > 0; i--) {
        st = st * LCG_MUL + LCG_ADD;
        int j = (int)(st >> 16) % (i + 1);
        uint8_t t = base[i]; base[i] = base[j]; base[j] = t;
    }
    /* mirror the 256-entry table into the upper half so perlin2d can index
     * perm[X]+perm[X+1] (offsets up to 511) without a wrap test */
    for (int i = 0; i < 256; i++) {
        perm[i      ] = base[i];
        perm[i + 256] = base[i];
    }
}

/* ----------------------------------------------------------------------- *
 * Maze + DFS carve.                                                        *
 * ----------------------------------------------------------------------- */

/*
 * Maze — one "perfect" maze: a grid in which exactly one path connects any
 * two cells (a SPANNING TREE of the grid graph — no loops, no unreachable
 * cells). maze_generate() carves it with the RECURSIVE BACKTRACKER
 * (randomised depth-first search): start with every wall up, walk to a
 * random unvisited neighbour knocking down the shared wall, and backtrack
 * at dead ends until all cells are visited.
 *   refs: Buck, "Mazes for Programmers" ch.5; perfect maze == spanning
 *         tree, CLRS §20 (DFS) / §21 (spanning trees).
 *
 * Representation — ONE byte per cell holding four wall bits, N=1 E=2 S=4
 * W=8 (WALL_N..WALL_W); 0xF = all walls up, the pre-carve state. An
 * interior wall is shared by two cells and stored REDUNDANTLY in both
 * (carving clears the bit on each side); the redundancy is deliberate so
 * the renderer can read any cell in isolation without consulting its
 * neighbours. Flat row-major: cell (x,y) is walls[y*w + x].
 */
typedef struct {
    int     w, h;                   /* grid size in cells, each <= MAX_MAZE_W/H */
    uint8_t walls[MAX_MAZE_CELLS];  /* per-cell 4-bit wall mask, row-major      */
} Maze;

/* Direction tables, clockwise from N. */
static const int DX[4] = {  0,  1,  0, -1 };
static const int DY[4] = { -1,  0,  1,  0 };
static const int OPP[4] = { 2,  3,  0,  1 };
static const uint8_t WALL_BIT[4] = { WALL_N, WALL_E, WALL_S, WALL_W };

/*
 * tiny LCG — deterministic per-call randomness for the DFS shuffle.
 * Seeded from the maze's seed; produces reproducible mazes.
 */
static inline uint32_t lcg_next(uint32_t *st)
{
    *st = (*st) * LCG_MUL + LCG_ADD;
    return *st;
}

static void shuffle4(int *a, uint32_t *st)
{
    for (int i = 3; i > 0; i--) {
        int j = (int)(lcg_next(st) >> 16) % (i + 1);
        int t = a[i]; a[i] = a[j]; a[j] = t;
    }
}

/* cell_idx — flat row-major index of cell (x, y) in a w*h grid. */
static inline int cell_idx(const Maze *m, int x, int y) { return y * m->w + x; }

/* in_bounds — is (x, y) a real cell of this maze grid? */
static inline bool in_bounds(const Maze *m, int x, int y)
{
    return x >= 0 && x < m->w && y >= 0 && y < m->h;
}

/*
 * remove_wall_between — knock down the wall shared by cell (x, y) and its
 * neighbour in direction d. The wall is stored REDUNDANTLY in both cells, so
 * clear the bit on each side: our wall d, their wall OPP[d].
 */
static inline void remove_wall_between(Maze *m, int x, int y, int d)
{
    int nx = x + DX[d], ny = y + DY[d];
    m->walls[cell_idx(m, x,  y )] &= (uint8_t)~WALL_BIT[d];
    m->walls[cell_idx(m, nx, ny)] &= (uint8_t)~WALL_BIT[OPP[d]];
}

/*
 * dfs_carve — recursive backtracker. From cell (x, y), shuffle the
 * four directions, and for each unvisited in-bounds neighbour,
 * remove the shared wall and recurse. When all 4 are visited or
 * out-of-bounds, return (effectively backtracking).
 *
 * `visited` is a flat bool array of size m->w * m->h, owned by the
 * caller (allocated on stack in maze_generate). `st` is the LCG state
 * threaded through recursive calls.
 */
static void dfs_carve(Maze *m, int x, int y, bool *visited, uint32_t *st)
{
    visited[cell_idx(m, x, y)] = true;
    int order[4] = { 0, 1, 2, 3 };
    shuffle4(order, st);
    for (int i = 0; i < 4; i++) {
        int d  = order[i];
        int nx = x + DX[d];
        int ny = y + DY[d];
        if (!in_bounds(m, nx, ny))           continue;
        if (visited[cell_idx(m, nx, ny)])    continue;
        remove_wall_between(m, x, y, d);
        dfs_carve(m, nx, ny, visited, st);
    }
}

/* lcg_seed_from — mix a maze seed into a NONZERO LCG state. The LCG
 * degenerates to a constant-zero stream if ever seeded with 0, so force the
 * state away from zero. */
static inline uint32_t lcg_seed_from(int seed)
{
    uint32_t st = (uint32_t)seed * KNUTH_HASH32 + 1u;
    return st ? st : 1u;
}

static void maze_generate(Maze *m, int seed)
{
    int total = m->w * m->h;
    if (total > MAX_MAZE_CELLS) return;     /* should never happen */

    /* reset to the pre-carve state: every wall up, no cell visited */
    bool visited[MAX_MAZE_CELLS];
    for (int i = 0; i < total; i++) {
        m->walls[i] = ALL_WALLS;
        visited[i]  = false;
    }

    uint32_t st = lcg_seed_from(seed);
    dfs_carve(m, 0, 0, visited, &st);
}

/* ----------------------------------------------------------------------- *
 * Maze of maze.                                                            *
 * ----------------------------------------------------------------------- */

/*
 * MazeOfMaze — the nested structure: one OUTER maze, plus an INNER maze
 * carved independently inside every outer cell. Two perfect mazes at two
 * scales, visible at once — a self-similar, fractal-flavoured layout (the
 * "maze of mazes"). mom_generate() seeds each inner maze from
 * base_seed ^ hash3(ox,oy,..), so the whole nest is reproducible from the
 * single Scene.seed yet no two rooms share a layout. The two levels are
 * deliberately INDEPENDENT — inner walls do not line up across room
 * boundaries — which is what makes the eye read two distinct scales.
 */
typedef struct {
    Maze outer;                    /* the big maze; its cells ARE the rooms   */
    Maze inner[MAX_OUTER_CELLS];   /* one inner maze per outer cell, row-major */
    int  outer_count;              /* live outer.w*outer.h; bounds the inner[]*/
                                   /*   loop so stale cells are never drawn   */
} MazeOfMaze;

static void mom_generate(MazeOfMaze *mom, const PatternCfg *cfg, int seed)
{
    int ow = imin(cfg->outer_w, MAX_MAZE_W);   /* clamp request to walls[] cap */
    int oh = imin(cfg->outer_h, MAX_MAZE_H);
    int iw = imin(cfg->inner_w, MAX_MAZE_W);
    int ih = imin(cfg->inner_h, MAX_MAZE_H);

    /* 1. carve the outer maze — its cells become the rooms */
    mom->outer.w = ow;
    mom->outer.h = oh;
    maze_generate(&mom->outer, seed);

    /* 2. carve one independent inner maze per room, each seeded from its
     *    (ox,oy) so the nest is reproducible from `seed` yet every room differs */
    mom->outer_count = ow * oh;
    for (int oy = 0; oy < oh; oy++) {
        for (int ox = 0; ox < ow; ox++) {
            Maze *room = &mom->inner[oy * ow + ox];
            room->w = iw;
            room->h = ih;
            maze_generate(room, inner_seed(seed, ox, oy));
        }
    }
}

/*
 * Brightness — the slow fractal-noise (fBm) light wash that drifts over the
 * otherwise STATIC maze, giving motion without changing a single wall.
 * bright_at() samples a value in [0,1] per screen cell from this state, and
 * render thresholds it to A_DIM / A_NORMAL / A_BOLD. The field itself is
 * never stored — only the drift phase below — so the type costs a handful
 * of bytes.
 *   refs: Perlin, "Improving Noise" (the perlin2d gradient noise);
 *         Ebert et al., "Texturing & Modeling" (fBm = sum of noise octaves).
 *
 *   drift : a clock plus a horizontal "wind" offset that scrolls the noise
 *           field sideways each tick (so the wash appears to blow across the
 *           maze), plus a reseed-flash envelope that fades 1 -> 0.
 *   speed : user multiplier on the wind — how fast the wash drifts.
 */
typedef struct {
    float time_secs;   /* elapsed seconds, advanced each tick; doubles as    */
                       /*   reseed entropy and the flash sparkle's phase     */
    float wind_x;      /* fBm horizontal scroll offset (the "wind") — the    */
                       /*   only term that makes the static maze shimmer     */
    float flash_t;     /* reseed-flash envelope: set 1.0 on regen, decays    */
                       /*   exp(-4*dt) -> 0; gates the '*' sparkle overlay   */
    int   speed;       /* drift rate SPEED_MIN..SPEED_MAX (+/- keys, x2 /2)  */
} Brightness;

/*
 * Scene — the whole demo state as a table of contents: the maze being
 * shown, the inputs that pick and paint it, and the cosmetic light over it.
 * Fields are grouped by CONCEPT, not by the key that changes them (a colour
 * theme is a render concept even though a key toggles it). Two boundaries
 * to keep in mind: changing `seed` or `current_pattern` forces a recarve
 * (scene_regenerate); `current_glyph`/`current_theme` are render-only and
 * need none. And only the init/reset/tick orchestrators take Scene* — leaf
 * functions take the narrowest sub-type (render takes Brightness*), so the
 * aggregate never re-couples the layers.
 */
typedef struct {
    MazeOfMaze mom;             /* WHAT  — the nested maze (static once carved) */
    Pattern    current_pattern; /* which maze: outer/inner cell-count combo     */
    int        seed;            /* which maze: RNG instance selector            */
    GlyphSet   current_glyph;   /* how drawn: wall glyph style                  */
    int        current_theme;   /* how drawn: palette index into themes[]       */
    Brightness bright;          /* the drifting light wash + reseed flash       */
    bool       paused;          /* run-state: freezes the drift                 */
} Scene;

/*
 * apply_perm — reshuffle the Perlin perm[] for the current
 * (seed, pattern) pair so the brightness field changes per pattern.
 * Same trick as truchet_tiles.c / wang_tiles.c / penrose_tiling.c.
 */
static void apply_perm(int seed, Pattern pattern)
{
    perm_shuffle(seed ^ ((int)pattern * 0xA5A5A5));
}

static void scene_regenerate(Scene *s)
{
    apply_perm(s->seed, s->current_pattern);
    mom_generate(&s->mom, &PATTERN_CFG[s->current_pattern], s->seed);
    s->bright.flash_t = 1.0f;
}

static void scene_reseed(Scene *s)
{
    s->seed = (int)hash3((int)(s->bright.time_secs * 1000.0f),
                         (int)(s->bright.wind_x * 100.0f), 0xC0FFEE);
    scene_regenerate(s);
}

static void scene_init(Scene *s)
{
    memset(s, 0, sizeof *s);
    s->paused          = false;
    s->bright.speed    = SPEED_DEF;
    s->current_theme   = 0;
    s->current_pattern = PATTERN_CLASSIC;
    s->current_glyph   = GLYPH_LINES;
    s->seed            = 0xCAFE;
    scene_regenerate(s);
}

/* ===================================================================== */
/* §6  effects      — cosmetic per-tick state advance (only simulation) */
/* ===================================================================== */

/*
 * scene_tick — advance brightness wind. Maze layout is static until
 * the user reseeds or changes pattern.
 */
static void scene_tick(Scene *s, float dt)
{
    s->bright.time_secs += dt;
    s->bright.flash_t   *= expf(-4.0f * dt);
    if (s->paused) return;

    float speed_mul = (float)s->bright.speed / (float)SPEED_DEF;
    s->bright.wind_x += WIND_X_BASE * speed_mul * dt;
}

/* ===================================================================== */
/* §7  render       — state -> screen; reads only, never mutates Scene */
/* ===================================================================== */

/*
 * Screen — the terminal viewport, measured in character cells. Re-read from
 * getmaxyx() at init and on every SIGWINCH (screen_resize), so all
 * rendering bounds-checks against the LIVE size and a resize never corrupts
 * the display. Passed const to draw functions; scene_draw() is the single
 * place that converts these dimensions into the per-cell pixel sizes of the
 * maze grid (the one terminal-size -> cell-size conversion point).
 */
typedef struct {
    int cols, rows;   /* viewport width, height in characters (cols=x, rows=y)*/
} Screen;

static void screen_init(Screen *s)
{
    initscr();
    noecho();
    cbreak();
    curs_set(0);
    nodelay(stdscr, TRUE);
    keypad(stdscr, TRUE);
    typeahead(-1);
    color_init();
    getmaxyx(stdscr, s->rows, s->cols);
}
static void screen_free(Screen *s) { (void)s; endwin(); }
static void screen_resize(Screen *s)
{
    endwin();
    refresh();
    getmaxyx(stdscr, s->rows, s->cols);
}

/*
 * draw_wall_cell — write one wall-segment glyph at (sy, sx) with
 * brightness modulation. Bounds-checks against the screen (rows-1
 * reserved for HUD).
 *
 * `no_dim` clamps the brightness floor to A_NORMAL — used for inner
 * walls so they remain readable everywhere, even where the fBm
 * brightness field is at its dim end. Outer walls leave it false so
 * the dim/normal/bold contrast still animates the outer scale.
 */
static inline void draw_wall_cell(const Screen *sc, const Brightness *br,
                                  int sx, int sy, char glyph,
                                  int pair, int extra_attr, bool no_dim)
{
    if (sy < HUD_TOP_ROWS || sy >= sc->rows - 1) return;
    if (sx < 0 || sx >= sc->cols)                return;
    int attr = brightness_attr(bright_at(sx, sy, br->wind_x), no_dim) | extra_attr;
    attron(COLOR_PAIR(pair) | attr);
    mvaddch(sy, sx, (chtype)(unsigned char)glyph);
    attroff(COLOR_PAIR(pair) | attr);
}

/*
 * draw_cell_walls — stamp the present edges of one maze cell whose top-left
 * corner is at screen (sx, sy) and which spans cw x ch chars. Endpoints
 * (dx/dy from 1) are skipped: the lattice crossings are drawn afterwards by
 * draw_grid_corners so '+' always lands on top.
 */
static void draw_cell_walls(const Screen *sc, const Brightness *br,
                            int sx, int sy, int cw, int ch, uint8_t walls,
                            WallStyle style, int pair, int extra_attr, bool no_dim)
{
    if (walls & WALL_N)
        for (int dx = 1; dx < cw; dx++)
            draw_wall_cell(sc, br, sx + dx, sy, style.h_wall, pair, extra_attr, no_dim);
    if (walls & WALL_E)
        for (int dy = 1; dy < ch; dy++)
            draw_wall_cell(sc, br, sx + cw, sy + dy, style.v_wall, pair, extra_attr, no_dim);
    if (walls & WALL_S)
        for (int dx = 1; dx < cw; dx++)
            draw_wall_cell(sc, br, sx + dx, sy + ch, style.h_wall, pair, extra_attr, no_dim);
    if (walls & WALL_W)
        for (int dy = 1; dy < ch; dy++)
            draw_wall_cell(sc, br, sx, sy + dy, style.v_wall, pair, extra_attr, no_dim);
}

/*
 * draw_grid_corners — stamp the intersection glyph at every lattice point
 * of the maze grid, after the edges, so corners are never overwritten.
 */
static void draw_grid_corners(const Screen *sc, const Brightness *br,
                              const Maze *m, int gx, int gy, int cw, int ch,
                              WallStyle style, int pair, int extra_attr, bool no_dim)
{
    for (int my = 0; my <= m->h; my++)
        for (int mx = 0; mx <= m->w; mx++)
            draw_wall_cell(sc, br, gx + mx * cw, gy + my * ch,
                           style.corner, pair, extra_attr, no_dim);
}

/*
 * render_maze — draw one maze at screen (gx, gy) with cw x ch cells in the
 * given style. Adjacent cells share a wall and both draw it (idempotent,
 * same colour). Reads as two passes: edges, then crossings on top.
 */
static void render_maze(const Screen *sc, const Brightness *br,
                        const Maze *m, int gx, int gy,
                        int cw, int ch,
                        WallStyle style, int pair, int extra_attr,
                        bool no_dim)
{
    for (int my = 0; my < m->h; my++)
        for (int mx = 0; mx < m->w; mx++)
            draw_cell_walls(sc, br, gx + mx * cw, gy + my * ch, cw, ch,
                            m->walls[my * m->w + mx],
                            style, pair, extra_attr, no_dim);

    draw_grid_corners(sc, br, m, gx, gy, cw, ch, style, pair, extra_attr, no_dim);
}

/*
 * MazeLayout — the computed on-screen geometry of one maze-of-maze frame,
 * all in terminal character cells. layout_fit() derives it once per frame
 * from the live screen size and the pattern, so scene_draw and its draw
 * helpers share one consistent placement.
 */
typedef struct {
    int gx, gy;                         /* top-left corner of the outer grid  */
    int cw_outer, ch_outer;             /* one outer cell (a room), in chars  */
    int cw_inner, ch_inner;             /* one inner cell, in chars           */
    int inner_margin_x, inner_margin_y; /* inset of an inner maze in its room */
} MazeLayout;

/*
 * layout_fit — size and centre the nested grid for the current screen.
 * Outer cells fill the area below the HUD; inner cells fill each room's
 * interior (the room minus its 1-char wall ring), with both mazes centred
 * in their boxes so nothing sits flush against a corner.
 */
static MazeLayout layout_fit(const Screen *sc, const PatternCfg *cfg)
{
    int avail_w = sc->cols;
    int avail_h = sc->rows - 1 - HUD_TOP_ROWS;   /* between HUD top and hint row */

    MazeLayout L;
    L.cw_outer = fit_cell_size(avail_w, cfg->outer_w, MIN_OUTER_CW);
    L.ch_outer = fit_cell_size(avail_h, cfg->outer_h, MIN_OUTER_CH);
    L.gx = center_offset(avail_w, grid_span(L.cw_outer, cfg->outer_w), 0);
    L.gy = center_offset(avail_h, grid_span(L.ch_outer, cfg->outer_h), HUD_TOP_ROWS);

    int interior_w = L.cw_outer - 1;             /* room interior = room minus */
    int interior_h = L.ch_outer - 1;             /*   its outer wall ring      */
    L.cw_inner = fit_cell_size(interior_w, cfg->inner_w, MIN_INNER_CELL);
    L.ch_inner = fit_cell_size(interior_h, cfg->inner_h, MIN_INNER_CELL);
    L.inner_margin_x = center_offset(interior_w, grid_span(L.cw_inner, cfg->inner_w), 0);
    L.inner_margin_y = center_offset(interior_h, grid_span(L.ch_inner, cfg->inner_h), 0);
    return L;
}

/*
 * draw_inner_mazes — render every room's inner maze, inset within the room.
 * Drawn FIRST so the outer walls (next) overlay any inner cell that lands on
 * a room boundary. no_dim keeps inner walls at >= A_NORMAL so they stay
 * legible where the fBm field is darkest.
 */
static void draw_inner_mazes(const Screen *sc, const Scene *s,
                             const PatternCfg *cfg, const MazeLayout *L)
{
    WallStyle style = inner_style_for(s->current_glyph);
    int pair = PAIR_RAMP_BASE + INNER_RAMP;
    for (int oy = 0; oy < cfg->outer_h; oy++) {
        for (int ox = 0; ox < cfg->outer_w; ox++) {
            int idx = oy * cfg->outer_w + ox;
            if (idx >= s->mom.outer_count) break;
            int igx = L->gx + ox * L->cw_outer + 1 + L->inner_margin_x;
            int igy = L->gy + oy * L->ch_outer + 1 + L->inner_margin_y;
            render_maze(sc, &s->bright, &s->mom.inner[idx], igx, igy,
                        L->cw_inner, L->ch_inner, style, pair, A_NORMAL, true);
        }
    }
}

/*
 * draw_outer_maze — render the outer maze over the inner ones; A_BOLD and
 * full brightness modulation make the large scale dominant.
 */
static void draw_outer_maze(const Screen *sc, const Scene *s, const MazeLayout *L)
{
    WallStyle style = outer_style_for(s->current_glyph);
    int pair = PAIR_RAMP_BASE + OUTER_RAMP;
    render_maze(sc, &s->bright, &s->mom.outer, L->gx, L->gy,
                L->cw_outer, L->ch_outer, style, pair, A_BOLD, false);
}

/*
 * draw_reseed_flash — the brief sparkle wash after a regenerate. A sparse
 * XOR pattern (~1 cell in 8) whose phase is advanced by time, so it shimmers.
 */
static void draw_reseed_flash(const Screen *sc, const Scene *s)
{
    int phase = (int)(s->bright.time_secs * FLASH_PHASE_RATE);
    attron(COLOR_PAIR(PAIR_FLASH) | A_BOLD);
    for (int sy = HUD_TOP_ROWS; sy < sc->rows - 1; sy += 2)
        for (int sx = 0; sx < sc->cols; sx += 2)
            if (((sx ^ sy ^ phase) & FLASH_SPARSITY_MASK) == 0)
                mvaddch(sy, sx, FLASH_GLYPH);
    attroff(COLOR_PAIR(PAIR_FLASH) | A_BOLD);
}

/*
 * scene_draw — render one frame of the maze of mazes: inner mazes first,
 * outer walls over the top, then the post-regenerate flash if it is fading.
 */
static void scene_draw(const Screen *sc, const Scene *s)
{
    const PatternCfg *cfg = &PATTERN_CFG[s->current_pattern];
    MazeLayout layout = layout_fit(sc, cfg);

    draw_inner_mazes(sc, s, cfg, &layout);
    draw_outer_maze(sc, s, &layout);
    if (flash_active(s->bright.flash_t))
        draw_reseed_flash(sc, s);
}

/* draw_ramp_swatch — the 8 palette tiers as a glyph strip (dark -> bright)
 * starting at column x; returns the column just past it. */
static int draw_ramp_swatch(int x)
{
    static const char ramp_glyphs[8] = { '`', '.', ',', ':', '-', 'o', '#', '@' };
    for (int i = 0; i < 8; i++) {
        attron(COLOR_PAIR(PAIR_RAMP_BASE + i) | A_BOLD);
        mvaddch(1, x, (chtype)(unsigned char)ramp_glyphs[i]);
        attroff(COLOR_PAIR(PAIR_RAMP_BASE + i) | A_BOLD);
        x++;
    }
    return x;
}

/* draw_hud_status — row 0: fps / tick rate / state / speed (right), title (left) */
static void draw_hud_status(const Screen *sc, const Scene *s, double fps, int sim_fps)
{
    const char *state_str = s->paused ? "PAUSED" : "DRIFT ";
    char buf[HUD_COLS + 1];
    snprintf(buf, sizeof buf, " %5.1f fps  %3d Hz  %s  speed:%-3d ",
             fps, sim_fps, state_str, s->bright.speed);
    int hx = sc->cols - (int)strlen(buf);
    if (hx < 0) hx = 0;
    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(0, hx, "%s", buf);
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);

    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(0, 1, " MAZE OF MAZE ");
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);
}

/* draw_hud_params — row 1: pattern / glyph / theme / palette swatch / sizes.
 * x advances by each printed field's width plus a gap (cursor bookkeeping). */
static void draw_hud_params(const Scene *s)
{
    const PatternCfg *cfg = &PATTERN_CFG[s->current_pattern];
    int x = 1;

    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(1, x, " pattern:%-7s ", pattern_name(s->current_pattern));
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    x += 18;

    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(1, x, " glyph:%-5s ", glyph_set_name(s->current_glyph));
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    x += 14;

    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(1, x, " theme:%-8s ", themes[s->current_theme].name);
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    x += 17;

    attron(COLOR_PAIR(PAIR_HUD));
    mvprintw(1, x, " ramp:");
    attroff(COLOR_PAIR(PAIR_HUD));
    x += 6;

    x = draw_ramp_swatch(x);

    attron(COLOR_PAIR(PAIR_HUD));
    mvprintw(1, x, "  outer:%dx%d  inner:%dx%d ",
             cfg->outer_w, cfg->outer_h, cfg->inner_w, cfg->inner_h);
    attroff(COLOR_PAIR(PAIR_HUD));
}

/* draw_hud_hint — bottom row: every interactive key */
static void draw_hud_hint(const Screen *sc)
{
    attron(COLOR_PAIR(PAIR_HINT) | A_BOLD);
    mvprintw(sc->rows - 1, 0,
             " n/p:pattern  g/G:glyph  t/T:theme  +/-:drift  spc:pause  r:reseed  q:quit ");
    attroff(COLOR_PAIR(PAIR_HINT) | A_BOLD);
}

static void screen_draw(Screen *sc, const Scene *s,
                        double fps, int sim_fps)
{
    erase();
    scene_draw(sc, s);
    draw_hud_status(sc, s, fps, sim_fps);
    draw_hud_params(s);
    draw_hud_hint(sc);
}

static void screen_present(void) { wnoutrefresh(stdscr); doupdate(); }

/* ===================================================================== */
/* §8  app          — events + the one tick-combine point + main loop */
/* ===================================================================== */

/*
 * App — the top-level runtime: the simulation (Scene), the viewport
 * (Screen), and the main-loop control state. A single global instance
 * (g_app) exists ONLY so the async signal handlers can reach it. The two
 * sig_atomic_t flags are written from signal context and polled by the loop
 * — hence volatile + the async-signal-safe type, which guarantees an
 * untorn read without locks. sim_fps is the fixed-timestep TICK rate and is
 * decoupled from the ~60 fps render cap (see the accumulator in main()).
 */
typedef struct {
    Scene                 scene;        /* WHAT runs — the demo state          */
    Screen                screen;       /* WHERE it draws — terminal viewport  */
    int                   sim_fps;      /* fixed tick rate, ]/[ keys; != render*/
    volatile sig_atomic_t running;      /* SIGINT/TERM clear it -> loop exits  */
    volatile sig_atomic_t need_resize;  /* SIGWINCH sets it -> re-query size   */
} App;

static App g_app;

static void on_exit_signal  (int sig) { (void)sig; g_app.running     = 0; }
static void on_resize_signal(int sig) { (void)sig; g_app.need_resize = 1; }
static void cleanup(void)             { endwin(); }

static void app_do_resize(App *app)
{
    screen_resize(&app->screen);
    app->need_resize = 0;
}

static bool app_handle_key(App *app, int ch)
{
    Scene *s = &app->scene;
    switch (ch) {
    case 'q': case 'Q': case 27 /* ESC */: return false;
    case ' ':           s->paused = !s->paused;                       break;
    case 'r': case 'R': scene_reseed(s);                               break;

    case '=': case '+':
        if (s->bright.speed < SPEED_MAX) s->bright.speed *= 2;
        if (s->bright.speed > SPEED_MAX) s->bright.speed  = SPEED_MAX;
        break;
    case '-':
        s->bright.speed /= 2;
        if (s->bright.speed < SPEED_MIN) s->bright.speed  = SPEED_MIN;
        break;

    case ']':
        app->sim_fps += SIM_FPS_STEP;
        if (app->sim_fps > SIM_FPS_MAX) app->sim_fps = SIM_FPS_MAX;
        break;
    case '[':
        app->sim_fps -= SIM_FPS_STEP;
        if (app->sim_fps < SIM_FPS_MIN) app->sim_fps = SIM_FPS_MIN;
        break;

    case 't':
        s->current_theme = cycle_next(s->current_theme, N_THEMES);
        theme_apply(s->current_theme);
        break;
    case 'T':
        s->current_theme = cycle_prev(s->current_theme, N_THEMES);
        theme_apply(s->current_theme);
        break;

    case 'n': case 'N':
        s->current_pattern = (Pattern)cycle_next(s->current_pattern, N_PATTERNS);
        scene_regenerate(s);
        break;
    case 'p': case 'P':
        s->current_pattern = (Pattern)cycle_prev(s->current_pattern, N_PATTERNS);
        scene_regenerate(s);
        break;

    case 'g':
        s->current_glyph = (GlyphSet)cycle_next(s->current_glyph, N_GLYPH_SETS);
        break;
    case 'G':
        s->current_glyph = (GlyphSet)cycle_prev(s->current_glyph, N_GLYPH_SETS);
        break;

    default: break;
    }
    return true;
}

/*
 * frame_dt — measure one frame's elapsed time and roll the clock forward.
 * The delta is CLAMPED to MAX_FRAME_MS so a stall (debugger, hung terminal)
 * can't hand the sim a huge dt and trigger a catch-up spiral. On return,
 * *frame_time holds this frame's start instant.
 */
static int64_t frame_dt(int64_t *frame_time)
{
    int64_t now = clock_ns();
    int64_t dt  = now - *frame_time;
    *frame_time = now;
    if (dt > MAX_FRAME_MS * NS_PER_MS) dt = MAX_FRAME_MS * NS_PER_MS;
    return dt;
}

/*
 * frame_sleep — hold the render cap: sleep off whatever is left of this
 * frame's budget (1/RENDER_FPS) after the work already done since
 * frame_start. Sleeping BEFORE terminal I/O keeps the cap stable regardless
 * of how long the write takes.
 */
static void frame_sleep(int64_t frame_start, int64_t dt)
{
    int64_t elapsed = clock_ns() - frame_start + dt;
    clock_sleep_ns(NS_PER_SEC / RENDER_FPS - elapsed);
}

/*
 * FpsCounter — a rolling frame-rate estimate. Frames and elapsed time
 * accumulate until FPS_UPDATE_MS has passed, then `value` is republished and
 * the window resets (so the HUD reading is steady, not jittering per frame).
 */
typedef struct {
    int     count;     /* frames since the last publish */
    int64_t accum;     /* ns since the last publish      */
    double  value;     /* last published frames-per-second */
} FpsCounter;

/* fps_tick — fold one frame of duration dt into the counter; republish the
 * rate once the measurement window fills. */
static void fps_tick(FpsCounter *f, int64_t dt)
{
    f->count++;
    f->accum += dt;
    if (f->accum >= FPS_UPDATE_MS * NS_PER_MS) {
        f->value = (double)f->count / ((double)f->accum / (double)NS_PER_SEC);
        f->count = 0;
        f->accum = 0;
    }
}

/*
 * advance_sim — drain the fixed-timestep accumulator, stepping the sim at
 * exactly sim Hz no matter the render rate (decouples animation speed from
 * frame rate). `accum` carries leftover time between frames.
 */
static void advance_sim(Scene *s, int64_t *accum, int64_t tick_ns, float dt_sec)
{
    while (*accum >= tick_ns) {
        scene_tick(s, dt_sec);
        *accum -= tick_ns;
    }
}

int main(void)
{
    srand((unsigned int)(clock_ns() & 0xFFFFFFFF));
    atexit(cleanup);
    signal(SIGINT,   on_exit_signal);
    signal(SIGTERM,  on_exit_signal);
    signal(SIGWINCH, on_resize_signal);

    App *app     = &g_app;
    app->running = 1;
    app->sim_fps = SIM_FPS_DEFAULT;

    screen_init(&app->screen);
    scene_init(&app->scene);

    int64_t    frame_time = clock_ns();
    int64_t    sim_accum  = 0;
    FpsCounter fps        = { 0, 0, 0.0 };

    while (app->running) {

        if (app->need_resize) {
            app_do_resize(app);
            frame_time = clock_ns();
            sim_accum  = 0;
        }

        int64_t dt      = frame_dt(&frame_time);
        int64_t tick_ns = TICK_NS(app->sim_fps);
        float   dt_sec  = (float)tick_ns / (float)NS_PER_SEC;

        sim_accum += dt;
        advance_sim(&app->scene, &sim_accum, tick_ns, dt_sec);

        fps_tick(&fps, dt);
        frame_sleep(frame_time, dt);

        screen_draw(&app->screen, &app->scene, fps.value, app->sim_fps);
        screen_present();

        int ch = getch();
        if (ch != ERR && !app_handle_key(app, ch))
            app->running = 0;
    }

    screen_free(&app->screen);
    return 0;
}

