/* Copyright (c) 2026 Tamilselvan R  SPDX-License-Identifier: MIT */
/*
 * penrose_tiling.c
 *   — Penrose P3 rhombus tiling generated by Robinson triangle
 *     deflation. Start with a small seed (10 triangles in a star, or
 *     a single rhombus); each iteration replaces every triangle with
 *     smaller golden-ratio-scaled children according to the Penrose
 *     substitution rules. After N rounds you have a finite patch of
 *     a true aperiodic Penrose tiling, drawn as ASCII line art.
 *
 * DEMO: A starburst of triangle edges fills the screen, fanning out
 *       in 5-fold symmetry from a central point. Look closely and
 *       every triangle is one of two shapes — the ACUTE Robinson
 *       triangle (36°-72°-72°, half of a thin rhombus) or the
 *       OBTUSE Robinson triangle (108°-36°-36°, half of a thick
 *       rhombus). Their relative arrangement never repeats; this
 *       is the famous Penrose aperiodic pattern.
 *
 *       PATTERN (n / N) — what to tile:
 *
 *         STAR       10 acutes around the centre, K=5 deflation
 *                    (≈ 900 triangles).  The classic Penrose
 *                    "sun" / "star" configuration.
 *         DEEP       same star at K=6 (≈ 2 300 triangles) —
 *                    finer detail, slower to render.
 *         THIN       single thin rhombus (2 acutes) deflated K=5 —
 *                    isolates the thin rhombus's deflation rule.
 *         THICK      single thick rhombus (2 obtuses) deflated K=5
 *                    — isolates the thick rhombus's rule.
 *
 *       GLYPH (g / G) — how to draw:
 *
 *         EDGES      Bresenham line edges of every triangle
 *         CENTERS    coloured dot at every triangle's centroid
 *                    (acute = mid tint, obtuse = bright tint)
 *         BOTH       edges + dim centroids
 *
 *       'r' randomises the tile orientation/seed offset and re-runs
 *       the deflation. 'space' pauses brightness drift.
 *
 * Study alongside:
 *   ../patterns/quasicrystal.c
 *      — quasicrystals from PLANE-WAVE INTERFERENCE; this file
 *        builds the same 5-fold aperiodic family from
 *        SUBSTITUTION/DEFLATION.  Different mathematics, same
 *        long-range orientational order.
 *   ../patterns/wang_tiles.c
 *      — also tilings constrained by adjacency rules; here the
 *        constraint is in the GEOMETRY (matching edge lengths and
 *        angles after subdivision) rather than coloured edges.
 *
 * Section map:
 *   §1 config        — geometry constants, themes, pattern enum
 *   §2 clock         — monotonic timer + sleep
 *   §3 color         — HUD reserved + 10 themes (8-step ramp + accents)
 *   §5 penrose       — hash, perlin/fBm, triangle struct,
 *                      deflation rule, seed configurations,
 *                      Bresenham rasteriser
 *   §6 scene         — state, regenerate on pattern change / reseed
 *   §7 screen        — render all triangles + brightness modulation
 *   §8 app           — signals, resize, fixed-step main loop
 *
 * Keys:
 *   q / ESC    quit
 *   space      pause / resume light-field drift
 *   r          reseed (rotate tiling, keep same algorithm)
 *   n / N      next pattern
 *   p / P      previous pattern
 *   g / G      next / previous glyph set
 *   t / T      next / previous theme
 *   + / =      faster light drift
 *   -          slower
 *   ] / [      raise / lower tick Hz
 *
 * Build:
 *   gcc -std=c11 -O2 -Wall -Wextra \
 *     procedural/patterns/penrose_tiling.c \
 *     -o penrose -lncurses -lm
 */

/* ── CONCEPTS ──────────────────────────────────────────────────────────── *
 *
 * Algorithm      : Penrose P3 deflation via Robinson triangles.
 *
 *                  Robinson triangles are the two half-rhombuses of
 *                  Penrose's P3 tiling:
 *                    ACUTE   — 36°/72°/72°.  Half of a thin rhombus.
 *                    OBTUSE  — 108°/36°/36°. Half of a thick rhombus.
 *                  Their side ratios are golden:
 *                    acute  = 1 : φ : φ
 *                    obtuse = 1 : 1 : φ          (where φ = golden ratio)
 *
 *                  DEFLATION RULES — each triangle is replaced with
 *                  smaller children scaled by 1/φ:
 *
 *                    ACUTE(A, B, C):
 *                      P = A + (B - A)/φ                  (point on AB)
 *                      → ACUTE(C, P, B)  +  OBTUSE(P, C, A)
 *                    OBTUSE(A, B, C):
 *                      Q = B + (A - B)/φ                  (point on BA)
 *                      R = B + (C - B)/φ                  (point on BC)
 *                      → OBTUSE(R, C, A) + OBTUSE(Q, R, B)
 *                                        + ACUTE (R, Q, A)
 *
 *                  Iterate K times starting from a seed configuration.
 *                  After each iteration, triangle count grows by a
 *                  factor approaching φ (1.618…). With K=5 from a
 *                  10-triangle STAR seed, the final tiling has ~900
 *                  triangles; with K=6, ~2 300.
 *
 *                  RENDERING — each triangle has 3 vertices in 2-D
 *                  float coords, rasterised via Bresenham line drawing
 *                  (see §5 for the integer-only inner loop). Glyph
 *                  selection by edge direction:
 *                    horizontal-ish → '-'
 *                    vertical-ish   → '|'
 *                    NW–SE          → '\\'
 *                    NE–SW          → '/'
 *                  Coloured by triangle type — acute and obtuse
 *                  picked from different ramp slots.
 *
 *                  PLUS a slow-drifting fBm BRIGHTNESS field
 *                  (same trick as truchet_tiles.c / wang_tiles.c)
 *                  modulates per-cell A_DIM/A_NORMAL/A_BOLD over the
 *                  static tiling, giving the pattern subtle motion
 *                  without retiling.
 *
 * Data-structure : Two flat arrays of Triangle structs (double-buffered
 *                  so the next iteration writes into the inactive
 *                  buffer while reading the active one). Each Triangle
 *                  is 28 bytes (1 int colour + 6 floats).  Capped at
 *                  4 096 triangles per buffer, comfortably fitting K=6
 *                  from any seed.
 *
 * Rendering      : ASCII only.  Bresenham line plotting per triangle
 *                  edge, ~10–20 cells per edge. With 2 300 triangles
 *                  × 3 edges × 15 cells ≈ 100 K cell writes per frame
 *                  — plenty fast at 60 fps.
 *
 * Performance    : Generation (K=6 from STAR seed): ~17 000 triangles
 *                  written across 6 iterations; runs in milliseconds.
 *                  Per-frame render: ~100 K mvaddch calls. The
 *                  brightness-fBm overlay adds one fBm per cell on top.
 *                  Total ~10 % of one CPU core at 240×80×60 fps.
 *
 * References     :
 *   • Penrose, R. (1974) — "The Role of Aesthetics in Pure and
 *     Applied Mathematical Research", Bulletin of the IMA 10:266.
 *   • Grünbaum & Shephard (1986) — "Tilings and Patterns".
 *     Definitive reference; chapter on Penrose tilings.
 *   • De Bruijn, N.G. (1981) — "Algebraic theory of Penrose's
 *     non-periodic tilings of the plane", Indagationes Math 43.
 *   • Wikipedia — Penrose tiling
 *     https://en.wikipedia.org/wiki/Penrose_tiling
 *   • Preshing, Jeff — "Penrose Tiling Explained"
 *     https://preshing.com/20110831/penrose-tiling-explained/
 *   • Bresenham, J. (1965) — "Algorithm for computer control of a
 *     digital plotter", IBM Systems Journal 4(1):25–30.
 *
 * ─────────────────────────────────────────────────────────────────────── */

/* ── MENTAL MODEL ─────────────────────────────────────────────────────── *
 *
 * CORE IDEA
 * ─────────
 * To make an aperiodic tiling, take ONE tile and replace every copy
 * of it with a SMALLER ARRANGEMENT OF THE SAME TILES.  Repeat. Each
 * round multiplies the number of tiles by the golden ratio φ; the
 * shapes get finer and finer, but the SUBSTITUTION RULE is fixed.
 * After N rounds the tiling looks complex, irregular, and
 * non-repeating — yet it was generated by a single deterministic
 * deflation rule. That is Penrose: complexity from inflation.
 *
 * HOW TO THINK ABOUT IT
 * ─────────────────────
 * Imagine a piece of putty in the shape of an arrowhead. Cut it into
 * two smaller arrowheads using a single specific cut. Now you have
 * two pieces of putty, both arrowheads, in the shape configuration
 * the cut prescribes. Cut each of those by the same rule. After
 * enough rounds the original arrowhead has become a fractal-looking
 * mosaic of tiny arrowheads.
 *
 * Penrose's brilliance was finding an arrowhead — actually two
 * arrowheads, the acute and the obtuse Robinson triangle — and a
 * pair of cutting rules where the resulting mosaic is APERIODIC: no
 * matter how big the patch you cut, you cannot translate it onto
 * itself. Yet the global structure has perfect 5-fold rotational
 * symmetry around the seed point. The hallmark of a quasicrystal.
 *
 * ALGORITHM IN STEPS
 * ──────────────────
 *  1. SEED. Place a few triangles in a known starting configuration.
 *     The classic "star" seed uses 10 acute triangles, all with their
 *     36° apex at a common centre, alternating chirality so the
 *     deflation rules match across boundaries.
 *  2. DEFLATE one round:
 *     For every triangle T in the current buffer:
 *       if T is ACUTE: emit (acute_child, obtuse_child) per the rule
 *       if T is OBTUSE: emit (obtuse, obtuse, acute) per the rule
 *     Swap buffers; the new buffer is now the active tiling.
 *  3. REPEAT step 2 K times. Triangle count grows by factor ~φ each
 *     round.
 *  4. RENDER each triangle to the screen via Bresenham line drawing
 *     for its 3 edges; choose a colour from the active theme based
 *     on triangle type (acute vs obtuse) and direction-glyph from
 *     edge slope.
 *  5. ANIMATE by overlaying a slow fBm brightness field that
 *     modulates per-cell A_DIM/A_NORMAL/A_BOLD without changing the
 *     underlying tiling.
 *
 * KEY FORMULAS
 * ────────────
 *  Golden ratio:
 *    φ      = (1 + √5) / 2 ≈ 1.618033988749…
 *    1/φ    = φ - 1
 *
 *  Acute triangle deflation (apex A is the 36° vertex):
 *    P      = A + (B - A) / φ
 *    →  ACUTE (apex C, base P, B)
 *       OBTUSE (apex P, base C, A)
 *
 *  Obtuse triangle deflation (apex A is the 108° vertex):
 *    Q      = B + (A - B) / φ
 *    R      = B + (C - B) / φ
 *    →  OBTUSE (apex R, base C, A)
 *       OBTUSE (apex Q, base R, B)
 *       ACUTE  (apex R, base Q, A)
 *
 *  STAR seed (10 acutes radiating from origin, alternating chirality):
 *    for i = 0..9:
 *      θ_a   = 2π·i / 10
 *      θ_b   = 2π·(i+1) / 10
 *      v_a   = (cos θ_a, sin θ_a)
 *      v_b   = (cos θ_b, sin θ_b)
 *      if i even:  triangle (acute, origin, v_a, v_b)
 *      else:       triangle (acute, origin, v_b, v_a)   [chirality flip]
 *
 *  Bresenham line from (x0, y0) to (x1, y1) — integer-only:
 *    dx = |x1 - x0|;  sx = sign(x1 - x0)
 *    dy = -|y1 - y0|; sy = sign(y1 - y0)
 *    err = dx + dy
 *    each step:
 *      plot(x, y)
 *      e2 = 2·err
 *      if e2 ≥ dy: err += dy; x += sx
 *      if e2 ≤ dx: err += dx; y += sy
 *    until (x, y) == (x1, y1)
 *
 *  Edge-direction glyph:
 *    |dx| ≥ 2·|dy|         → '-'
 *    |dy| ≥ 2·|dx|         → '|'
 *    sign(dx) == sign(dy)  → '\\'
 *    else                  → '/'
 *
 * EDGE CASES TO WATCH
 * ───────────────────
 *  • TRIANGLE BUFFER OVERFLOW. Each iteration can multiply by up to
 *    3× (obtuse → 3 children). With MAX_TRIANGLES=4096 and a STAR
 *    seed (10), K=7 would overflow. The deflation function checks
 *    bounds and stops emitting once full — visually, the tiling
 *    becomes incomplete (some triangles missing) rather than
 *    crashing.  Cap K at 6 for the STAR seed.
 *
 *  • CHIRALITY IN THE SEED. The STAR seed alternates orientation
 *    (the "(i & 1)" flip) so the deflation rule produces a valid
 *    tiling at every triangle boundary. Without alternation, child
 *    triangles from neighbouring seed triangles would not align
 *    edge-to-edge and the tiling would have visible gaps or
 *    overlaps after deflation.
 *
 *  • ASPECT RATIO. Triangle vertices are in unit-circle coords; we
 *    scale to screen by multiplying x by `scale` and y by
 *    `scale / ASPECT_Y_F` so the tiling renders square (not
 *    horizontally squashed). Without this correction the 5-fold
 *    symmetry would look like a flattened ellipse.
 *
 *  • SHARED EDGES DRAWN TWICE. Adjacent triangles share their
 *    "long" edge (the rhombus's diagonal). The renderer draws ALL
 *    edges of all triangles, so each shared edge is drawn twice
 *    in the same colour. Visually identical to drawing once; the
 *    overhead is negligible. To eliminate it you would need to
 *    track edges in a hash set — not worth the complexity.
 *
 *  • BRESENHAM AT ENDPOINTS. Same edge endpoint drawn from two
 *    triangles → that cell is written multiple times. Last write
 *    wins for colour/attr. Since adjacent triangles have different
 *    colours (acute vs obtuse), corner cells take whichever colour
 *    was rendered last. Acceptable visual artifact; minimise by
 *    drawing ALL triangle edges of one type before the other type.
 *
 *  • FLOAT-TO-INT ROUNDING. Vertices are floats; mvaddch needs ints.
 *    Truncating with `(int)` introduces a 1-cell jitter at certain
 *    angles. Use `lroundf` or `floorf + 0.5` for cleaner alignment
 *    if you notice artifacts. Default (int) cast is OK at 240×80.
 *
 * HOW TO VERIFY
 * ─────────────
 *  • PAUSE (space). The brightness wave freezes; the static tiling
 *    is unchanged. Resume: drift continues from where it stopped.
 *
 *  • Press 'r'. The flash fires and the tiling rotates / re-orients
 *    around the centre. Same pattern, different orientation.
 *
 *  • STAR pattern. Look at the centre — you should see 10 triangles
 *    meeting at one point, creating perfect 5-fold rotational
 *    symmetry. After K=5 deflations every original triangle has
 *    been replaced with ~90 smaller ones.
 *
 *  • THIN pattern. A single thin rhombus (long thin shape, vertical)
 *    fills the centre, deflated to its smaller children. Almost all
 *    visible triangles are acute (a property of thin-rhombus
 *    deflation).
 *
 *  • THICK pattern. A thick rhombus (almost square) fills the
 *    centre. Visible triangles are mostly obtuse.
 *
 *  • Glyph cycle (g). The triangle layout doesn't change; only the
 *    rendering does. EDGES shows pure line art. CENTERS shows a
 *    "pointillist" version with one dot per triangle. BOTH overlays.
 *
 *  • Theme cycle (t). Colours for acute vs obtuse should be visibly
 *    distinct in every theme. The brightness drift should be
 *    legible against every theme's ramp.
 *
 * ─────────────────────────────────────────────────────────────────────── */

#define _POSIX_C_SOURCE 200809L

#include <math.h>
#include <ncurses.h>
#include <signal.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ===================================================================== */
/* §1  config                                                             */
/* ===================================================================== */

enum {
    SIM_FPS_MIN         =  10,
    SIM_FPS_DEFAULT     =  60,
    SIM_FPS_MAX         = 240,
    SIM_FPS_STEP        =  10,

    SPEED_MIN           =   1,
    SPEED_DEF           =   8,
    SPEED_MAX           =  64,

    HUD_COLS            =  80,
    FPS_UPDATE_MS       = 500,

    /* Deflation buffer size — large enough for a STAR seed at K=6
     * (≈ 2 300 triangles), with margin. */
    MAX_TRIANGLES       = 4096,

    /* Color pair indices.  PAIR_HUD/PAIR_HINT reserved per CLAUDE.md. */
    PAIR_HUD            =   1,
    PAIR_HINT           =   2,
    PAIR_RAMP_BASE      =   3,    /* +0..+7 = 8 brightness/colour tints */
    PAIR_HOT            =  11,
    PAIR_COLD           =  12,
    PAIR_FLASH          =  13,
};

#define NS_PER_SEC      1000000000LL
#define NS_PER_MS          1000000LL
#define TICK_NS(f)      (NS_PER_SEC / (f))

#define ASPECT_Y_F           2.0f

/* Brightness fBm parameters — slow drift over the static tiling. */
#define BRIGHT_SCALE_X       0.040f
#define BRIGHT_SCALE_Y       0.080f
#define WIND_X_BASE          3.0f
#define FBM_OCTAVES          3

/* Golden ratio and its inverse — drives the deflation step length. */
#define PHI                  1.6180339887498949f
#define INV_PHI              0.6180339887498949f

/* Triangle types. */
#define TRI_ACUTE            0
#define TRI_OBTUSE           1

/*
 * Pattern enum — what to deflate, and how deep. STAR + DEEP differ
 * only in iteration count; THIN and THICK use single-rhombus seeds.
 */
typedef enum {
    PATTERN_STAR  = 0,    /* 10-triangle star, K=5  */
    PATTERN_DEEP  = 1,    /* 10-triangle star, K=6  */
    PATTERN_THIN  = 2,    /* single thin rhombus,  K=5 */
    PATTERN_THICK = 3,    /* single thick rhombus, K=5 */
    N_PATTERNS    = 4,
} Pattern;

static const char *pattern_name(Pattern p)
{
    switch (p) {
    case PATTERN_STAR:  return "STAR ";
    case PATTERN_DEEP:  return "DEEP ";
    case PATTERN_THIN:  return "THIN ";
    case PATTERN_THICK: return "THICK";
    default:            return "?    ";
    }
}

static int pattern_depth(Pattern p)
{
    switch (p) {
    case PATTERN_STAR:  return 5;
    case PATTERN_DEEP:  return 6;
    case PATTERN_THIN:  return 5;
    case PATTERN_THICK: return 5;
    default:            return 5;
    }
}

/* Glyph enum — how the tiling is rendered. */
typedef enum {
    GLYPH_EDGES   = 0,
    GLYPH_CENTERS = 1,
    GLYPH_BOTH    = 2,
    N_GLYPH_SETS  = 3,
} GlyphSet;

static const char *glyph_set_name(GlyphSet g)
{
    switch (g) {
    case GLYPH_EDGES:   return "edges";
    case GLYPH_CENTERS: return "ctrs ";
    case GLYPH_BOTH:    return "both ";
    default:            return "?    ";
    }
}

/* Triangle-type → ramp slot. Acute uses a mid tint; obtuse uses a
 * brighter tint so the two types read as distinct colours regardless
 * of the active theme. Centroid markers get a slightly different
 * pair so they don't merge visually with the edges. */
#define ACUTE_EDGE_RAMP      4
#define OBTUSE_EDGE_RAMP     6
#define ACUTE_CENTER_RAMP    5
#define OBTUSE_CENTER_RAMP   7

/*
 * Themes — every entry sits in the bright half of the 256-colour
 * cube so even A_DIM cells stay legible against a default-black
 * terminal.  See "Theme Palette Brightness" in /CLAUDE.md.
 */
typedef struct {
    const char *name;
    short       ramp[8];
    short       hot;
    short       cold;
} Theme;

#define N_THEMES 10

static const Theme themes[N_THEMES] = {
    /* name       0    1    2    3    4    5    6    7   hot cold */
    { "DEFAULT",{ 24,  31,  39,  70,  76, 137, 215, 230 }, 196,  39 },
    { "MATRIX", { 28,  34,  40,  46,  76, 118, 154, 192 }, 226,  39 },
    { "NOVA",   { 60,  91, 134, 165, 207, 213, 219, 231 }, 196,  39 },
    { "MONO",   {240, 243, 245, 247, 249, 251, 253, 255 }, 226,  39 },
    { "OCEAN",  { 24,  25,  31,  38,  45,  51, 117, 195 }, 196,  21 },
    { "FIRE",   { 88, 124, 130, 166, 202, 208, 214, 226 }, 226,  21 },
    { "EARTH",  { 94, 130, 137, 173, 179, 215, 222, 230 }, 196,  39 },
    { "FOREST", { 28,  34,  40,  70,  76, 112, 156, 192 }, 196,  39 },
    { "DESERT", {130, 137, 143, 173, 179, 215, 222, 229 }, 196,  21 },
    { "ARCTIC", { 24,  31,  67, 110, 117, 153, 195, 231 }, 196,  39 },
};

/* ===================================================================== */
/* §2  clock                                                              */
/* ===================================================================== */

static int64_t clock_ns(void)
{
    struct timespec t;
    clock_gettime(CLOCK_MONOTONIC, &t);
    return (int64_t)t.tv_sec * NS_PER_SEC + t.tv_nsec;
}

static void clock_sleep_ns(int64_t ns)
{
    if (ns <= 0) return;
    struct timespec req = {
        .tv_sec  = (time_t)(ns / NS_PER_SEC),
        .tv_nsec = (long)  (ns % NS_PER_SEC),
    };
    nanosleep(&req, NULL);
}

/* ===================================================================== */
/* §3  color                                                              */
/* ===================================================================== */

static void theme_apply(int idx)
{
    if (idx < 0 || idx >= N_THEMES) idx = 0;
    if (COLORS >= 256) {
        const Theme *t = &themes[idx];
        for (int i = 0; i < 8; i++)
            init_pair((short)(PAIR_RAMP_BASE + i), t->ramp[i], -1);
        init_pair(PAIR_HOT,  t->hot,  -1);
        init_pair(PAIR_COLD, t->cold, -1);
    } else {
        static const short fb[8] = {
            COLOR_BLUE,  COLOR_BLUE,  COLOR_CYAN,   COLOR_CYAN,
            COLOR_GREEN, COLOR_YELLOW,COLOR_YELLOW, COLOR_WHITE,
        };
        for (int i = 0; i < 8; i++)
            init_pair((short)(PAIR_RAMP_BASE + i), fb[i], -1);
        init_pair(PAIR_HOT,  COLOR_RED,  -1);
        init_pair(PAIR_COLD, COLOR_CYAN, -1);
    }
}

static void color_init(void)
{
    start_color();
    use_default_colors();
    if (COLORS >= 256) {
        init_pair(PAIR_HUD,   226, -1);
        init_pair(PAIR_HINT,   51, -1);
        init_pair(PAIR_FLASH, 226, -1);
    } else {
        init_pair(PAIR_HUD,   COLOR_YELLOW, -1);
        init_pair(PAIR_HINT,  COLOR_CYAN,   -1);
        init_pair(PAIR_FLASH, COLOR_YELLOW, -1);
    }
    theme_apply(0);
}

/* ===================================================================== */
/* §5  penrose — hash, perlin, triangle deflation, Bresenham              */
/* ===================================================================== */

/* hash3 — same routine as other showcases. Drives the reseed flash
 * and (indirectly via the perm shuffle) the brightness field. */
static inline uint32_t hash3(int wx, int wy, int wz)
{
    uint32_t h = (uint32_t)wx * 73856093u
               ^ (uint32_t)wy * 19349663u
               ^ (uint32_t)wz * 83492791u;
    h ^= h >> 16;
    h *= 0x85ebca6bu;
    h ^= h >> 13;
    h *= 0xc2b2ae35u;
    h ^= h >> 16;
    return h;
}

/* Perlin scaffold — copied inline per the self-contained-file rule. */
static uint8_t perm[512];

static void perm_shuffle(int seed)
{
    uint8_t base[256];
    for (int i = 0; i < 256; i++) base[i] = (uint8_t)i;
    uint32_t st = (uint32_t)seed * 2654435761u;
    for (int i = 255; i > 0; i--) {
        st = st * 1664525u + 1013904223u;
        int j = (int)(st >> 16) % (i + 1);
        uint8_t t = base[i]; base[i] = base[j]; base[j] = t;
    }
    for (int i = 0; i < 256; i++) {
        perm[i      ] = base[i];
        perm[i + 256] = base[i];
    }
}

static inline float fade_q(float t)
{
    return t * t * t * (t * (t * 6.0f - 15.0f) + 10.0f);
}
static inline float lerp_f(float a, float b, float t) { return a + t * (b - a); }
static inline float grad2(int hash, float x, float y)
{
    int h = hash & 7;
    float u = (h < 4) ? x : y;
    float v = (h < 4) ? y : x;
    return ((h & 1) ? -u : u) + ((h & 2) ? -2.0f * v : 2.0f * v);
}

static float perlin2d(float x, float y)
{
    int X = (int)floorf(x) & 255;
    int Y = (int)floorf(y) & 255;
    x -= floorf(x); y -= floorf(y);
    float u = fade_q(x), v = fade_q(y);
    int A = perm[X    ] + Y;
    int B = perm[X + 1] + Y;
    float n00 = grad2(perm[A    ], x,        y       );
    float n10 = grad2(perm[B    ], x - 1.0f, y       );
    float n01 = grad2(perm[A + 1], x,        y - 1.0f);
    float n11 = grad2(perm[B + 1], x - 1.0f, y - 1.0f);
    return lerp_f(lerp_f(n00, n10, u), lerp_f(n01, n11, u), v);
}

static float fbm2(float x, float y)
{
    float total = 0.0f, amp = 1.0f, freq = 1.0f, max_amp = 0.0f;
    for (int o = 0; o < FBM_OCTAVES; o++) {
        total   += amp * perlin2d(x * freq, y * freq);
        max_amp += amp;
        amp     *= 0.5f;
        freq    *= 2.0f;
    }
    return (total / max_amp) * 0.5f + 0.5f;     /* → [0, 1] */
}

/* ----------------------------------------------------------------------- *
 * Triangle struct + double-buffered deflation.                            *
 * ----------------------------------------------------------------------- */

typedef struct {
    int   color;          /* TRI_ACUTE or TRI_OBTUSE */
    float ax, ay;         /* apex */
    float bx, by;         /* base 1 */
    float cx, cy;         /* base 2 */
} Triangle;

static Triangle tri_buf[2][MAX_TRIANGLES];
static int      tri_n  [2];
static int      tri_active = 0;

/*
 * deflate_step — one round of the Penrose substitution rule.
 * Reads from tri_active buffer, writes to the inactive one, then
 * swaps. After the call, tri_active points to the new tiling.
 *
 * Acute deflation:
 *   ACUTE(A, B, C):
 *     P = A + (B - A) / φ
 *     → ACUTE  (apex C, base P, B)
 *       OBTUSE (apex P, base C, A)
 *
 * Obtuse deflation:
 *   OBTUSE(A, B, C):
 *     Q = B + (A - B) / φ
 *     R = B + (C - B) / φ
 *     → OBTUSE (apex R, base C, A)
 *       OBTUSE (apex Q, base R, B)
 *       ACUTE  (apex R, base Q, A)
 *
 * Capped at MAX_TRIANGLES; any further children are silently dropped
 * so the renderer never reads past the buffer.
 */
static void deflate_step(void)
{
    int from = tri_active;
    int to   = 1 - tri_active;
    int n_in = tri_n[from];
    int n_out = 0;

    for (int i = 0; i < n_in; i++) {
        const Triangle *t = &tri_buf[from][i];

        if (t->color == TRI_ACUTE) {
            float px = t->ax + (t->bx - t->ax) * INV_PHI;
            float py = t->ay + (t->by - t->ay) * INV_PHI;

            if (n_out < MAX_TRIANGLES) {
                Triangle *o = &tri_buf[to][n_out++];
                o->color = TRI_ACUTE;
                o->ax = t->cx; o->ay = t->cy;
                o->bx = px;    o->by = py;
                o->cx = t->bx; o->cy = t->by;
            }
            if (n_out < MAX_TRIANGLES) {
                Triangle *o = &tri_buf[to][n_out++];
                o->color = TRI_OBTUSE;
                o->ax = px;    o->ay = py;
                o->bx = t->cx; o->by = t->cy;
                o->cx = t->ax; o->cy = t->ay;
            }
        } else {
            float qx = t->bx + (t->ax - t->bx) * INV_PHI;
            float qy = t->by + (t->ay - t->by) * INV_PHI;
            float rx = t->bx + (t->cx - t->bx) * INV_PHI;
            float ry = t->by + (t->cy - t->by) * INV_PHI;

            if (n_out < MAX_TRIANGLES) {
                Triangle *o = &tri_buf[to][n_out++];
                o->color = TRI_OBTUSE;
                o->ax = rx;    o->ay = ry;
                o->bx = t->cx; o->by = t->cy;
                o->cx = t->ax; o->cy = t->ay;
            }
            if (n_out < MAX_TRIANGLES) {
                Triangle *o = &tri_buf[to][n_out++];
                o->color = TRI_OBTUSE;
                o->ax = qx;    o->ay = qy;
                o->bx = rx;    o->by = ry;
                o->cx = t->bx; o->cy = t->by;
            }
            if (n_out < MAX_TRIANGLES) {
                Triangle *o = &tri_buf[to][n_out++];
                o->color = TRI_ACUTE;
                o->ax = rx;    o->ay = ry;
                o->bx = qx;    o->by = qy;
                o->cx = t->ax; o->cy = t->ay;
            }
        }
    }

    tri_n[to]  = n_out;
    tri_active = to;
}

/* ----------------------------------------------------------------------- *
 * Seed configurations — one per pattern.                                   *
 * ----------------------------------------------------------------------- */

/*
 * seed_star — 10 acute triangles arranged so all 36° apexes meet at
 * the origin. Adjacent triangles have ALTERNATING chirality (the
 * "(i & 1)" flip) so the deflation rule produces a globally
 * consistent tiling at every shared edge.
 */
static void seed_star(float rot)
{
    int n = 0;
    Triangle *out = tri_buf[0];
    for (int i = 0; i < 10; i++) {
        float a0 = (float)i * 2.0f * (float)M_PI / 10.0f + rot;
        float a1 = (float)(i + 1) * 2.0f * (float)M_PI / 10.0f + rot;
        Triangle *t = &out[n++];
        t->color = TRI_ACUTE;
        t->ax = 0.0f; t->ay = 0.0f;
        if ((i & 1) == 0) {
            t->bx = cosf(a0); t->by = sinf(a0);
            t->cx = cosf(a1); t->cy = sinf(a1);
        } else {
            t->bx = cosf(a1); t->by = sinf(a1);
            t->cx = cosf(a0); t->cy = sinf(a0);
        }
    }
    tri_n[0] = n;
    tri_active = 0;
}

/*
 * seed_thin — single thin rhombus (angles 36° + 144°), split by its
 * SHORT diagonal into 2 ACUTE Robinson triangles. Verifies the acute
 * deflation rule in isolation.
 */
static void seed_thin(float rot)
{
    /* Thin rhombus oriented with 36° apex at top, 36° at bottom,
     * 144° vertices on left/right. */
    float c18 = cosf(18.0f * (float)M_PI / 180.0f);
    float s18 = sinf(18.0f * (float)M_PI / 180.0f);

    /* Vertices, before rotation, scaled to fit unit-ish bounds. */
    float v_top_x = 0.0f,         v_top_y = c18;       /* 36° */
    float v_bot_x = 0.0f,         v_bot_y = -c18;      /* 36° */
    float v_rt_x  =  s18,         v_rt_y  = 0.0f;      /* 144° */
    float v_lf_x  = -s18,         v_lf_y  = 0.0f;      /* 144° */

    /* Apply rotation. */
    float cr = cosf(rot), sr = sinf(rot);
    #define ROT(X, Y, OX, OY) do { \
        OX = (X) * cr - (Y) * sr; \
        OY = (X) * sr + (Y) * cr; \
    } while (0)
    float tx, ty, bx, by, rx, ry, lx, ly;
    ROT(v_top_x, v_top_y, tx, ty);
    ROT(v_bot_x, v_bot_y, bx, by);
    ROT(v_rt_x,  v_rt_y,  rx, ry);
    ROT(v_lf_x,  v_lf_y,  lx, ly);
    #undef ROT

    /* Split by short diagonal (left-right): two acute triangles. */
    Triangle *out = tri_buf[0];
    out[0] = (Triangle){ TRI_ACUTE, tx, ty, rx, ry, lx, ly };  /* top half */
    out[1] = (Triangle){ TRI_ACUTE, bx, by, lx, ly, rx, ry };  /* bottom — flipped chirality */
    tri_n[0]  = 2;
    tri_active = 0;
}

/*
 * seed_thick — single thick rhombus (angles 72° + 108°), split by its
 * LONG diagonal into 2 OBTUSE Robinson triangles.
 */
static void seed_thick(float rot)
{
    /* Place rhombus with 72° vertices on left/right, 108° vertices
     * on top/bottom. Side length 1. */
    float c36 = cosf(36.0f * (float)M_PI / 180.0f);
    float s36 = sinf(36.0f * (float)M_PI / 180.0f);

    float v_lf_x = -c36,         v_lf_y =  0.0f;       /* 72° */
    float v_rt_x =  c36,         v_rt_y =  0.0f;       /* 72° */
    float v_tp_x =  0.0f,        v_tp_y =  s36;        /* 108° */
    float v_bt_x =  0.0f,        v_bt_y = -s36;        /* 108° */

    float cr = cosf(rot), sr = sinf(rot);
    #define ROT(X, Y, OX, OY) do { \
        OX = (X) * cr - (Y) * sr; \
        OY = (X) * sr + (Y) * cr; \
    } while (0)
    float lx, ly, rx, ry, tx, ty, bx, by;
    ROT(v_lf_x, v_lf_y, lx, ly);
    ROT(v_rt_x, v_rt_y, rx, ry);
    ROT(v_tp_x, v_tp_y, tx, ty);
    ROT(v_bt_x, v_bt_y, bx, by);
    #undef ROT

    /* Split by long diagonal (left-right between 72° verts): two
     * obtuse triangles, apex at the 108° vertex of each half. */
    Triangle *out = tri_buf[0];
    out[0] = (Triangle){ TRI_OBTUSE, tx, ty, lx, ly, rx, ry };  /* top half */
    out[1] = (Triangle){ TRI_OBTUSE, bx, by, rx, ry, lx, ly };  /* bottom half */
    tri_n[0]  = 2;
    tri_active = 0;
}

/* ----------------------------------------------------------------------- *
 * Bresenham line plotter.                                                  *
 * ----------------------------------------------------------------------- */

static inline char line_glyph_for(int dx, int dy)
{
    int adx = abs(dx), ady = abs(dy);
    if (adx >= 2 * ady) return '-';
    if (ady >= 2 * adx) return '|';
    if ((dx > 0) == (dy > 0)) return '\\';
    return '/';
}

/*
 * draw_line_styled — Bresenham line from (x0, y0) to (x1, y1).
 * Glyph is fixed (chosen by the caller from edge direction); the
 * caller also passes pair / attr. Bounds-checks every cell against
 * the screen (cols, rows-1 reserved for HUD) — the algorithm
 * doesn't know about the HUD strip.
 */
static void draw_line_styled(int x0, int y0, int x1, int y1,
                             int rows, int cols,
                             int pair, int attr, char glyph)
{
    int dx_abs = abs(x1 - x0);
    int dy_abs = abs(y1 - y0);
    int sx     = (x0 < x1) ?  1 : -1;
    int sy     = (y0 < y1) ?  1 : -1;
    int dx     =  dx_abs;
    int dy     = -dy_abs;
    int err    = dx + dy;
    int x = x0, y = y0;

    while (1) {
        if (y >= 2 && y < rows - 1 && x >= 0 && x < cols) {
            attron(COLOR_PAIR(pair) | attr);
            mvaddch(y, x, (chtype)(unsigned char)glyph);
            attroff(COLOR_PAIR(pair) | attr);
        }
        if (x == x1 && y == y1) break;
        int e2 = 2 * err;
        if (e2 >= dy) { err += dy; x += sx; }
        if (e2 <= dx) { err += dx; y += sy; }
    }
}

/* ===================================================================== */
/* §6  scene                                                              */
/* ===================================================================== */

typedef struct {
    bool     paused;
    int      speed;
    int      current_theme;
    Pattern  current_pattern;
    GlyphSet current_glyph;
    int      seed;
    float    rot;            /* extra rotation applied to the seed */
    float    time_secs;
    float    wind_x;
    float    flash_t;
} Scene;

/*
 * apply_perm — reshuffle the Perlin perm[] for the current
 * (seed, pattern) pair so the brightness field changes per pattern.
 * Same trick as truchet_tiles.c / wang_tiles.c.
 */
static void apply_perm(const Scene *s)
{
    perm_shuffle(s->seed ^ ((int)s->current_pattern * 0xA5A5A5));
}

/*
 * scene_regenerate — set the seed configuration, run K deflation
 * iterations, leave the result in tri_buf[tri_active].
 */
static void scene_regenerate(Scene *s)
{
    apply_perm(s);

    switch (s->current_pattern) {
    case PATTERN_STAR:
    case PATTERN_DEEP:  seed_star (s->rot); break;
    case PATTERN_THIN:  seed_thin (s->rot); break;
    case PATTERN_THICK: seed_thick(s->rot); break;
    case N_PATTERNS:    break;
    }

    int k = pattern_depth(s->current_pattern);
    for (int i = 0; i < k; i++) {
        deflate_step();
    }
    s->flash_t = 1.0f;
}

static void scene_reseed(Scene *s)
{
    /* Pick a fresh rotation and seed value. */
    s->seed = (int)hash3((int)(s->time_secs * 1000.0f),
                         (int)(s->wind_x * 100.0f), 0xC0FFEE);
    uint32_t h = hash3(s->seed, 0, 1);
    s->rot = ((float)(h & 0xFFFFu) / 65536.0f) * 2.0f * (float)M_PI;
    scene_regenerate(s);
}

static void scene_init(Scene *s)
{
    memset(s, 0, sizeof *s);
    s->paused          = false;
    s->speed           = SPEED_DEF;
    s->current_theme   = 0;
    s->current_pattern = PATTERN_STAR;
    s->current_glyph   = GLYPH_EDGES;
    s->seed            = 0xCAFE;
    s->rot             = 0.0f;
    scene_regenerate(s);
    s->flash_t = 1.0f;
}

/*
 * scene_tick — advance brightness wind. The tiling itself is static
 * until the user reseeds or changes pattern.
 */
static void scene_tick(Scene *s, float dt)
{
    s->time_secs += dt;
    s->flash_t   *= expf(-4.0f * dt);
    if (s->paused) return;

    float speed_mul = (float)s->speed / (float)SPEED_DEF;
    s->wind_x += WIND_X_BASE * speed_mul * dt;
}

/* ===================================================================== */
/* §7  screen                                                             */
/* ===================================================================== */

typedef struct {
    int cols, rows;
    int cx, cy;             /* screen centre — origin of the tiling */
    float scale;            /* world-unit → screen-cell scale       */
} Screen;

static void screen_layout(Screen *s)
{
    int top = 2, bottom = s->rows - 1;
    int avail_h = bottom - top;
    int avail_w = s->cols;

    s->cx = avail_w / 2;
    s->cy = top + avail_h / 2;

    /* Pick scale so the unit-circle seed fills ~90% of the smaller
     * dimension. With aspect correction (y · scale / ASPECT_Y_F),
     * radius 1 in world = scale cells horizontally and
     * scale/ASPECT_Y_F cells vertically. */
    float max_h = (float)(avail_w - 4) * 0.5f;
    float max_v = (float)(avail_h - 2) * 0.5f * ASPECT_Y_F;
    s->scale = (max_h < max_v) ? max_h : max_v;
    if (s->scale < 4.0f) s->scale = 4.0f;
}

static void screen_init(Screen *s)
{
    initscr();
    noecho();
    cbreak();
    curs_set(0);
    nodelay(stdscr, TRUE);
    keypad(stdscr, TRUE);
    typeahead(-1);
    color_init();
    getmaxyx(stdscr, s->rows, s->cols);
    screen_layout(s);
}
static void screen_free(Screen *s) { (void)s; endwin(); }
static void screen_resize(Screen *s)
{
    endwin();
    refresh();
    getmaxyx(stdscr, s->rows, s->cols);
    screen_layout(s);
}

/*
 * world_to_screen — apply scale + aspect + centre offset.
 */
static inline void world_to_screen(const Screen *sc, float wx, float wy,
                                    int *sx, int *sy)
{
    *sx = (int)(wx * sc->scale)              + sc->cx;
    *sy = (int)(wy * sc->scale / ASPECT_Y_F) + sc->cy;
}

/*
 * bright_at — slow drifting fBm spotlight value, [0, 1].
 */
static inline float bright_at(int sx, int sy, float wind_x)
{
    float nx = (float)sx * BRIGHT_SCALE_X + wind_x;
    float ny = (float)sy * BRIGHT_SCALE_Y * ASPECT_Y_F;
    float b  = fbm2(nx, ny);
    if (b < 0.0f) b = 0.0f;
    if (b > 1.0f) b = 1.0f;
    return b;
}

static int level_to_attr(float b)
{
    if (b > 0.65f) return A_BOLD;
    if (b < 0.35f) return A_DIM;
    return A_NORMAL;
}

/*
 * draw_triangle — render one triangle's three edges via Bresenham,
 * with per-cell brightness modulation. Acute and obtuse use different
 * ramp slots so the two types remain visually distinct.
 */
static void draw_triangle_edges(const Screen *sc, const Scene *s,
                                const Triangle *t)
{
    int ax, ay, bx, by, cx, cy;
    world_to_screen(sc, t->ax, t->ay, &ax, &ay);
    world_to_screen(sc, t->bx, t->by, &bx, &by);
    world_to_screen(sc, t->cx, t->cy, &cx, &cy);

    int ramp = (t->color == TRI_ACUTE) ? ACUTE_EDGE_RAMP : OBTUSE_EDGE_RAMP;
    int pair = PAIR_RAMP_BASE + ramp;

    /* For each edge, pick glyph from direction, apply brightness from
     * a sample at the edge midpoint (cheap approximation; fully
     * per-cell would require duplicating the Bresenham loop with
     * variable attr). */
    int mx, my;
    int attr;

    /* AB */
    char glyph_ab = line_glyph_for(bx - ax, by - ay);
    mx = (ax + bx) / 2; my = (ay + by) / 2;
    attr = level_to_attr(bright_at(mx, my, s->wind_x));
    draw_line_styled(ax, ay, bx, by, sc->rows, sc->cols, pair, attr, glyph_ab);

    /* BC */
    char glyph_bc = line_glyph_for(cx - bx, cy - by);
    mx = (bx + cx) / 2; my = (by + cy) / 2;
    attr = level_to_attr(bright_at(mx, my, s->wind_x));
    draw_line_styled(bx, by, cx, cy, sc->rows, sc->cols, pair, attr, glyph_bc);

    /* CA */
    char glyph_ca = line_glyph_for(ax - cx, ay - cy);
    mx = (cx + ax) / 2; my = (cy + ay) / 2;
    attr = level_to_attr(bright_at(mx, my, s->wind_x));
    draw_line_styled(cx, cy, ax, ay, sc->rows, sc->cols, pair, attr, glyph_ca);
}

/*
 * draw_triangle_centroid — render a single coloured glyph at the
 * triangle's centroid, in the centre-tint ramp slot.
 */
static void draw_triangle_centroid(const Screen *sc, const Scene *s,
                                   const Triangle *t)
{
    float wcx = (t->ax + t->bx + t->cx) / 3.0f;
    float wcy = (t->ay + t->by + t->cy) / 3.0f;
    int sx, sy;
    world_to_screen(sc, wcx, wcy, &sx, &sy);
    if (sy < 2 || sy >= sc->rows - 1) return;
    if (sx < 0 || sx >= sc->cols)     return;

    int ramp = (t->color == TRI_ACUTE)
             ? ACUTE_CENTER_RAMP
             : OBTUSE_CENTER_RAMP;
    int pair = PAIR_RAMP_BASE + ramp;
    char glyph = (t->color == TRI_ACUTE) ? '.' : 'o';
    int attr = level_to_attr(bright_at(sx, sy, s->wind_x));
    if (t->color == TRI_OBTUSE) attr |= A_BOLD;

    attron(COLOR_PAIR(pair) | attr);
    mvaddch(sy, sx, (chtype)(unsigned char)glyph);
    attroff(COLOR_PAIR(pair) | attr);
}

static void scene_draw(const Screen *sc, const Scene *s)
{
    int n = tri_n[tri_active];
    const Triangle *T = tri_buf[tri_active];

    bool draw_edges   = (s->current_glyph == GLYPH_EDGES
                      || s->current_glyph == GLYPH_BOTH);
    bool draw_centers = (s->current_glyph == GLYPH_CENTERS
                      || s->current_glyph == GLYPH_BOTH);

    if (draw_edges) {
        for (int i = 0; i < n; i++)
            draw_triangle_edges(sc, s, &T[i]);
    }
    if (draw_centers) {
        for (int i = 0; i < n; i++)
            draw_triangle_centroid(sc, s, &T[i]);
    }

    /* Reseed flash overlay. */
    if (s->flash_t > 0.05f) {
        int seed = (int)(s->time_secs * 1000.0f);
        attron(COLOR_PAIR(PAIR_FLASH) | A_BOLD);
        for (int sy = 2; sy < sc->rows - 1; sy += 2) {
            for (int sx = 0; sx < sc->cols; sx += 2) {
                if (((sx ^ sy ^ seed) & 7) == 0)
                    mvaddch(sy, sx, '*');
            }
        }
        attroff(COLOR_PAIR(PAIR_FLASH) | A_BOLD);
    }
}

static void screen_draw(Screen *sc, const Scene *s,
                        double fps, int sim_fps)
{
    erase();
    scene_draw(sc, s);

    int n = tri_n[tri_active];
    const char *state_str = s->paused ? "PAUSED" : "DRIFT ";

    /* Row 0 right — primary status. */
    char buf[HUD_COLS + 1];
    snprintf(buf, sizeof buf,
             " %5.1f fps  %3d Hz  %s  speed:%-3d ",
             fps, sim_fps, state_str, s->speed);
    int hx = sc->cols - (int)strlen(buf);
    if (hx < 0) hx = 0;
    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(0, hx, "%s", buf);
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);

    /* Row 0 left — title. */
    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(0, 1, " PENROSE TILING ");
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);

    /* Row 1 — pattern + glyph + theme + ramp swatch + N triangles. */
    int x = 1;
    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(1, x, " pattern:%-5s ", pattern_name(s->current_pattern));
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    x += 16;

    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(1, x, " glyph:%-5s ", glyph_set_name(s->current_glyph));
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    x += 14;

    attron(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    mvprintw(1, x, " theme:%-8s ", themes[s->current_theme].name);
    attroff(COLOR_PAIR(PAIR_HUD) | A_BOLD);
    x += 17;

    attron(COLOR_PAIR(PAIR_HUD));
    mvprintw(1, x, " ramp:");
    attroff(COLOR_PAIR(PAIR_HUD));
    x += 6;
    static const char ramp_glyphs[8] = { '`', '.', ',', ':', '-', 'o', '#', '@' };
    for (int i = 0; i < 8; i++) {
        int p = PAIR_RAMP_BASE + i;
        attron(COLOR_PAIR(p) | A_BOLD);
        mvaddch(1, x, (chtype)(unsigned char)ramp_glyphs[i]);
        attroff(COLOR_PAIR(p) | A_BOLD);
        x++;
    }
    attron(COLOR_PAIR(PAIR_HUD));
    mvprintw(1, x,
             "  K=%d  N=%d ",
             pattern_depth(s->current_pattern), n);
    attroff(COLOR_PAIR(PAIR_HUD));

    /* Bottom hint. */
    attron(COLOR_PAIR(PAIR_HINT) | A_BOLD);
    mvprintw(sc->rows - 1, 0,
             " n/p:pattern  g/G:glyph  t/T:theme  +/-:drift  spc:pause  r:reseed  q:quit ");
    attroff(COLOR_PAIR(PAIR_HINT) | A_BOLD);
}

static void screen_present(void) { wnoutrefresh(stdscr); doupdate(); }

/* ===================================================================== */
/* §8  app                                                                */
/* ===================================================================== */

typedef struct {
    Scene                 scene;
    Screen                screen;
    int                   sim_fps;
    volatile sig_atomic_t running;
    volatile sig_atomic_t need_resize;
} App;

static App g_app;

static void on_exit_signal  (int sig) { (void)sig; g_app.running     = 0; }
static void on_resize_signal(int sig) { (void)sig; g_app.need_resize = 1; }
static void cleanup(void)             { endwin(); }

static void app_do_resize(App *app)
{
    screen_resize(&app->screen);
    app->need_resize = 0;
}

static bool app_handle_key(App *app, int ch)
{
    Scene *s = &app->scene;
    switch (ch) {
    case 'q': case 'Q': case 27 /* ESC */: return false;
    case ' ':           s->paused = !s->paused;                       break;
    case 'r': case 'R': scene_reseed(s);                               break;

    case '=': case '+':
        if (s->speed < SPEED_MAX) s->speed *= 2;
        if (s->speed > SPEED_MAX) s->speed  = SPEED_MAX;
        break;
    case '-':
        s->speed /= 2;
        if (s->speed < SPEED_MIN) s->speed  = SPEED_MIN;
        break;

    case ']':
        app->sim_fps += SIM_FPS_STEP;
        if (app->sim_fps > SIM_FPS_MAX) app->sim_fps = SIM_FPS_MAX;
        break;
    case '[':
        app->sim_fps -= SIM_FPS_STEP;
        if (app->sim_fps < SIM_FPS_MIN) app->sim_fps = SIM_FPS_MIN;
        break;

    case 't':
        s->current_theme = (s->current_theme + 1) % N_THEMES;
        theme_apply(s->current_theme);
        break;
    case 'T':
        s->current_theme = (s->current_theme + N_THEMES - 1) % N_THEMES;
        theme_apply(s->current_theme);
        break;

    case 'n': case 'N':
        s->current_pattern = (Pattern)(((int)s->current_pattern + 1) % N_PATTERNS);
        scene_regenerate(s);
        break;
    case 'p': case 'P':
        s->current_pattern = (Pattern)(((int)s->current_pattern + N_PATTERNS - 1) % N_PATTERNS);
        scene_regenerate(s);
        break;

    case 'g':
        s->current_glyph = (GlyphSet)(((int)s->current_glyph + 1) % N_GLYPH_SETS);
        break;
    case 'G':
        s->current_glyph = (GlyphSet)(((int)s->current_glyph + N_GLYPH_SETS - 1) % N_GLYPH_SETS);
        break;

    default: break;
    }
    return true;
}

int main(void)
{
    srand((unsigned int)(clock_ns() & 0xFFFFFFFF));
    atexit(cleanup);
    signal(SIGINT,   on_exit_signal);
    signal(SIGTERM,  on_exit_signal);
    signal(SIGWINCH, on_resize_signal);

    App *app     = &g_app;
    app->running = 1;
    app->sim_fps = SIM_FPS_DEFAULT;

    screen_init(&app->screen);
    scene_init(&app->scene);

    int64_t frame_time  = clock_ns();
    int64_t sim_accum   = 0;
    int64_t fps_accum   = 0;
    int     frame_count = 0;
    double  fps_display = 0.0;

    while (app->running) {

        if (app->need_resize) {
            app_do_resize(app);
            frame_time = clock_ns();
            sim_accum  = 0;
        }

        int64_t now = clock_ns();
        int64_t dt  = now - frame_time;
        frame_time  = now;
        if (dt > 100 * NS_PER_MS) dt = 100 * NS_PER_MS;

        int64_t tick_ns = TICK_NS(app->sim_fps);
        float   dt_sec  = (float)tick_ns / (float)NS_PER_SEC;

        sim_accum += dt;
        while (sim_accum >= tick_ns) {
            scene_tick(&app->scene, dt_sec);
            sim_accum -= tick_ns;
        }

        frame_count++;
        fps_accum += dt;
        if (fps_accum >= FPS_UPDATE_MS * NS_PER_MS) {
            fps_display = (double)frame_count
                        / ((double)fps_accum / (double)NS_PER_SEC);
            frame_count = 0;
            fps_accum   = 0;
        }

        int64_t elapsed = clock_ns() - frame_time + dt;
        clock_sleep_ns(NS_PER_SEC / 60 - elapsed);

        screen_draw(&app->screen, &app->scene, fps_display, app->sim_fps);
        screen_present();

        int ch = getch();
        if (ch != ERR && !app_handle_key(app, ch))
            app->running = 0;
    }

    screen_free(&app->screen);
    return 0;
}
